== Coping with rape-kisses

If a woman “rape-kiss”es me, https://www.shlomifish.org/humour/bits/true-stories/my-first-kiss/[I will not resist and even try to enjoy it]. Do note that it will still feel awkward, so please don't do this.

== Meeting invitations

Given there are many women (and likely many men) whom my mismanagement as https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/[a Terran terminator] caused heartbreak, sadness, and grief, I will accept meeting invitations from any woman who isn't overly fat and unkempt. Before it, she and I will donate some money to a charity of her choice, and tweet about it, while possibly hyperlinking to her website. At the end of the meeting, we may both hug upon mutual agreement.

== Sharing our sex lives

Given I enjoy
https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/bad_acting_ftw.xhtml[hacky acting], I may need to kiss fellow actresses on stage.

I don't own 100% of your sex-life either. E.g.: as of 2023-05-16 , my
current celebrity crush is Tiffany Alvord, and https://www.shlomifish.org/meta/nav-blocks/blocks/#tiffany_alvord_sect[I feature her in my screenplays] as kissing 3 actors, 2 muppets, and 1 animated draconequus. I hope that she, or her stuntdoubles, comply, when-and-if the screenplays are produced.

As far as I am concerned, my significant other can 4th-base four, female, underage, kangaroos.

== Favourite pastimes

Nevertheless, I still have the need for an intimate, Romantic, relationship. With a woman. I cannot guarantee I'll love you forever, but I'll try hard not to take you for granted, and let me know when and if I do.

One of my favourite pastimes is crossover https://www.shlomifish.org/humour/image-macros/indiv-nodes/standup_philosopher.xhtml[philosophy/comedy] (including stand-up one, or one done on online chats, or forums). Other pasttimes I enjoy include:

* Checkers, backgammon and other board games https://www.shlomifish.org/meta/FAQ/do_you_play_chess.xhtml[but not chess]
* Biking
* https://www.shlomifish.org/meta/FAQ/homesite_or_blog.xhtml[Webpublishing and blogging]
* https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/hollywood_screenplay_format.xhtml[Screenwriting]
* https://www.shlomifish.org/meta/FAQ/#computing[Software development]
* https://en.wikipedia.org/wiki/Tabletop_role-playing_game[Tabletop role-playing games (TTRPG)], e.g: https://en.wikipedia.org/wiki/Dungeons_%26_Dragons[Dungeons &amp; Dragons], Star Wars Role-playing-game
* Fencing using soft, harmless, swords
* Playing https://en.wikipedia.org/wiki/Table_tennis[ping-pong]
* Playing https://en.wikipedia.org/wiki/Basketball[Basketball]
* Eating at restaurants
* https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/bad_acting_ftw.xhtml[Acting in a hacky way]
* Playing computer games
* Watching youtube videos
* Listening to music
* Hiking or taking walks.
* Playing https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/#fantasia-vs-fantastecha[the Role Playing Game of Greater Fantasia]
* Attending https://en.wikipedia.org/wiki/Science_fiction_convention[sci-fi/fantasy/etc. conventions (“Cons”)]
* There are other types of conventions, parties, or assemblies I enjoy, as long as I will be able to quickly teleport back home.
* Solving mathematical, logical, or Competitive Programming riddles and puzzles
* I like weight-training (e.g: at gyms). I also liked some introductory Yoga sessions I attended. There are other physical fitness activities I enjoy.

== Wedding rings’ policy

link:++https://www.shlomifish.org/humour/fortunes/show.cgi?id=sharp-reddit--rindolf-planning-his-wedding++[My wedding rings policy].

== Modelling

I might pose naked or scantily clad, if I'm offered enough money and/or it's a noble enough cause, and it isn't too time-consuming. You can also try hiring a temporary lookalike of mine or peruse https://en.wikipedia.org/wiki/Akashic_records[the Akashic records]. I am also open for modelling captioned T-shirts, and shorts.

== Physical freedom

If you tie me to bed, or lock me inside/outside, I might break up with you, and get a restraining order.

== Alimony

If we divorce, you can have https://www.chabad.org/library/bible_cdo/aid/16480/jewish/Chapter-7.htm[half my cash] (or more?). I'll https://www.shlomifish.org/humour/Queen-Padme-Tales/[likely make it back]. Furthermore, I swear I will not require alimony from you.

== Priorities

I try to prioritize helping people online / offline:

* https://www.shlomifish.org/humour/Terminator/Liberation/ongoing-text.html#emma-watson-and-the-children-get-icecream[“Emma Watson and the children getting Icecream” (from “Terminator: Liberation”)]

== Family names

Let's suppose, without loss of generality, that your premarital name is “Jane Austen”.

Then, if we marry:

* I will remain Mr. Shlomi Fish.
* We can call the children “Austen”, but hopefully not “Austen-Fish”
* I suggest your name will remain “Jane Austen”, but you can opt to change it to “Jane Austen-Fish”, or “Jane Fish”, or whatever.
