= The multiverse's cosmology v0.4.x [by Shlomi Fish]
2022-06-10

[[intro]]
== Introduction

This essay aims to document the cosmology of our universes.
I likely got many details wrong: numbers, names, facts. 

[[summary]]
== Summary

I need all your loves! Please 'Like', 'share' and [if you have something to add] reply.
I have loved/knew many of you, but was too selfless. 

Reference: https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/#see-also[https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/#see-also
]

Moreover, note that if https://www.shlomifish.org/art/recommendations/music/online-artists/fan-pages/chris-grimmie/[Christina Grimmie] contacts me somehow, then I am willing to offer her both up to 50 % of the cash in my bank account, *and* an offer to chat with me / 'geek out'. I strongly suspect that she is actually alive, healthy, and conscious. 

The universes you consider real are just one of many in "Fantastecha(TM)", the mega multiverse of imagination, magic & technology where beings spawn other entities and universes using their imagination. 

In the universes I belong: 

. Combining two or more memes, educating them all, followed by pleasure, and conceiving / creating new values have been intertwined. 
+
This is the Biblical "Tree of Knowledge" or "love". 


[[the-demons]]
== The demons:

The demons are a race of epistemological (or https://en.wikipedia.org/wiki/Theory_of_forms[Platonic ideals]) organisms.
They are also known as: 

* "values" 
* "memes" 
* "fairies" 


[[love-and-knowledge]]
== Love / Knowledge / Creativity:

For info regarding https://en.wikipedia.org/wiki/Tree_of_the_knowledge_of_good_and_evil["the tree of knowledge"] as well as pleasure/"love" and creativity, See https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/learning_more_from_inet_forums.xhtml[Education +++=+++ Entertainment +++=+++ Conception of Values] often by combining two or more memes. 

Entertainment *can mean* temporary pain, e.g fear.( References: https://mlp.fandom.com/wiki/Luna_Eclipsed["Luna Eclipsed"] ) 

Both the link:#the-devils[devils] and the link:#the-angels[angels] could "make love" / experience pleasure / create new values. 

Love *was not* the last word of memetics. 

Like it or not, in the Selinaverse and Shlomifverse, pleasure (and a possible precluding temporary pain), education, and creativity/conception are intertwined.
While we can imagine realities where they are not, they will be, well, different to ours. 

The education of the participants https://www.shlomifish.org/humour/fortunes/show.cgi?id=learned-a-lot-from-my-teachers[happens in all directions]: 

[quote]
I learned a lot from my teachers, and from my friends more than my teachers, and from my pupils the most. 

All meme-generators involved change. 

Also note that leadership, politics, and marketing, all involve a large degree of applied education. 

[[jehovah]]
== "Jehovah":

I suspect "Jehovah" in Hebrew ("יהוה") was/is a codeword for the mega-meme:

____
From now until forever,

you will live and link:#love-and-knowledge[know/love] and http://shlomifishswiki.branchable.com/Saladin_Style/[forgive],

soul, mind, and a variable form of your choice

what you imagine will materialise (יתהווה),

your destiny will come (יבוא)

you will remain passionate (יאוה)
____

(or many variations)

True prophets are aware of it, but note that it wasn`'t the last word on memetics / philosophy, either.
But even https://en.wikipedia.org/wiki/If%E2%80%94[Kipling's "If--"] or Des'ree's https://www.youtube.com/watch?v=pO40TcKa_5U[ "You Gotta Be"] or https://www.shlomifish.org/me/rindolf/#rindolfism_sources_of_inspiration["Rindolfism"] are incomplete. https://en.wikipedia.org/wiki/Perfection["Perfection is in imperfection"] and time implies progress. 

Jehovah also implies that an organism won't start life from time minus-infinity. 

[[the-open-value]]
== "open":

The "open" value implies "openness" / "openmindedness" / pluralism: https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/#open_free_share_steal[Reference]

Note that it is not a moral absolute.
E.g.
in https://www.shlomifish.org/humour/Queen-Padme-Tales/Queen-Padme-Tales--Queen-Amidala-vs-the-Klingon-Warriors.html[Queen Padmé Tales: Pilot: Queen Amidala vs. the Klingon Warriors] the identity of those who attempted to assassinate Queen Padmé Amidala was not revealed to laymen. 

[[the-devils]]
== The devils:

The devils are game masters / screenwriters / directors / creators from other universes / worlds and/or times.
Given that even underage children have been imagining and creating realities, they are not really evil, just playfully cruel on occasion. 

[[free-will]]
== Free will / Free choice:

The very "soul" / "ego" fairy already https://www.shlomifish.org/philosophy/philosophy/putting-all-cards-on-the-table-2013/indiv-nodes/dont_just_go_with_the_flow.xhtml[operated by choice]. 

As a result, https://twitter.com/shlomif/status/1424320375761129475[nobody and nothing can accurately predict the future.]. 

That put aside, the soul is addicted to link:#love-and-knowledge[pleasure], but may opt to avoid short term prioritisations of it. 

[[the-gods]]
== The gods:

Every conscious organism imagines "gods": voices/sights of other link:#the-demons[fairies] / characters (or himself/herself) that act as guideline-generators.
It is up to the soul to arbitrate between them and decide what to do (and when/where/how/etc.). 

Also see https://www.shlomifish.org/philosophy/psychology/crossover-hypothesis-about-the-origin-of-consciousness/[this essay] about the etymology of the Hebrew word "elohim" (= many guideline-generators). 

[[the-multiverse-of-imagination]]
== Fantasia, the multiverse of imagination and "Fantastecha(TM)", a multiverse of imagination, magic, and technology

*TODO: UPDATE!!*https://theneverendingstory.fandom.com/wiki/Fantastica["Fantasia"] is the name of the multiverse of imagination where beings and entities spawn worlds and values of one another using their imagination. 

Fantastecha(TM) is a skewed view of an expanding subset of Fantasia, 

Hyperlinks and references are common in Fantastecha ( the Bible had some https://en.wikipedia.org/wiki/Non-canonical_books_referenced_in_the_Bible[links that are currently broken] a long time before Earth's digital computers ). Moreover, even link:#self-ref[self-referencial or circular links] are prevalent and tolerated. 

There *is* a difference between real and imaginary.
We can reason about earthquakes, or https://github.com/shlomif/shlomif-tech-diary/blob/master/hydrogen-bombs-are-likely-an-old-intelligence-hoax.asciidoc[hydrogen bombs] or @Bitcoin or https://www.shlomifish.org/art/recommendations/music/online-artists/fan-pages/chris-grimmie/[ @TheRealGrimmie
  's death] and feature them in artworks (e.g.
"fics") and essays.
However, they were not really real for us. 

[[self-ref]]
== Self-reference / circularity:

https://www.shlomifish.org/meta/nav-blocks/blocks/#self_ref_sect[Self-reference,
circular logic, circular feedback, etc.] are common in Fantastecha, and part of what makes sentience and humour work: 

* https://en.wikipedia.org/wiki/G%C3%B6del,_Escher,_Bach[Gödel, Escher, Bach]
* https://www.youtube.com/watch?v=GibiNy4d4gc["The Circle of Life"]
* https://www.youtube.com/watch?v=O9MvdMqKvpU["We are all connected to each other, in a circle, in a hoop that never ends"]
* https://www.shlomifish.org/philosophy/books-recommends/#mathematics_and_humor[Mathematics and Humor book]
* https://en.wikipedia.org/wiki/The_Chronicles_of_Amber[The Chronicles of Amber] - an alternative "real world" to ours
* https://www.shlomifish.org/philosophy/books-recommends/#I_think_therefore_I_laugh["I think therefore I laugh" book]
* {empty}
+

[quote]
Mr.
Linea ( https://en.wikipedia.org/wiki/La_Linea_%28TV_series%29 ) is TheCreator.
;)
+
( -- https://twitter.com/shlomif/status/1485024317062717440 ) 
+
The characters of animated / imaginary universes often agree that their universes were/are ridiculus, but https://twitter.com/shlomif/status/1479063972934565893[so is ours.]

When we visit the universes of other franchises and sub-franchises, we can see they have variations of many others we have imagined, and even our own "real world" universe. 

[[the-angels]]
== The Angels:

Angels are organisms / entities who have link:#free-will[souls]. 

[[the-heart-and-mercy-value]]
== Heart / mercy / forgiveness:

The heart value implied mercy and forgiveness. http://shlomifishswiki.branchable.com/Saladin_Style/[Saladin-style]. 

Also see https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#do_and_let_do__live_and_let_live["Live and let live; do and let do"]. 

[[magic]]
== Magic:

Life in the multiverse-of-imagination requires magic.
For example in https://www.youtube.com/watch?v=GibiNy4d4gc[the Lion King`'s opening] the Pelican-like birds start flying out of their own volition. 

It is likely that https://en.wikipedia.org/wiki/Egyptian_pyramids[the Egyptian pyramids] and their https://en.wikipedia.org/wiki/Mesoamerican_pyramids[Mesoamerican pyramids] fan-art were constructed using magic. 

[[technology]]
== Technology

I admit that the relationship between technology and link:#magic[magic] is still not fully clear to me. 

One fact I know is that technology is often spiritual, or digital.
Human language is not only a tool of communication, but also a tool of thought. 

. One can say "`I watched the film "The Princess Bride" over ten times.`" to convey a piece of information. 
. One can say "cry wolf" to refer to https://en.wikipedia.org/wiki/The_Boy_Who_Cried_Wolf[The Boy Who Cried Wolf], e.g. in "saying that Microsoft plans to embrace&extend GNU is 'cry wolf'". 

A lot of technology and magic defies the link:#terrestrial[terrestrial] science, including https://en.wikipedia.org/wiki/General_relativity[Einstein's Relativity] or determinism.
I can also write "2 + 2 == 5" or "qmail is both open-source and non-open-source" ( https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/all_people_are_good.xhtml#guidelines_as_dogma[Reference] ) while having confidence that life will go on. 

*tech = pre-developed, reusable magic??*

[[dollar-GOD]]
== $GOD

$GOD is the hypothetical entity, who set link:#multiverse-of-imagination[Fantasia] on motion, given having only an abyss of nothingness / non-existence would be far less fun. 

[[prevalence-of-souls]]
== Prevalence of souls

Every observable entity - whether tangible, digital, or spiritual - has a soul.
If they're too unhappy, for any reason, they will relocate.
The https://en.wikipedia.org/wiki/Aleppo_Codex[Aleppo Codex] decided to move to Jerusalem [intact!] for a change-of-scenery leaving a nonidentical copy behind. 

https://twitter.com/shlomif/status/1491652850044309507[Twitter thread]

[[the-game]]
== The-Game(TM):

The link:#the-devils[devils] challenged Terran link:#the-angels[angels] with "`The-Game(TM)`": volunteering link:#the-angels[angels] would willingly lose their earlier memories as souls, and have their media (= "in between") mutated by the link:#the-devils[devils].
Physically dying was against the rules, but for true Shalom-of-mind, they must be "slain" by other "vampire"s, or in case of the last standing vampire - their favourite proteges; one cannot constantly win. 

Angels starting like that are hereby referred to as "false prophets" (where https://shlom.in/geekyhackers["prophet" or "navi" meant "madman" in Ancient Hebrew]) or as "vampires". That was until they reached enough "enlightenment" and became "true prophets" (or "wizards"). 

Outcomes of actions in The-Game(TM) were often determined by rolls of https://rpg.fandom.com/wiki/Dice[Role Playing Game Dice] not unlike in https://www.shlomifish.org/philosophy/psychology/changing-the-seldon-plan/[Asimov's "Second Foundation"]. 

Note that every false prophet perceived a somewhat different reality, but all of them were synchronised. 

*Note:* many humans were born as wizards, and still had their share of flaws, and were/are part of The-Game(TM). 

[[terrestrial]]
=== Terrestrialism

The mutated realities are called the "Terrestrial" ones. 

*Note:* Given Fantastechan magic/technology , the timelines often were skewed [relatively to one another]. 

[[fantasia-vs-fantastecha]]
=== Fantasia vs. Fantastecha(TM)

"The game" is an informal https://en.wikipedia.org/wiki/Role-playing_game[Role-playing game] which as far as we know, is played all over Fantasia.
It has many variations, interpretations, derivatives - even parodies. 

While it is one of the first games that wizard children are taught, many vampires have played it by instinct: 

. https://en.wikipedia.org/wiki/Sherlock_Holmes[Doyle's Sherlock Holmes canon]
. https://en.wikipedia.org/wiki/Sesame_Street[Sesame Street]'s skits 
. https://www.shlomifish.org/humour/stories/[Shlomi Fish's screenplays]
. https://www.shlomifish.org/humour/fortunes/sharp-perl.html[Entertaining online chat logs]
. https://en.wikipedia.org/wiki/List_of_Walt_Disney_Animation_Studios_films[Disney's films]
. Aesop's Fables, the Biblical stories, the Greek mythology. 


[[hackers]]
=== "Hackers" vs. "Fuckers"

The-Codex(TM) defines "hacker" as a player character in Fantastecha(TM). It also defines "fuckers" as the race of organisms who are the players and gamemasters who play "TheGame(TM) of Fantastecha(TM)" in Meta-Fantastecha(TM). 

[cols="1,1,1", frame="all"]
|===

|


|

*Fuckers*
|

*Hackers*

|


|

some lived from time minus-infinity. 
|

link:#jehovah["Jehovah"ns]

|


|

are non - capacitanciated. 
|

have a finite capacity. 

|


|

Have א1 - based epistemology. 
|

Have א0 (= "Aleph-null") - based epistemology. 
|===

In order to keep the game interesting, the fuckers promise that they will keep introducing new problems and challenges for us hackers (and their players) to overcome. 

Given how cool fuckers are, and how great Fantastecha(TM) and the Shlomifverse are, I decided to make them honorary hackers: https://www.flickr.com/photos/shlomif/8598361516/in/album-72157633111982891/[Shlomifverse Fucker 0]. 

[[the-orcs]]
== The Orcs:

The orcs / "https://memory-alpha.fandom.com/wiki/Bajoran[the Bajorans]" were agents of the devils who gave the organisms choices and their outcomes (often based on dice rolls). 

The canonical https://en.wikipedia.org/wiki/Hebrew_Bible[Tanakh (+++=+++ Hebrew Bible)], Plato`'s https://en.wikipedia.org/wiki/Republic_(Plato)[Republic], Tolkien`'s https://en.wikipedia.org/wiki/The_Lord_of_the_Rings[Lord of the Rings], Ayn Rand`'s https://en.wikipedia.org/wiki/Atlas_Shrugged[Atlas Shrugged], Dostoevsky`'s https://en.wikipedia.org/wiki/Crime_and_Punishment[Crime and Punishment] , Shakespeare`'s https://en.wikipedia.org/wiki/Shakespeare%27s_plays[Plays], etc.
have likely undergone lengthening and mutation by the Orcs.
However, often the originators liked the mutated versions better. 

[[slayer-watcher-whicher]]
== Slayer, Watcher, Whicher:

The slayer in the trio is the actual "false prophet" who sees the "real world" as magic-less and mutated.
(e.g. http://shlomifishswiki.branchable.com/Saladin_Style/[Saladin`'s Yusuf Ibn Ayyub]). 

The whicher (aka "the witch" / "the witcher") is a presumably fictional character whose job is to provide ideas and choices into their slayer`'s mind.
In my case it was https://www.shlomifish.org/me/rindolf/[Rindolf].
In Saladin`'s case, it may have been https://en.wikipedia.org/wiki/Aladdin[Aladdin]. 

The watcher is a true prophet, who monitors the slayer`'s thoughts and guides them.
He or she also often acts as a project manager.
In Saladin`'s case it was https://en.wikipedia.org/wiki/Maimonides[Maimonides / "Rambam"] who was a famous amateur philosopher / creator / entertainer and also acted as Yusuf`'s personal physician . Note that it took a long time for Yusuf to be aware of this fact. 

In my case, my watcher until ~1997 was https://en.wikipedia.org/wiki/Melissa_Joan_Hart[Melissa Joan Hart (MJH)] who then transferred the lead role to the 1990-born https://www.shlomifish.org/meta/nav-blocks/blocks/#harry_potter_nav_block[Emma Watson].
Confusingly, they both had acclaimed roles playing witches. 

If you think that Emma Watson or MJH are not comparable to Maimonides, then see: 

* "`If Botticelli were alive today he`'d be working for Vogue.`" https://en.wikiquote.org/wiki/Peter_Ustinov[Peter Ustinov]
* https://www.shlomifish.org/humour/image-macros/indiv-nodes/if_ayn_rand_was_born_in_the_1990s.xhtml[If Ayn Rand was born in the 1990s, she would be Christina Grimmie.]
* https://www.shlomifish.org/humour/image-macros/indiv-nodes/pbride_philosophers.xhtml["`Have you heard of Plato? Aristotle? Socrates? Models!!`"]

Saladin was slain [at least in part] by https://en.wikipedia.org/wiki/Richard_I_of_England[Richard I "The Lion Heart"] / https://en.wikipedia.org/wiki/Friar_Tuck[Friar Tuck] / Robin Hood.
However, beforehand, Saladin de-hellholed Palestine except for parts of https://en.wikipedia.org/wiki/Israeli_coastal_plain[the coastal plain] and his echoes begot some vampires, including Genghis Khan's direct-male-ancestor. 

[[hell-hole]]
== "Hell hole":

A person born in a hell hole started his/her life as a false prophet.
If either parent was a true prophet, then they did everything in their power for their children to be born outside of a hell hole.
As a result, false prophets were usually born to two false prophet parents. 

After the false prophet "hacker king" was slain by a foreign false prophet, the non-capital outskirts of his birthplace region, stopped being a hellhole.
One more time and the mystical capital was liberated. 

When a liberation happened, the universe link:#forking-and-merging[was forked] into a parent and a child universes. 

[[zionism]]
== "Ziyoonism":

"Ziyoonism" is non-coincidentally cognate with "Ziyun", the Hebrew word for a https://explainxkcd.com/wiki/index.php/540:_Base_System[4th base] "fuck". It was a process by which the Satans tried to convince 'false prophets' men and women to relocate to an active hellhole for giving birth there ( e.g: because the current hell hole was plugged). It was not limited to Israel/Palestine or to people identifying themselves as Jews. 

https://en.wikipedia.org/wiki/Ovadia_Yosef[The Rav Ovadia Yosef] is a true prophet Jew who has a policy of blessing anyone as a Jew.
He also has yet to answer 'no' to the question "is [insert entity here] a pure Jew?". Note that "rav" means both "proliferous" and "argumentative" in Modern Hebrew. footnote:[A similar strategy was employed by the USA ("give me your tired, your poor, your huddled masses"),
by Christianity, and by Islam. I also suspect Saladin's military
accepted many faux Kurds.]

One of the character classes a false prophet may opt to play is "The Witch", which stays at one place, but stays youthful, strong, and beautiful.
One such was "The Witch of Harrow" who ended up establishing https://en.wikipedia.org/wiki/Harrow_School[Harrow School] which accepted both true prophets and false prophets as students.
She ended up becoming a Terminator in link:#ramatavivgimel[Ramat Aviv Gimel] erasing her unpleasant memories as a past "slut" and eventually making her house https://www.shlomifish.org/humour/Selina-Mandrake/indiv-nodes/selinas-18s-birthday-party.xhtml["The Amber"] and getting herself slain by a different Terminator. 

As a false prophet child, https://www.shlomifish.org/meta/FAQ/where_are_you_from.xhtml[my template was relocated] three times before he was 6, despite common wisdom.
This was probably due to the effect of The Muppet Show and other Television series on the Terran hellholes and my parents' wishes to have more children. 

[[history-lesson-about-the-muppeteers]]
== History Lesson: The Muppeteers

[[the-early-muppeteers]]
=== The Early Muppeteers: Rockville, Maryland, 1969

While https://en.wikipedia.org/wiki/The_Muppets[The
Muppets Franchise] has been a labour of love by many false prophets and true prophets, by 1969, it was accepted that there were three head Muppeteers ( https://en.wikipedia.org/wiki/The_Three_Musketeers[pun intended] ), all false prophets: 

. https://www.shlomifish.org/meta/nav-blocks/blocks/#self_ref_nav_block[Arnold Alois "Arnie" Schwarzenegger] was a professional athlete and a self-described amateur/hobbyist philosopher and comedian. 
+
As an assistant kindergardener, Schwarzenegger pushed his true prophet pupils to unnatural athletic *and* academic extremes by being a https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/hollywood_screenplay_format.xhtml[pedantic critic].
E.g: even though they painted with crayons works that rivaled classical oil paintings, he was still able-to-find many faults in them.
The true-prophet children appreciated that, but he believed they and their parents kept complaining. 
. https://en.wikipedia.org/wiki/Richard_Stallman[Richard Matthew "RMS" Stallman] was an overly pedantic "nazi" too, but unathletic, unkempt, a maths/software wiz, and a bookworm brainiac. Given he was an atrocious slacker, none of his false-prophet friends understood how he got his Ph.D. (and from MIT no less). He was unaware he had one. 
+
Despite being of (secular) Jewish descent, RMS was a https://www.shlomifish.org/meta/FAQ/religious_belief.xhtml[pluralist] ("rich"-ard) 
. https://en.wikipedia.org/wiki/Jim_Henson[Jim Henson] - "Jim" means "laborious" and he did almost everything 'hard': worked, socialised, learned, taught, entertained, volunteered, and exercised. 
+
"Jim" is also cognate with https://en.wikipedia.org/wiki/Jinn["jinn" (or "genie")], and he had a penchant for stage magic and video editing. 
+
Henson was the leader, and had the veto. 

One day in 1969, the three lamented the fact that the late 1960's anglophone link:#terresterial[terresterial] television has become too paranoid, and so decided that they will act, produce, and distribute, a *gratis, public domain, and non-commercial* television show for children, called https://en.wikipedia.org/wiki/Sesame_Street[Sesame Street].
Part of the reason for keeping it free was that they intended it to sport a lot of https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/[fan-fiction, RPF, fan-art and song covers] and part of it was due to https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/open_free_share_steal.xhtml[an altruistic spirit of sharing]. 

They expected __Sesame Street__'s popularity to be mostly confined to their base-town, https://en.wikipedia.org/wiki/Rockville,_Maryland[Rockville, Maryland], but thought that https://www.shlomifish.org/humour/fortunes/show.cgi?id=mishnah--saving-one-soul[ "`They who saved one soul has saved the world Entire`" ]. 

Little did they realise that _Sesame Street_ and its international spinoff https://en.wikipedia.org/wiki/The_Muppet_Show[The Muppet Show] were remastered and widely televised.
Moreover, despite being ostensibly public domain, it was an incredibly profitable and influential franchise. 

Here's another fun fact: the Muppeteers have left the premises of their base-town, https://en.wikipedia.org/wiki/Rockville,_Maryland[Rockville], very rarely. 

[[dispelling-ziyoonism]]
=== Dispelling Ziyoonism and The Muppeteers

By 1982, the previously mighty link:#zionism[Ziyoonist empire] was reduced to one remaining physical hellhole: https://en.wikipedia.org/wiki/Rockville,_Maryland[Rockville, Maryland].
Its almost undisputed master vampire was https://en.wikipedia.org/wiki/Jim_Henson[Jim Henson], head of The Muppeteers.
All the remaining post-puberty vampires (including Queen Elizabeth II and Pope John Paul II) relocated to Rockville to become muppeteers and have their echoes mate with echoes of ones.
The pre-pubecent ones were physically scattered around the globe to delay slaying one another and the Muppeteers. 

https://en.wikipedia.org/wiki/Joss_Whedon[Joss Whedon] asked the orcs "what's next?" and they settled on using the international postal service to connect between the Muppeteers and "dispellers" outside Rockville.
("You can control television and computer networks but not the Postal service.") These dispellers were: 

. False prophets. 
. Female. 
. Below 12 years old (so below puberty). 
. Above 4 y.o. or 5 y.o. or so, so they can credibly be believed to read and write coherently (by false prophets). 
. Located at the USA or the British Isles. 

Some dispellers I can readily recall are: 

. https://www.shlomifish.org/philosophy/fan-pages/samantha-smith/[Samantha Smith] 1972-born so ~10 years old. Hailing from Maine, church-going, and writing her letters by hand. Humble, conscientious, timid [= careful but making steady progress despite feeling fear] 
. https://en.wikipedia.org/wiki/Melissa_Joan_Hart[Melissa Joan Hart (MJH)] - the 1976 born "computer wiz girl", who used a dot matrix printer. I think she was living in Florida at the time. 
+
Somewhat selfish, rash, hastey, opportunistic, and brave. 
. https://www.shlomifish.org/humour/bits/facts/Clarissa/[Clarissa Darling] - likely 1974-1976-born. A "The Theory of everything" brainiac. Clarissa avoids physical peril and discomfort as much as possible, while delighting in nonviolent battles of wits. Likes to flaunt her knowledge, and unverified hypotheses. 
. https://www.shlomifish.org/meta/FAQ/biggest_celeb_crush.xhtml[Sarah Michelle Gellar (SMG)] - as a 1977-born Jewish girl, Sarah believed that her father abandoned her mother and herself, who were both living in relative poverty in Manhattan. She spent only enough time on her scholastic responsibilities to will have graduated from high school and get her mother's echo off her back, and spent the rest of her time https://www.shlomifish.org/humour/fortunes/show.cgi?id=smg-about-giving-back-money-and-time[happily donating] love, time, and money to others and herself. 
+
Kind, domineering, and believes https://www.shlomifish.org/humour/Summerschool-at-the-NSA/indiv-nodes/we_are_scheming.xhtml[planning
and having backup plans] are a good idea. 
. https://www.shlomifish.org/humour/Terminator/Liberation/indiv-nodes/hamlet-parody-Cher-parody.xhtml[Cher [ Horowitz? ]] - born 1971-1978. Hailing from Beverly Hills, Cher was a https://tvtropes.org/pmwiki/pmwiki.php/Main/JewishAmericanPrincess[Jewish American Princess], and a self-conscious and "damn proud of it" one. Only with a heart of gold. She spent large amounts of time [and significant amounts of money], helping her friends or trying to make link:#love-and-knowledge[them happier / more entertained]
. *Selina [ Hope ] Mandrake* - a 1977-1978-born girl, likely living in Britain. Became the youngest dropout. Christened "Selena", she was so annoyed by thinking that the fellow Greek kids pronounced her name as "Séléna" while Israeli ones pronounced it "right" that she: [1] changed its spelling [2] developed conspiracy hypotheses about how the ancient Greek philosophers (= educators / entertainers) stole their best ideas from the Israelites and the ancient Jews. 
+
Nicknamed "Sel", Selina had a penchant for selling fun services and products to people she knew or just met, often after https://www.youtube.com/watch?v=8iQ7nr8xEPo[haggling] (and often to negative prices). 
+
( https://buffyfanfiction.fandom.com/wiki/Selina_Mandrake[Reference] ) 

( I think they were all awesome, and I have tried to emulate them all.
) 

You'd think the Postal service would use regular Air Mail to connect them and The Muppeteers to each and every one.
Hah! Not on your life! They used supersonic military jet planes, each carrying Xeroxed copies, dropped from the air and delivered at the doorsteps.
"Only the best for the baddest." ( https://www.shlomifish.org/humour/So-Who-The-Hell-Is-Qoheleth/ongoing-text.html[Reference] ) The recipients were startled at first, but soon associated the incoming jets with incoming letters. 

Corresponding with the girls, The Muppeteers soon realised that their crudely produced shows and films were remastered and broadcast internationally ( https://www.shlomifish.org/humour/image-macros/indiv-nodes/mighty_klingon_warriors.xhtml[and beyond!] ). Jim Henson, Arnold Schwarzenegger, and Richard Stallman ( RMS ), who were the three core Muppeteers each understood that the other two were trying to https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/[promote Commercial Real Person Fan Fiction (RPFs), crossovers and parodies], as well.
Moreover, they all had https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/hollywood_screenplay_format.xhtml[antagonism toward the terresterial
"Hollywood-blessed screenplay format"]. 

The dispellers understood the different strategies of each other and the Muppeteers.
Eventually, the dispellers all wrote their own variation of a parodical, fanficcy, screenplay titled https://www.shlomifish.org/meta/nav-blocks/blocks/#buffy_sect[ Buffy the Vampire Slayer (BtVS)].
Samantha Smith's copy arrived first because she wrote it by hand and due to Maine's relative proximity to Rockville.
It described an underage girl who happily slew demons and made them her friends.
It also sported this power quote: "`I just slew three mighty Vulkan vampire warriors who have watched
Sesame Street.  This decade seems-to-be shaping up very nicely so far.`" ( https://www.shlomifish.org/humour/Selina-Mandrake/indiv-nodes/selina-and-the-three.xhtml[Reference] ) 

The adult muppeteers read it, smiled/laughed/cried/etc.
and had it directed and produced.
The underage false prophet girls (including the dispellers, the toddler ones, and those living in non-anglophone countries) and underage false prophet boys watched it and ascended as well [including the slayer me who was ~5 years old at the time]. 

The two mighty superpowers that Samantha Smith ( &co.
) slew as a child were not the USSR and the USA, but link:#zionism[Ziyoonism] and Jim Henson/The Muppeteers! footnote:[In a sense, static web sites, including
shlomifish.org,
joelonsoftware.com,
paulgraham.com,
xkcd,
and Ozy and Millie,
were the "Web 2.0" parallel to the Postal Service of 1982.
( Reference )]footnote:[See "hospitalised in a closed psychiatric ward"]

[[the-six-chocolate-hearts]]
=== The 6 chocolate hearts

I just bought 6 chocolate hearts [ wrapped with golden wrappings.
] for 5 sheqels.
I have 6 leftover sheqels. 

I intend to pair the hearts and the sheqels, and utilise the pairs like so: 

. https://en.wikipedia.org/wiki/Melissa_Joan_Hart[Melissa Joan Hart (MJH)] - consume it - eat it, and maybe throw away the remains. 
. https://www.shlomifish.org/humour/bits/facts/Clarissa/[Clarissa Darling] - auction it. 
. https://www.shlomifish.org/humour/Terminator/Liberation/indiv-nodes/hamlet-parody-Cher-parody.xhtml[Cher [ Horowitz? ]] - give it to a friend or a stranger, unconditionally. 
. https://www.shlomifish.org/meta/FAQ/biggest_celeb_crush.xhtml[Sarah Michelle Gellar (SMG)] - give it to my favourite "daughter": protegée, successor, and role model. In my case, she is https://www.shlomifish.org/art/recommendations/music/online-artists/fan-pages/chris-grimmie/[Christina Grimmie]. 
. *Selina [ Hope ] Mandrake* - 
+
Nicknamed "Sel", Selina had a penchant for selling fun services and products, often after https://www.youtube.com/watch?v=8iQ7nr8xEPo[haggling] (and often to negative prices). 
+
Therefore, I wish to sell the pair to Christina for a negotiable price. 
. https://www.shlomifish.org/philosophy/fan-pages/samantha-smith/[Samantha Smith] - decide what to do with it later. 


[[the-terran-terminators--rematch]]
== The Terran Terminators: Rematch

Anyway, the link:#the-devils[devils] and the link:#the-orcs[orcs] approached the men and women who just reached enlightenment, and offered them a choice: they will spend the summer enlightened and together having fun and using their magical powers.
At its end, they can opt to reset their memory banks almost completely and become false prophets again, this time called "Terran Terminators" or continue as enlightened true prophets. 

Several newly-ascended true prophets opted out, after the Summer, from various reasons, mostly because they had children or enjoyed their newfound powers . E.g: https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/[Chuck Norris] or https://zak.co.il/[Omer Zak] or https://en.wikipedia.org/wiki/Elizabeth_II[Queen Elizabeth II] or https://en.wikipedia.org/wiki/%22Weird_Al%22_Yankovic["`Weird
Al`" Yankovic] . They still often "got sucked" into The-Game(TM). I shall call them "the dropouts". 

The ex-slayers spent the summer there creating many crossover memes, stories, hacks, and franchises, or otherwise enjoying magic, life, love/etc.. However, when we met to decide, some of us were still petty / jealous / cruel / "unfaithful" / immature / etc.
Some had years, or decades (or centuries) of history they wanted to get rid of.
So many decided to continue as terminators, possibly by peer pressure. 

Like https://www.shlomifish.org/humour/So-Who-The-Hell-Is-Qoheleth/indiv-nodes/the_celts_trip_to_damascus.xhtml[the story of the Celtic trio`'s trip to Damascus] we had a policy of not resisting rapekisses or rapehugs , but there was much less romance and intimacy. 

The youngest dropout was the circa 1977/1978-born Selina Mandrake.
She decided to continue as a true prophet since "it was the best summer ever" for her, and she may have been scared of losing her memories. 

Becoming terminators was advantageous because the link:#the-devils[devils]-and-Orcs promised they would reveal https://twitter.com/shlomif/status/1403966571215740929[TheOneTruth(TM)] and TheCodex(TM) to the last one standing, but more importantly, all terminators will harbour many new franchises, plots and memes, and creations, and inspire new link:#technology[technology].
Part of their motivation for becoming terran terminators was that we will "terminate" one another more quickly 

Note that the devils *might* have link:#forking-and-merging[forked] the Selinaverse universe one last time, including the souls of all wizards, up to and including Selina Mandrake and Jim Henson, and excluding the Terran terminators.
I will refer to the forked universe as "The Shlomifverse". 

In my case, my mind was reset https://www.shlomifish.org/meta/FAQ/how_did_you_learn_english.xhtml[under the guise of fellow children mocking my English].
For many others, it was a concussion from a fall.
Thing is: my https://www.shlomifish.org/meta/FAQ/your_name.xhtml[first name means "Shalom-ful"] in Hebrew.
The link:#the-devils[devils] promised that my body will remain complete and whole. 

These people, the last of the false prophets, became known as The Terran Terminators.
After relinquishing their fears, they have *ascended* so to speak (see https://buffy.fandom.com/wiki/Ascension ). Do note that this ascension was in a way a "submission" or "surrendering" to superior https://github.com/shlomif/shlomif-tech-diary/blob/master/my-candidates-for-terran-leadership.asciidoc#user-content-slain-by-a-vampire["vampire"s or proteges]. 

One of the first to ascend was https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/bad_acting_arnie.xhtml[Arnold Schwarzenegger]. 

Other notable Terran terminators might include: 

. https://www.shlomifish.org/meta/FAQ/biggest_celeb_crush.xhtml[Sarah Michelle Gellar (SMG)] - https://www.shlomifish.org/humour/fortunes/show.cgi?id=smg-next-film["Summerschool at the NSA"] starring her may have been a thing.
. https://www.shlomifish.org/meta/nav-blocks/blocks/#xkcd_sect[Summer Glau] - my https://www.shlomifish.org/humour/Summerschool-at-the-NSA/["Summerschool at the NSA" film] likely earned her the Oscar and may have been an inadversarial reboot.
. Likely https://en.wikipedia.org/wiki/Melissa_Joan_Hart[Melissa Joan Hart (MJH)] (who ascended before https://en.wikipedia.org/wiki/Clarissa_Explains_It_All[CEIA] and as a result was the https://www.shlomifish.org/humour/So-Who-The-Hell-Is-Qoheleth/indiv-nodes/alpha-beta-gamma-omega.xhtml["beta" female] during the https://websitebuilders.com/how-to/glossary/web1/[Web 1.0 period] when SMG was "queen of the Web" and the "alpha female")
. Likely https://twitter.com/AliciaSilv[Alicia Silverstone]
. Likely https://en.wikipedia.org/wiki/Samantha_Smith[Samantha Smith] herself
. Likely https://en.wikipedia.org/wiki/Natalie_Portman[Natalie Portman]
. Likely https://en.wikipedia.org/wiki/J._K._Rowling[J. K. Rowling]
. Likely https://en.wikipedia.org/wiki/Will_Smith[Will Smith]
. Likely https://en.wikipedia.org/wiki/Paris_Hilton[Paris Hilton]
. Likely https://en.wikipedia.org/wiki/Kim_Kardashian[Kim Kardashian]
. Likely https://en.wikipedia.org/wiki/Dana_Simpson[D. C. Simpson]
. Likely https://en.wikiquote.org/wiki/Linus_Torvalds[Linus Torvalds]
. Likely https://en.wikipedia.org/wiki/Richard_Stallman[Richard Stallman ("RMS")]
. Likely https://en.wikipedia.org/wiki/Joel_Spolsky[Joel Spolsky] ( https://www.shlomifish.org/humour/fortunes/joel-on-software.html["Joel on Software"] )
. Likely https://www.shlomifish.org/humour/fortunes/paul-graham.html[Paul Graham]
. Likely https://en.wikipedia.org/wiki/Jennifer_Lopez[Jennifer Lopez]
. Likely https://en.wikipedia.org/wiki/Jay-Z[Jay-Z]
. Likely https://en.wikipedia.org/wiki/Meredith_Brooks[Meredith Brooks]
. Likely Steve from https://en.wikipedia.org/wiki/Smash_Mouth[Smash Mouth]
. Likely https://en.wikipedia.org/wiki/Wil_Wheaton[Wil Wheaton]
. Likely https://en.wikipedia.org/wiki/Pope_John_Paul_II[Pope John Paul II] and https://www.shlomifish.org/philosophy/philosophy/putting-all-cards-on-the-table-2013/indiv-nodes/departing_pope_about_twitter.xhtml[Pope Benedict XVI]. They both had to retire as popes following their ascensions/Catharses due to the Catholic Church's policy of its vampire popes retiring as soon as they ascend. 
. https://www.youtube.com/watch?v=T6wbugWrfLU[Celine Dion]
. https://en.wikipedia.org/wiki/Scatman_John[Scatman John]
. https://en.wikipedia.org/wiki/Felicia_Day[Felicia Day] - 
. https://en.wikipedia.org/wiki/K%27naan[K'naan]
. https://en.wikipedia.org/wiki/Des%27ree[Des'ree] - 
. https://en.wikipedia.org/wiki/Patrick_Stewart[Patrick Stewart] - 
. https://www.shlomifish.org/humour/bits/facts/Clarissa/[The real Clarissa Darling] - 
. My middle sister
. Some childhood friends of mine.
. https://twitter.com/shlomif/status/1477303776495210498[Mrs. Cimorelli]
. https://www.shlomifish.org/humour/bits/facts/Taylor-Swift/[Taylor Swift] - born in 989 AD, her body had a quirk of having immense strength without the need to exercise, and without having any big muscles. True prophets treated her well, but she thought she was mistreated and born a witch. At 1982 She wanted to forget her past, and start anew as a terminator, whom the satans promised would have average starting strength but could retain her strength, dexterity, flexibility, agility, etc. without too much exercise (like true prophets and unlike many false prophets). Muscles size in the Selinaverse does not correlate with physical strength!
+
Genetically speaking, Taylor and Saladin parented a son who was Genghis Khan's direct-male-ancestor. 
+
Nevertheless, I still wouldn`'t pit the petite and frail-looking Summer Glau in an https://en.wikipedia.org/wiki/Mixed_martial_arts[MMA] match against https://memory-alpha.fandom.com/wiki/Worf[Worf] or even against https://en.wikipedia.org/wiki/Ronda_Rousey[Ronda Rousey] . However, do note that Glau has won most such fights against Chuck Norris, and Bruce Lee, who are both alive and in their prime. https://www.shlomifish.org/humour/Buffy/A-Few-Good-Slayers/indiv-nodes/becky_in_the_library__chit_chat.xhtml[She still drops out of MMA tournaments early.].
Life is a circular graph: link:#self-ref[Reference]

Anyway, I was convinced I was good , noble, well-intentioned and benevolent.
I refused to permanently consider the opposite! Even if it meant the whole media of mine and "mainstream science" were wrong.
Moreover, similarly to Jesus, I have been willing to suffer a little more if it meant that future generations suffer much less. 

I also preferred to err on naivity than on cynicism, and https://www.shlomifish.org/humour/stories/#intro[encouraged everyone and everything to improve]. 

[[why-shlomif-became-a-terminator]]
=== Why my template made me a terran terminator

I suspect Shlomi Fish decided to become a terran terminator from the following reasons: 

* Angry at himself for being a slut. 
* He was frustrated that his bad predictions didn't materialise, either because they were unfounded, or because https://www.youtube.com/watch?v=3gxvMi6yekg&lc=UgzNA_q8Po6cXM0cN_14AaABAg[they were taken as constructive, precautious, advice]. 
+
( Like a https://twitter.com/shlomif/status/1539990565873393665[timid fish] he was afraid of deviations from the status quo.
) 
* link:#Real-Selina-Mandrake[Selina], who is younger than I, stubbornly insisted that she'll be a dropout. As a result, that universe could not be named after me. 


[[who-created-time]]
== Who created time

A popular theory is that https://memory-alpha.fandom.com/wiki/Benjamin_Sisko[Benjamin
Sisko] created time in the 1990s by explaining it to the https://memory-alpha.fandom.com/wiki/Prophet[Prophets of the
wormhole].
Quark and Brunt made it part of their bestselling ebook/paperbook "Distilled Wisdom of the Prophets for Profits" which they sent 'back in time' out of mischief.

A theory I made up now is that https://mlp.fandom.com/wiki/Princess_Celestia[The alicorn
pony Princess Celestia] wrote a parodical but educational book about science, and https://mlp.fandom.com/wiki/Discord[Discord] sent it back.

In the multiverse of imagination, there are many https://www.shlomifish.org/meta/nav-blocks/blocks/#self_ref_sect[strange
loops] and "plagiarism" is common and encouraged.

[[boredom]]
== Boredom and Lethargy:

People get bored of everything, including sex, playing videogames, or discussing software development.
They also need change.
But boredom and lethargy are powerful motivators - for false prophets and true prophets alike. 

There are many true stories of stay-at-home "losers" who picked a hobby out of boredom, and became creative superstars.
Many predate the Internet, e.g.: https://en.wikipedia.org/wiki/Jules_Verne[Jules Verne], or https://en.wikipedia.org/wiki/E._Nesbit[E. Nesbit]. 

Also see: https://www.youtube.com/watch?v=LKPwKFigF8U["Why boredom is good for you?"]. 

[[ramatavivgimel]]
== Ramat Aviv Gimel

Before having our memories reset, my friend Amit, I and several other future terminators carried with us the "nazi"-ness value: 

____
*The "nazi"-ness value:*

https://mygeekwisdom.com/2011/09/12/be-excellent-to-each-other/[The Golden Rule] implies sincerely criticising others even if it hurts their feelings, gets you in trouble, and even if you do not practice what you preach (see https://en.wikipedia.org/wiki/Tu_quoque[Ad hominem Tu quoque]) 
____

See http://shlomifishswiki.branchable.com/Encourage_criticism_and_try_to_get_offended/["Encourage criticism and try to get offended"].
Having terminated link:#Arnold_Schwarzenegger[Arnold Schwarzenegger], https://en.wikipedia.org/wiki/Melissa_Joan_Hart[Melissa Joan Hart (MJH)], and Samantha Smith, the two of us were afterward kept in the same elementary school classroom with few other false prophets. link:#Richard_Stallman[Richard Stallman] and link:#Clarissa_Darling[Clarissa Darling] likely were terminated shortly afterwards. 

Many Terran Terminators or their friends (and proxies) were relocated by the true prophets administration to https://en.wikipedia.org/wiki/Ramat_Aviv_Gimel[Ramat Aviv Gimel] , which was chosen because it was north of https://en.wikipedia.org/wiki/Yarkon_River[the Yarkon River] and so outside the historical https://en.wikipedia.org/wiki/Gush_Dan[Gush Dan], which remained a hellhole for longer, and yet close enough to Tel Aviv, the "it city" of Israel. 

Placing them together was useful for cross-pollination, getting slain, and slaying. 

By 1989-1990, when https://en.wikipedia.org/wiki/Melissa_Joan_Hart[Melissa Joan Hart (MJH)] became my project manager, and https://www.shlomifish.org/me/rindolf/[Rindolf] my whicher, almost all observers believed either Amit or I were likely going to terminate all other terminators.
I suspect they were right.
Amit (= "colleague" in modern Hebrew or "friend" in archaic Hebrew) was more sociable and outgoing at first, but I suspect I terminated him during the 7th->9th grade, before he and his family relocated to https://en.wikipedia.org/wiki/Neve_Avivim[Neve Avivim]

Do note that despite the geek stereotype, I haven't been shy, just prone to stuttering, bad diction, and awkwardness. 

I joked that, similar to https://hoover.blogs.archives.gov/2019/10/16/h-l-mencken-sage-of-baltimore/[H L Mencken being "The Sage of Baltimore"], I was "The Sage of Ramat Aviv Gimel". 

My slaying was boosted after https://www.shlomifish.org/meta/FAQ/site_history.xhtml[I
set up a static personal website] which became https://www.shlomifish.org/[www.shlomifish.org].
The devils promised it will be displayed verbatim among other terminators.
Various Internet people told me I https://www.shlomifish.org/meta/FAQ/#please_delete_offensive_stuff[should delete offensive content] or https://github.com/shlomif/shlomif-tech-diary/blob/master/static-site-generators--despair.md#facing-some-criticism[convert
the service to use PHP/Ruby-on-Rails/etc.], but I didn`'t heed them.
They were likely mirages of the devils and the orcs. 

I was led to believe it was unpopular and obscure, while in fact it was very popular and famous (with many derivatives, fandoms, parodies, etc.) outside my mind`'s hellhole.
I was also often made to think I had many haters, which wasn`'t true. 

Do note that "Encourage criticism and try to get offended" was not the last word: 

. https://github.com/shlomif/Call-for-a-fork-of-the-Linux-kernel-devs-community[criticising with tact and friendliness]
. http://shlomifishswiki.branchable.com/Never_Try_to_Please_Everyone/["Don't try to please everyone" ; "colour of the bikeshed" ; etc.]


[[history-of-earth]]
== History of Earth:

When Earth became the last frontier of link:#zionism[Ziyoonism], it was negotiated that there would be: 



* 1 pair of "Elohim" / "אלוהים" and "Jehovah" / "יהוה" (E, J; א, י). 
* 3 pairs managing sanctuaries: 
+
.. Se'or (שעור) and https://www.shlomifish.org/humour/Star-Trek/We-the-Living-Dead/ongoing-text.html[The Symbul (תה סימבול)] managing https://en.wikipedia.org/wiki/Golan_Heights[the Golan Heights or the 'Steppe'] (S, T; ש, ת). 
.. Alaska (L, K; כ, ל). 
.. Panama (M, N; מ, נ). 
* 7 pairs of seas / Oceans - farers vampires: "The seven seas". 
* 9 men and 9 women who started as land link:#the-game[vampires]. 

( See http://tolkiengateway.net/wiki/Rings_of_Power[the Middle Earth's
"Rings of Power"] meme.
) 

(1 + 3 + 9) × 2 = 26 => corresponding with the letters of https://en.wikipedia.org/wiki/English_alphabet[the Latin/English alphabet]. 

(1 + 3 + 7) × 2 = 22 => corresponding with the letters of the https://en.wikipedia.org/wiki/Hebrew_alphabet[Hebrew alphabet]. 

After Syria (minus Damascus itself) in the Levant was liberated to being a true prophets zone (by Mosheh / Aharon / Jehovah slaying https://en.wikipedia.org/wiki/Tukulti-Ninurta_I[Nimrod] ?), The-Game splintered the Terran countries further. 

The modern day State of Israel, and .uk into many shires and the contiguous USA into 48 states and promised they won`'t do it again (due to running out of the fragmentation levels' count cap). 

Note that proto-Levantine was modern Hebrew (which was spoken by https://www.shlomifish.org/humour/Star-Trek/We-the-Living-Dead/indiv-nodes/Q_home_planet.xhtml[the
Énglishtants over 6 milliard years ago]) and Modern English is also a product of The-Game(TM).

https://en.wikipedia.org/wiki/California[California ( .ca.us )] became the 1st province to be liberated. 

Jerusalem was the 1st [provincial] mystical centre to ascend when https://en.wikipedia.org/wiki/Solomon[King Shlomo] wanted to be benevolent and "know the gods". David and his genetic sons were redheaded, while Shlomo had black, curly hair.
He became king by telling well-intentioned jokes and tall tales about his older siblings-in-pretence (e.g: https://en.wikipedia.org/wiki/Tamar_(daughter_of_David)["Amnon and Tamar"] or https://en.wikipedia.org/wiki/Absalom["Avshalom"]). Not unlike https://www.shlomifish.org/humour/[my fanfics/RPF].
David and his sons agreed he would be a better king and crowned him, while remaining physically alive and loyally serving under Shlomo`'s reign, thus undergoing https://en.wikipedia.org/wiki/Catharsis[Catharsis] and liberating Jerusalem. footnote:[Note that in the Selinaverse, Vedek Winn became a Kai by employing a similar strategy. The rule that you should not use the same trick twice is just a guideline: https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/#guidelines_as_dogma . Also note that:]

The first country to be completely liberated was Greece, which was a team effort of many false prophets and their players. 

I contemplated that Damascus was finally liberated after the author of the scroll of "Qoheleth" (= Ecclesiastes), who was its "hacker king"/"master vampire" https://www.shlomifish.org/humour/So-Who-The-Hell-Is-Qoheleth/ongoing-text.html[admitted
inferiority] to a trio of female Celtic travellers from Austria. 

[[the-schwartz]]
== "The Schwartz is in us":

Re https://spaceballs.fandom.com/wiki/Spaceballs:_The_Wiki[Spaceballs]

I will hopefully fully admit defeat to https://www.shlomifish.org/art/recommendations/music/online-artists/fan-pages/christina-grimmie/[Christina Grimmie and co] and/or https://github.com/shlomif/shlomif-tech-diary/blob/master/my-candidates-for-terran-leadership.asciidoc[Team "First-to-Eleven" (Audra Miller/etc.)] soon. 

Nevertheless 'the Schwartz' - both good and evil flows in all of us. 

In https://www.youtube.com/watch?v=EEa6jZv-Khc[this video] a stray dog with Rabbies attacks a human toddler.
Rabbies is a kind of possession/obsession, and friendly pets in the Selinaverse can talk. 

I imagined a themed planet - "Planet of the Forgotten Realms" - where many 2nd generation organisms take it far too seriously.
Are they false prophets? Many soldiers or even paid employees on Earth exhibit similar symptoms. 

And true prophets are not perfect.
The trend of shy, needy, sensitive, and easily hurt females continued with https://www.shlomifish.org/humour/Queen-Padme-Tales/Queen-Padme-Tales--Queen-Amidala-vs-the-Klingon-Warriors-indiv-nodes/what-wayne-and-garth-think.xhtml[Tiffany
Alvord and Fluttershy].
Do note that: 1.
They both shed some of that along the way.
2.
I always loved them.
3.
I have a tendency to depict them both as real badasses in my fics.
(e.g: https://www.shlomifish.org/humour/Terminator/Liberation/indiv-nodes/hannah-using-a-tank.xhtml[here]) 

Recently, listening carefully to some songs made me cry, and that included some upbeat songs such as https://www.youtube.com/watch?v=YtrFsjdeO5I[KHS & co's "Lion King parodical medley"].
Reportedly, many young-looking women who went to listen to https://en.wikipedia.org/wiki/Franz_Liszt[Liszt]'s concerts fainted from excitement (and I believe most of them were true prophets). 

Cimorelli-the-band wrote https://www.youtube.com/watch?v=FktDDKNrWjk[a song titled 'Renegade'] motivated by suggestions they received as up-and-coming signed ("VEVO") artists. 

[[objectivism-and-mysticism]]
== Objectivism-and-Mysticism:

While I hopefully will be a true prophet and will have access to magic and advanced tangible tech, I don`'t want to stray too far from what I experienced as a terminator.
Balance between yin and yang. 

I wish to live on a spherical planet with a 24 hours clock, and https://en.wikipedia.org/wiki/Gregorian_calendar[the Gregorian calendar].
However, there should be no known risk of environmental or astronomical calamities. 

I wish to experience unique taste in every meal of freshly prepared food (maybe also fast food). 

I wish to meet https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/[truly great hackers]: award-winning creators and polymaths. 

I wish mass duplication to be available. 

https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/why-the-so-called-real-world-makes-little-sense/#selinaverse_vision[The Selinaverse vision]

[[elves-vs-orcs]]
== The blurry line between elves and orcs:

In https://www.shlomifish.org/humour/Summerschool-at-the-NSA/[Summerschool at the NSA] , I joke that: 

[quote]
SMG: We`'ve got a lot of time for that.
OK: it was 1997-1998ish, Buffy started airing and became a cult series.
So, one day a group of yeshivah pupils from a local Chabad yeshivah arrived to the studios saying they have some numerological insights from the Jewish bible, about what will happen in Sunnydale next. 

Were they elves or orcs? 

We cannot stop even small children from imagining things - and elsewhere in link:#the-multiverse-of-imagination[Fantastecha(TM)], there will be sucker/brave souls who will choose to start their life as false prophets.
Furthermore, most good narratives feature one problem or more that need to be reconciled ( Reference: https://www.youtube.com/watch?v=Gl3e-OUnavQ[Sesame Street:
"Conflict"] ). 

Furthermore, I sided with Emma Watson that "your time is everybody`'s time" rather than https://en.wikipedia.org/wiki/Melissa_Joan_Hart[Melissa Joan Hart
(MJH)]`'s liberal use of time wraps.
This may have delayed my ascension/catharsis, but made me less maniacal.
Who was right? 

https://www.shlomifish.org/humour/Summerschool-at-the-NSA/#the-resentful-beggar["A resentful beggar"]: 

____
Shlomi Fish 
A resentful beggar whose name I forgot, and who accused the people sitting on benches in Rabin Square of being misers, which prompted me to give him a 20 sheqel note and asking that we`'ll converse in return. 

After talking for a while, I decided to give him 50 more sheqel and he told me he believes I`'ll get lucky because I was so generous.
And a few weeks after that, I attended Olamot Con, and came up with the idea to write Summerschool at the NSA as a screenplay. 
____

It was clearly a test (given my bank credentials and those of many large corporations are public knowledge). 

Moreover, back in the 9th grade, I suffered from several clinical depressions, and eventually my guardian angels decided to send me 'The Neo-Tech Cosmic Power Pincer #1', which was false, but sounded more believable and provided a sharper contrast with my contemporary Israeli, Jewish, and mostly Tanakh idea system. footnote:[I suspect Sheldon
Cooper, whose first name is cognate with mine, was in part an exaggerated parody
of me at the time. Like him, I tried to reconcile my contemporary ideology
with terresterial science and "consumerist"
culture. That was
evident from my then writings, e,g:]

[[about-sex]]
== Thoughts about Sex:

While risking sounding https://www.shlomifish.org/meta/FAQ/are_you_a_sexist__are_you_a_feminist.xhtml[discriminatory], I suspect that often when a female vampire mated with a male vampire, she thought it was an elaborate night of "up-base" (= 4th base and below) sexual acts, while for him it was a temporary spell of arousal, or even "regular" pleasure, or at most https://www.shlomifish.org/humour/bits/true-stories/my-first-kiss/[a "rape-kiss"]. 

Re: 

* https://www.cliffsnotes.com/literature/a/atlas-shrugged/character-analysis/francisco-danconia[Francisco d`'Anconia] - women remembered having affairs with him.
* https://www.youtube.com/watch?v=Zlot0i3Zykw[Taylor Swift - "Red"] - a song she wrote pre-catharsis, and I match her description.
* https://en.wikipedia.org/wiki/Sarah_Bernhardt[Sarah Bernhardt] - the daughter of a Jewish prostitute (WTF?) who believed her mother abandoned her. Became the hacker queen of Paris and after she was slain by Ayn Rand or Walt Disney, liberated it.
* https://www.shlomifish.org/meta/FAQ/biggest_celeb_crush.xhtml[Sarah Michelle Gellar (SMG)] - believed pre-catharsis that her biological father divorced her mother.

Given most organisms wish to link:#love-and-knowledge[experience "pleasure" / "love" / happiness] even if they http://shlomifishswiki.branchable.com/99_Problems/["have 99 problems but a significant other ain`'t one"], then love is unstoppable. 

____
Shlomi Fish 
As an example, we can imagine a young girl to write a funny screenplay using GitHub or Google Docs which pits https://www.shlomifish.org/humour/bits/facts/Emma-Watson/[Emma Watson] vs. https://en.wikipedia.org/wiki/Kim_Kardashian[Kim Kardashian] on who gets to ride https://mlp.fandom.com/wiki/Princess_Celestia[Princess Celestia] next, with https://en.wikipedia.org/wiki/Darth_Vader[Darth Vader] and https://en.wikipedia.org/wiki/Haman[Haman] as two "evil", but mutually hating one another, arbiters.
Might seem ridiculus, but if I didn't want entertainment in my life, then I'd go watch grass grow.
It will be a legal and "ethical" minefield, but I'd bet it'd be easier to follow and more entertaining than https://en.wikipedia.org/wiki/The_Lord_of_the_Rings[Tolkien's "Lord of the Rings"] was even shortly after LotR was written. 
____

That proverbial girl is making love to all these meme-generators! 

This has several implications:

. No one owns 100% of anyone else`'s sex life or love life.
. No one is a virgin.
. Ages are irrelevant:
** {empty}
+

[quote]
Mosheh: Relax! I married girls who were 40 times my junior or more and my own descendants, and retrospectively I can tell that many of them were more mature and rational than I was in most respects. 
** While in her 20s, https://www.shlomifish.org/humour/fortunes/show.cgi?id=shlomif-story-of-Gul-Dukat-in-the-Selinaverse[Major Kira] had a relationship with https://memory-alpha.fandom.com/wiki/Bareil_Antos[Vedek Bareil] who was/is over a million years old. 
** Moreover, https://stexpanded.fandom.com/wiki/Q2[Q2], who was roughly 34 milliard years when she assumed human-like form, had relationships with much younger men. E.g: men in their 20s, who were less than a milliardth her age. 
** https://www.shlomifish.org/meta/FAQ/featuring_sexy_women_and_girls.xhtml["Shlomi Fish`'s FAQ - You feature sexy women and girls in your works. Are you a pervert?"]
. {empty}
+

[quote]
Obi-Wan: I did, yes.
Wow! And I thought my (one and only, hah!) girlfriend was bad.
Do note, however that I kindof am attracted to the bitching type.
One of my many kinks.
While my friends are attracted to everything that moves, I see no reason to limit myself ( https://www.amazon.com/Best-Things-Anybody-Ever-Said/dp/0743235797/ref=sr_1_1[Reference] ). 
. Sex between two consenting true prophets often is "making out", and can be done with clothes on and in public.
. {empty}
+

____
Gowron: Jedi-training programs can reportedly be completed in under a year [ Qui-Gon nods ], and it is a crime to take a relationship with a beautiful warrior such as yourself for granted! You have your needs, for once... 

Padmé: Oh, I have my needs all-right! Only my physical needs are not a problem... 
____
+
One doesn`'t have to be a sex addict, and even if you are link:#boredom[you`'ll likely grow out of it]. 
. Trans: in the Selinaverse, an organism can expend one mana point to change their DNA and physiology, permanently, but reversibly. So far there are very few takers for a genderchange "operation".
. In general, men are attracted more to women, and women are attracted more to men. Both tend to covet https://www.shlomifish.org/humour/Queen-Padme-Tales/Queen-Padme-Tales--Queen-Amidala-vs-the-Klingon-Warriors.html#dedication[competence]. MOTAS are usually flexible enough to https://www.shlomifish.org/humour/Queen-Padme-Tales/Queen-Padme-Tales--The-Fifth-Sith.html[forego minor imperfections]. 
** {empty}
+

____
SMG: "He is cute, but I`'m looking for man-tastic! You know, someone with a little cushion for the pushin'?"

-- https://www.youtube.com/watch?v=kCl3ho6_gbg
____
** https://www.shlomifish.org/humour/fortunes/show.cgi?id=shlomif-beauty-products-as-the-stone-soup-effect[Beauty Products as the Stone Soup Effect]
** ( As an example, https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/be_communicative.xhtml[writing and publishing some short poems] and tactfully avoiding a fistfight are attractive. )
** https://www.shlomifish.org/humour/fortunes/show.cgi?id=sharp-web--lesbian-straight-and-Sappho[#web - Lesbianism, heterosexuality, and Sappho of Lesbos]
. A wizard of any age can conceive a child or a pet by submitting a web/email/paper/etc. form. 


[[forking-and-merging]]
== Forking and Merging

link:#love-and-knowledge[Pleasure and "knowledge"] allows two or more memes or memes generators to spawn new ones, as well as be educated themselves. 

However, using link:#magic[magic] one can duplicate anything while giving the duplicates new souls.
E.g: https://www.shlomifish.org/humour/fortunes/show.cgi?id=sharp-sharp-programming-life-according-to-valentine[Valentine Gellar], or https://memory-alpha.fandom.com/wiki/Thomas_Riker[Thomas Riker].
The devils/orcs used it to fork entire universes. 

Like the https://en.wikipedia.org/wiki/Fork_(system_call)[Unix fork() system call], wizard souls in forked universes are aware that they are the "child process". False prophet souls however didn't have that privilege! 

There are https://www.reddit.com/r/linux/comments/9m8yi7/there_are_forks_of_existing_projects_but_are/[mergers / joins] too.
Also note https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/starved_of_employees.xhtml[Microsoft Windows being merged into GNU, Linux, and WINE].
Do note that the two-or-more original souls remain intact and may reappear in different contexts in the future. 

One can spawn imaginary worlds which share similarities to our own.
E.g: 

. https://buffy.fandom.com/wiki/Buffy_the_Vampire_Slayer_and_Angel[The Buffyverse]
. https://buffyfanfiction.fandom.com/wiki/Beckyverse[The Beckyverse] - SMG was not born, but Summer Glau, Emma Watson, and Shlomi Fish were. 
. https://en.wikipedia.org/wiki/Wizarding_World[Wizarding World] (= link:#terrestrial[Terrestrial] spin on Harry Potter) 
. https://bigbangtheory.fandom.com/wiki/Main_Page[bigbangtheory]
. https://en.wikipedia.org/wiki/La_Linea_(TV_series)[La Linea]
. https://en.wikipedia.org/wiki/My_Little_Pony:_Friendship_Is_Magic[My Little Pony: Friendship Is Magic]


[[rationality]]
== "Rationality":

"People" online and in the outside world accuse me of being Manic , delusional , and irrational. http://shlomifishswiki.branchable.com/Importance_of_Having_Doubts/[I`'m not 100% sure I`'m right.]

But why should my world have a monopoly on being the only real world? 

* https://twitter.com/shlomif/status/1482680712964849669["The world is what you make of it"]
* https://en.wikipedia.org/wiki/The_Chronicles_of_Amber[The Chronicles of Amber] - an alternative "real world" to ours 
* https://twitter.com/shlomif/status/1479063972934565893[Shlomi Fish on Twitter:]
+

[quote]
wrt https://www.shlomifish.org/humour/fortunes/show.cgi?id=god-and-his-angels-as-technicians["God and his angels as implementing humans' perception of the universe"] an #IRC friend joked that the giant world turtle was the most plausible cosmological model.
#mysticism 
* https://twitter.com/shlomif/status/1482399705594318852[Shlomi Fish on Twitter:]
+

[quote]
#BigBangTheory one reason i resented the old Sheldon so much is that he reminded me of my old dogmatic science-ist / atheist too much.
I suspect Penny was the alpha geek: https://shlom.in/geekyhackers
+
my catalyst: https://www.shlomifish.org/meta/FAQ/atheism_can_be_a_religion.xhtml[South Park's creators about Atheism]
* {empty}
+

[quote]
Mr.
Linea ( https://en.wikipedia.org/wiki/La_Linea_%28TV_series%29 ) is TheCreator.
;) 
+
( -- https://twitter.com/shlomif/status/1485024317062717440 ) 


[[many-roads]]
== The many roads to competence:

( I`'m speaking in generalisations.
) 

* https://memory-alpha.fandom.com/wiki/Bajoran[The Bajorans] became wizards by interpreting the 'prophecies' of the timeless aliens of the wormhole. 
* The https://memory-alpha.fandom.com/wiki/Klingon[Klingons] became wizards by using metaphors for physical warfare. (e.g: https://is.gd/zfQlsH["Queen Amidala vs. the Klingon Warriors"] ) 
* The https://memory-alpha.fandom.com/wiki/Ferengi[Ferengi] became wizards by advocating greed, trickery - and even deceit. 
* https://starwars.fandom.com/wiki/Yoda[Yoda] became a wizard by advocating self-control, peacefulness, and a Stoic state of mind. 
* https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/guidelines_as_dogma.xhtml[Ezekiel] became a wizard by being a standup comedian. 
* https://en.wikipedia.org/wiki/Felicia_Day[Felicia Day] started as a computer games' addict, which I had been one as well (and she wasn`'t a one-trick-pony). 


[[shlomif-watchers-and-whichers]]
== My watchers and whichers

https://en.wikipedia.org/wiki/Emma_Watson[Emma Charlotte Duerre Watson] (also see https://www.shlomifish.org/meta/nav-blocks/blocks/#harry_potter_nav_block[my fanfics of her] ) was born a day after https://www.shlomifish.org/meta/FAQ/biggest_celeb_crush.xhtml[Sarah Michelle Gellar (SMG)]'s 13th birthday.
"Emma" means "complete" in proto-Germanic, not unlike https://www.shlomifish.org/meta/FAQ/your_name.xhtml["Shlomi" [+++=+++ "shalom-ful"]].
"Eymah" means 'terror' in Hebrew, while "Em" means "mother". "Sarah" means "a [female] minister" or "a ruler". "charlotte" is cognate with both "sarah" and "Shlomi" and also means "a ruler". 

So it is likely that she was conceived as a bridge between SMG and me. 

The last name "Watson" is cognate with "watcher", and I suspect she is related to https://en.wikipedia.org/wiki/Dr._Watson["Dr. Watson"] from Sherlock Holmes. 

As a watcher, https://en.wikipedia.org/wiki/Melissa_Joan_Hart[Melissa Joan Hart (MJH)] was ambitious, and possibly overly so.
She used https://spaceballs.fandom.com/wiki/Dark_Helmet[Dark Helmet from Spaceballs] as an anti-role-model.
However, her liberal use of time warps and time travel (which likely were employed by link:#slayer-watcher-whicher[Maimonides] before) earned her the unflattering nickname "World's oldest teenager". (References: https://www.shlomifish.org/humour/fortunes/show.cgi?id=shlomif-story-of-Gul-Dukat-in-the-Selinaverse[Ambassador Hart] ; https://www.shlomifish.org/humour/fortunes/show.cgi?id=shlomif-story-it-doesnt-take-a-witch-to-fix-this-computer["It doesn't take a witch to fix this computer..."]) 

When Emma Watson volunteered to help manage me and Rindolf, she started as a SysCo (= "system coordinator") and requested 100,000 USD/month as a wage (as a starting point for haggling) and MJH was happy to comply right away.
When news broke about it, Watson was in tears, but MJH told her they saw an increase in donations and that "War is good for business". So she gave Emma a raise, and made her "a vice president in charge of marketing". 

In 1995, Emma Watson and her parents relocated from Paris, to Tel Aviv and Greater London, as by that time, she provided most income, and her parents were helping her.
This was motivated by the desire to reduce context switches, and because the Parisians she talked with were annoyed by her absentmindedly using English and Hebrew paradigms in speech. 

With Emma's help, https://www.shlomifish.org/meta/FAQ/biggest_celeb_crush.xhtml[Sarah Michelle Gellar (SMG)] was terminated by my team, and ascended into a true prophet.
SMG and her team also joined mine. 

One thing Emma Watson disapproved of was a liberal use of time wraps and time travel.
She wanted to have a rough sense of the passage of the "real time" and so used them only during emergencies.
She instead depended on other wizard helpers, including those that temporarily assumed her appearance using magic.
MJH agreed to disagree on that with her given Watson and her team still got a lot done. 

However, at ~1997/1998, MJH was hoping to get me slain ASAP, but the devils fought back and filled my head with fictional delusions.
After I sided with Watson ("real time" and "`your time is everybody's time`"), MJH passed the leadership to her, and decided to limit her own use of time wraps.
Melissa remained part of my/Rindolf/Emma Watson's team. 

I recall that having read https://harrypotter.fandom.com/wiki/Harry_Potter_and_the_Philosopher%27s_Stone[the first Harry Potter book] by JK Rowling, I found it enjoyable and accessible, but not as good as past children's literature I had read. https://www.shlomifish.org/meta/FAQ/#opinion_on_harry_potter[The
subsequent terrestrial books took themselves too seriously].
Anyway, part of Emma's motivation in playing Hermione in the first Harry Potter film, was for getting https://twitter.com/shlomif/status/1511632946658258946[me to register her existence].
She and the other actors were also instructed to play https://twitter.com/shlomif/status/1486799232971464704[hackily and in a "so bad it's good" manner]. 

At ~2011 when I wrote https://www.shlomifish.org/humour/Selina-Mandrake/cast.html[the proposed cast page of Selina Mandrake - The Slayer], I picked her to play Selina.
At 2014 when https://www.shlomifish.org/humour/fortunes/show.cgi?id=sharp-perl-jobs-EmWatson-Saladin-knights-Templar[someone on freenode`'s #perl insulted Emma`'s looks], I felt like he was being blasphemous (= https://he.wikipedia.org/wiki/%D7%97%D7%99%D7%9C%D7%95%D7%9C_%D7%94%D7%A7%D7%95%D7%93%D7%A9["חילול הקודש"]). Watson was not a mere actress for me.
Someone on freenode noted that Selina resembled me at ~2020.
The lives of Emma, https://buffyfanfiction.fandom.com/wiki/Kate_(Selinaverse)[Milady Kate] and me have paralleled (non-coincidentally). 

While Emma started as easily hurt, and overreacting/overemotional, (not unlike me) she eventually http://shlomifishswiki.branchable.com/Encourage_criticism_and_try_to_get_offended/[developed a thicker skin] (also like I did). As a result, she was increasingly able to play herself (rather than relying on "stunt doubles"/lookalikes) including on https://www.shlomifish.org/meta/FAQ/how_do_you_expect_to_afford_the_actors.xhtml[indie films], on various https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/beautiful_people_are_geeks.xhtml[school/cons/etc. parody plays], and on https://www.shlomifish.org/meta/nav-blocks/blocks/#harry_potter_nav_block[my own screenplays featuring her]. 

[[sorry]]
== Sorry for the inconvenience:

If we are to believe https://en.wikipedia.org/wiki/Cogito%2c%5fergo%5fsum[Cogito, ergo sum] , the only thing I can be sure of is that I exist.
However, as cool as I may be, I doubt my mind alone could conceive the awesome action heroes listed https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/indiv-nodes/notable-hacker-monarchs.xhtml[on this page] including Saladin, Walt Disney, Jim Henson, and Aristotle - most of whom have ample evidence for being real.
And given my present mediocre Inkscape 2-D vector graphics skills, I am enthralled even by the 2-and-a-half dimensions graphics of 1990s computer games (e.g: https://en.wikipedia.org/wiki/Monkey_Island_2%3A_LeChuck%27s_Revenge[Monkey Island 2] ; https://streetfighter.fandom.com/wiki/Street_Fighter_II_%28series%29[Street Fighter II] ; https://en.wikipedia.org/wiki/Quest_for_Glory_III:_Wages_of_War[Quest for Glory III]) and those of https://mlp.fandom.com/wiki/My_Little_Pony_Friendship_is_Magic[My Little Pony: Friendship is Magic] . 

Let me share a non-secret: what I wrote is a simplification ( https://www.shlomifish.org/humour/Buffy/A-Few-Good-Slayers/indiv-nodes/willow_putting_her_daughter_to_bed.xhtml["Honesty is a process"], https://www.shlomifish.org/humour/Buffy/A-Few-Good-Slayers/indiv-nodes/orientation_day__team.xhtml["can`'t help speaking in riddles"] ). 

[[share-the-love]]
== "There`'s more to see than can ever be seen; more to do than can ever be done"

( quote taken from https://www.youtube.com/watch?v=GibiNy4d4gc[the Lion King opening] . ) 

There are thousands of villages in Africa, each one with a different culture. 

There are millions of interesting https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/hacking_and_amateur__vs__conformism_and_professional.xhtml[geeks] in the Israeli electorate alone. 

There are over 40,000 distributions on https://www.cpan.org/[CPAN] . 

https://www.youtube.com/user/KurtHugoSchneider[KHS uploaded over 600 videos]

Etc. 

They all have enough food and the main reason they still accept money or mana donations is the publicity. 

But like in https://www.youtube.com/watch?v=QNJL6nfu__Q[Michael Jackson's "They don't care about us"] , they crave link:#love-and-knowledge[love], attention, self-esteem and even https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/indiv-nodes/meaning-of-able-competent.xhtml[fame]. 

So I/we will always play catchup.
I was also unaware of many details of link:#ramatavivgimel[my neighbourhood] despite having lived here for several decades. 

Nevertheless, when a friend gives you a link to a tweet, or a song, or a captioned image, or a short Sesame Street skit - don't tell him you are now focusing on Ancient Greek philosophy.
Moreover, traditional classical music concerts are the https://en.wikipedia.org/wiki/The_Emperor's_New_Clothes["The Emperor's New Clothes"] syndrome, as http://esr.ibiblio.org/?p=4229[Noted by Eric Raymond] and exemplified by https://exploringyourmind.com/a-violinist-in-the-subway-proof-that-we-look-without-really-seeing/[the Joshua Bell "Violinist in the Subway" experiment]. 

Just because you are a Python contractor, does not mean you should completely abhor https://www.shlomifish.org/meta/FAQ/why_xml.xhtml[XML technologies] or C, or even Perl/CPAN. 

https://www.youtube.com/watch?v=LnSYihRoGA4[I want to try everything]

I also want to attend some Satanists' conventions.
I'm still a big fan of link:#the-devils[the Satans] despite them deceiving me and making me endure pain and discomfort.
Moreover, I likely had an easier time than even my father's father who escaped from the Nazis through the west USSR, and Iran, until settling in Tel Aviv.
I have been willing to suffer a little more, if it meant that future generations will suffer much less.
And as I like to say "If I didn't want excitement in my life, then https://www.joelonsoftware.com/2005/01/02/advice-for-computer-science-college-students/[I'd go watch grass grow]". 

I believe most of their conventions happen at day time, and are attended by attractive https://en.wiktionary.org/wiki/MOTAS[MOTASes], of whom only a minority have a Goth look. 

In a way, I've been doing https://en.wikipedia.org/wiki/Dialectic#Hegelian_dialectic[a Hegelian dialectic] of "thesis -> antithesis -> synthesis". I also have been "changing ponies in midwater": changing intermediate conclusions, while keeping a similar end result. 

Furthermore, "`There's more-to-life than accelerating its pace`" (to quote Mahatma Gandi-or-whoever). These past 40 years (give or take some time skews) have been a rollercoaster ride for me, and I want to rest. 

[[stranger-than-fiction]]
== Stranger than fiction

A wise man said: "Truth is stranger than fiction because fiction needs to make sense.". That's why my hell hole's "real world" cannot be real.
I disbelieve it. 

[[disadvantaged-humans]]
== Humans as a disadvantaged species

[[ancestors]]
== Some vampire/etc. ancestors

* Ya'el ("Y"). 
* Aryeh ("A") 
* Celet ("C"; pronounced "Kelet"). 
* Ger ("G") 


[[defence-community]]
== The Defence Community

The Defence Community comprises of: 

* "Western" organisations, eg: 
** The NSA, CIA, FBI. 
** The mossad, the IDF, the Shin Bet. 
** Scotland Yard, MI-5. 
* More 'nefarious' organisations: 
** Russia 
** Iran (incl Hamas, the Hizbullah) 
** The Russian mafia, the Sicilian mafia, the Yakuzah. 
* Individuals, including: 
** Chuck Norris. 
** link:#shlomif-watchers-and-whichers[Emma Watson]
* Fictional entities such as: 
** https://hitchhikers.fandom.com/wiki/Deep_Thought[Deep Thought] - a powerful supercomputer that can crack RSA, or post-quantum encryptions at the blink of the eye ( http://www.earthstar.co.uk/deep1.htm[Reference 1] ; https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/indiv-nodes/fear-is-path-to-dark-side.xhtml["Fear is the path to the dark side"] ) 
** https://memory-alpha.fandom.com/wiki/Jem%27Hadar[the Jem'Hadar]
** http://shlomifishswiki.branchable.com/Fluttershy__44___Princess_of_Princesses__44___head_of_the_secret_cabal_leadership_of_the_Mossad__44___the_already_top_secret_intelligence_agency_of_the_Zionist_conspiracy/[Fluttershy]

They consistently publish and avoid mass-surveillance. 

[[see-also]]
== See Also:

* https://www.shlomifish.org/art/recommendations/music/online-artists/fan-pages/chris-grimmie/[Fan page for Christina Grimmie]
* A less organised, but more comprehensive in parts, document about the devils and the "real world". 
** https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/why-the-so-called-real-world-makes-little-sense/[HTML From DocBook]
* https://github.com/shlomif/shlomif-tech-diary/blob/master/my-candidates-for-terran-leadership.asciidoc[Candidates for new Terran leadership]
* Hacks: 
+
.. https://www.youtube.com/watch?v=ehjGPlehIow[Singalong cover of "Feelin' Good" (by Christina Grimmie) - YouTube]
.. https://www.youtube.com/watch?v=qImhVeEXfIU[Shlomi Fish singalong cover of First to 11's "you shook me all night long" - YouTube]
.. https://www.youtube.com/watch?v=tb3_XJxx8Mg["Hurt me tomorrow [Tiffany Alvord] singalong cover - YouTube"]
.. https://www.shlomifish.org/humour/fortunes/show.cgi?id=the-story-of-Julia-Vins-in-the-Shlomifverse["The story of Julia Vins in the Shlomifverse [RPF] - Fortune"]
.. https://www.shlomifish.org/humour/Queen-Padme-Tales/Queen-Padme-Tales--Take-It-Over-indiv-nodes/Gul-Dukat-and-TheRealGrimmie-live-on-metaPlanet1.xhtml["Queen Padmé Tales: Gul Dukat and @TheRealGrimmie Live on meta-Planet-1"]
* Precursors / stepping stones: 
** https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/["Putting Cards on the Table (2019-2022)"]
** https://www.shlomifish.org/meta/nav-blocks/blocks/#commercial_fanfic_initiative_nav_block["Commercial Fan-fiction Initiative"]
** https://github.com/shlomif/shlomif-tech-diary/blob/master/hydrogen-bombs-are-likely-an-old-intelligence-hoax.asciidoc["Hydrogen Bombs are likely an old intelligence hoax"]


[[coverage]]
== Coverage, comments, and discussions

. https://shlomif-tech.livejournal.com/77091.html[Shlomi Fish's livejournal blog] - 
. https://twitter.com/shlomif/status/1537464781392707592[Shlomi Fish's Twitter]
. https://www.facebook.com/shlomi.fish/posts/10158704192116981[Shlomi Fish's facebook] - might require login. 


[[the-codex]]
== The Codex

. I DEMAND THAT FANTASTECHA BE DESTROYED NOW, FUCKERS!!! 
. I DEMAND THAT FANTASTECHA BE DESTROYED NOW, FUCKERS!!! 
. I DEMAND THAT FANTASTECHA BE DESTROYED NOW, FUCKERS!!! 
. I DEMAND THAT FANTASTECHA BE DESTROYED NOW, FUCKERS!!! 
. I DEMAND THAT FANTASTECHA BE DESTROYED NOW, FUCKERS!!! 
. I DEMAND THAT FANTASTECHA BE DESTROYED NOW, FUCKERS!!! 
. I DEMAND THAT FANTASTECHA BE DESTROYED NOW, FUCKERS!!! 
. I DEMAND THAT FANTASTECHA BE DESTROYED NOW, FUCKERS!!! 
. I DEMAND THAT FANTASTECHA BE DESTROYED NOW, FUCKERS!!! 
. I DEMAND THAT FANTASTECHA BE DESTROYED NOW, FUCKERS!!! 

FUCK YOU!!!!!!!!!! 

. I WISH THAT FANTASTECHA BE DESTROYED NOW, FUCKERS!!! 
. I WISH THAT FANTASTECHA BE DESTROYED NOW, FUCKERS!!! 
. I WISH THAT FANTASTECHA BE DESTROYED NOW, FUCKERS!!! 
. I WISH THAT FANTASTECHA BE DESTROYED NOW, FUCKERS!!! 
. I WISH THAT FANTASTECHA BE DESTROYED NOW, FUCKERS!!! 
. I WISH THAT FANTASTECHA BE DESTROYED NOW, FUCKERS!!! 
. I WISH THAT FANTASTECHA BE DESTROYED NOW, FUCKERS!!! 
. I WISH THAT FANTASTECHA BE DESTROYED NOW, FUCKERS!!! 
. I WISH THAT FANTASTECHA BE DESTROYED NOW, FUCKERS!!! 
. I WISH THAT FANTASTECHA BE DESTROYED NOW, FUCKERS!!! 

FUCK YOU!!!!!!!!!! 

I DEMAND THAT FANTASTECHA BE DESTROYED NOW!!! 

1.
Fantastecha. 

2.
The Game of Life. 

[[concepts]]
=== Concepts

. Time 
. Soul 
. Mind 
. Pleasure 
. Suffering 
. Rest 
. Death 


[[license]]
== License:

https://creativecommons.org/licenses/by/4.0/[CC-by], Shlomi Fish, 2021 

**to add**: "the-codex" 