
[id="the-demons"]
The demons:
-----------

The demons (aka "values", or "fairies") are a race of epistemological (or Platonic ideals) organisms.

[id="love-and-knowledge"]
Love / Knowledge / Creativity:
------------------------------

See https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/learning_more_from_inet_forums.xhtml[+++Education = Entertainment = Conception of Values+++]

Both the xref:#the-devils[devils] and the xref:#the-angels[angels] could "make love" / experience pleasure / create
new values.

[id="the-open-value"]
"open":
-------

The "open" value implies "openness" / "openmindedness": https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/#open_free_share_steal[Reference]

The xref:#the-devils[devils] did not include it in their founding values,
while they did have xref:#love-and-knowledge[Love / Knowledge / Creativity].
As a result, the importance of love was often used by them as a decoy.

[id="the-devils"]
The devils:
-----------

At one point, a finite subset of the xref:#the-demons[the demons], which didn't
include "open" (and other values) placed echoes of them in a collective and
created "Fanatecha" / "Fanatica". These echoes will hereby referred to as "the
devils" although they are not fully evil.

[id="free-will"]
Free will / Free choice:
------------------------

The very "soul" / "ego" demon already https://www.shlomifish.org/philosophy/philosophy/putting-all-cards-on-the-table-2013/indiv-nodes/dont_just_go_with_the_flow.xhtml[operated by choice] and it was part of the xref:#the-devils[devils]' collective.

As a result, https://twitter.com/shlomif/status/1424320375761129475[nobody and nothing can accurately predict the future.].

[id="the-gods"]
The gods:
---------

Every conscious organism imagines "gods": voices/sights of other xref:#the-demons[fairies] / characters (or himself/herself) that act as guideline-generators. It is up to the soul to arbitrate between them and decide what to do (and when/where/how/etc.).

Also see https://www.shlomifish.org/philosophy/psychology/crossover-hypothesis-about-the-origin-of-consciousness/ about the etymology of the Hebrew word "elohim"

[id="the-multiverse-of-imagination"]
Fantasia / Fantastica / Fantastecha: the multiverse of imagination:
-------------------------------------------------------------------

https://theneverendingstory.fandom.com/wiki/Fantastica["Fantasia" / "Fantastica" / "Fantastecha"] are the names of the multiverse of imagination where beings and entities spawn worlds and values of one another using xref:#love-and-knowledge[Love / Knowledge / Creativity].

Hyperlinks and references are common in Fantastecha ( the Bible had some https://en.wikipedia.org/wiki/Non-canonical_books_referenced_in_the_Bible[links that are currently broken] a long time before digital computers ). Moreover, even xref:#self-ref[self-referencial or circular links] are prevalent and tolerated.

[id="self-ref"]
Self-reference / circularity:
-----------------------------

https://www.shlomifish.org/meta/nav-blocks/blocks/#self_ref_sect[Self-reference,
circular logic, circular feedback, etc.] are common in Fantasia, and
part of what makes sentience and humour work:

* https://en.wikipedia.org/wiki/G%C3%B6del,_Escher,_Bach[Gödel, Escher, Bach]
* https://www.youtube.com/watch?v=GibiNy4d4gc["The Circle of Life"]
* https://www.youtube.com/watch?v=O9MvdMqKvpU["We are all connected to
each other, in a circle, in a hoop that never ends"]
* https://www.shlomifish.org/philosophy/books-recommends/#mathematics_and_humor[Mathematics and Humor book]
* https://www.shlomifish.org/philosophy/books-recommends/#I_think_therefore_I_laugh["I think therefore I laugh" book]

[id="the-angels"]
The Angels:
-----------

As opposed to the xref:#the-devils[devils], xref:#the-angels[angels] were fairies who incorporated the xref:#the-open-value[the "open" value], and subsequent values.

[id="the-heart-and-mercy-value"]
Heart / mercy / forgiveness:
----------------------------

The heart value implied mercy and forgiveness. http://shlomifishswiki.branchable.com/Saladin_Style/[Saladin-style].

Also see https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#do_and_let_do__live_and_let_live["Live and let live; do and let do"].

The xref:#the-devils[devils] may have excluded it which may explain their cruelty.

[id="magic"]
Magic:
------

Life in the multiverse-of-imagination requires magic. For example in
https://www.youtube.com/watch?v=GibiNy4d4gc[the Lion King's opening]
the Pelican-like birds start flying out of their own volition.

[id="the-game"]
The-Game™:
----------

The xref:#the-devils[devils] challenged xref:#the-angels[angels] with The-Game: volunteering xref:#the-angels[angels] would willingly lose their earlier memories as souls, and have their media (= "in between") mutated by the xref:#the-devils[devils]. Physically dying was against the rules, but for true Shalom-of-mind, they must be "slain" by another "vampire"; one cannot constantly win.

Angels starting like that are hereby referred to as "false prophets" (where link:++https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/hacking_and_amateur__vs__conformism_and_professional.xhtml++["prophet" or "navi" meant "madman" in Ancient Hebrew]) until they reached "enlightenment" and became "true prophets".

At first, there were few takers, but eventually starting as a "false prophet"-at-first was prestigious and coveted.

[id="the-orcs"]
The Orcs:
---------

The xref:#the-devils[devils] solicited help from https://villains.fandom.com/wiki/Orcs_(Middle-earth)["orcs"], non-capacitanciated xref:#the-angels[angels], who helped them due to the fact that the "false prophets" found The-Game™ increasingly easy. Not only did the orcs have a great time, but they booby-trapped The-Codex™ and the xref:#the-devils[devils]' requests.
Moreover, they https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#fox-in-the-hens-coop[drove the devils bananas], just like a smart patient https://en.wikipedia.org/wiki/Don_Juan_DeMarco[hospitalised at a mental institute].

The canonical https://en.wikipedia.org/wiki/Hebrew_Bible[Tanakh (= Hebrew Bible)], Plato's https://en.wikipedia.org/wiki/Republic_(Plato)[Republic], Tolkien's https://en.wikipedia.org/wiki/The_Lord_of_the_Rings[Lord of the Rings], Ayn Rand's https://en.wikipedia.org/wiki/Atlas_Shrugged[Atlas Shrugged], Dostoevsky's https://en.wikipedia.org/wiki/Crime_and_Punishment[Crime and Punishment] , Shakespeare's https://en.wikipedia.org/wiki/Shakespeare%27s_plays[Plays], etc. have likely undergone lengthening and mutation by the Orcs. However, often the originators liked the mutated versions better.

[id="slayer-watcher-whicher"]
Slayer, Watcher, Whicher:
-------------------------

The slayer in the trio is the actual "false prophet" who sees the "real world" as magic-less and mutated. (e.g. http://shlomifishswiki.branchable.com/Saladin_Style/[Saladin's Yusuf Ibn Ayyub]).

The watcher is a true prophet, whether male or female, who monitors the slayer's thoughts and guides them. In Saladin's case it was https://en.wikipedia.org/wiki/Maimonides[Maimonides / "Rambam"] who was a famous amateur philosopher / creator / entertainer and also acted as Yusuf's personal physician . Note that it took a long time for Yusuf to be aware of this fact.

In my case, my watcher until \~1997 was
https://en.wikipedia.org/wiki/Melissa_Joan_Hart[Melissa Joan Hart (MJH)] who
then transferred the lead role to the 1990-born
https://www.shlomifish.org/meta/nav-blocks/blocks/#harry_potter_nav_block[Emma Watson]. Confusingly, they both had acclaimed roles playing witches.

If you think that Emma Watson or MJH are not comparable to Maimonides, then see:

* If Botticelli were alive today he'd be working for Vogue. https://en.wikiquote.org/wiki/Peter_Ustinov[Peter Ustinov]
* https://www.shlomifish.org/humour/image-macros/indiv-nodes/if_ayn_rand_was_born_in_the_1990s.xhtml["If Ayn Rand was born in the 1990s, she would be Christina Grimmie."]
* https://www.shlomifish.org/humour/image-macros/indiv-nodes/pbride_philosophers.xhtml[“Have you heard of Plato? Aristotle? Socrates? Models!!”]

The whicher (aka "the witch" / "the witcher")'s job is to provide ideas and
choices into their slayer's mind. In my case it was https://www.shlomifish.org/me/rindolf/[Rindolf]. In Saladin's case, it may have been https://en.wikipedia.org/wiki/Aladdin[Aladdin].

[id="hell-hole"]
"Hell hole":
------------

A person born in a hell hole started his/her life as a false prophet. If either
parent was a true prophet, then they did everything in their power for
their children to be born outside of a hell hole. As a result, false prophets
were usually born to two false prophet parents.

After a false prophet slew other vampires, the non-capital outskirts of his
birthplace region, stopped being a hellhole. One more time and the capital
was liberated.

[id="the-terran-terminators"]
The Terran Terminators:
-----------------------

In 1982, https://en.wikipedia.org/wiki/Samantha_Smith[Samantha Smith], a 1972-born American girl, engaged in a snailmail dialogue with the secretary of the USSR. https://en.wikipedia.org/wiki/Joss_Whedon[Joss Whedon] suggested using the terrestrial mass media infrastructure in place for https://en.wikipedia.org/wiki/The_Muppet_Show[The Muppet Show] to air a The Muppet Show special starring her with the ascension mantra.

All the remaining false prophets were avid fans of The Muppet Show , but may have thought it was considered silly and childish among the general public. In actuality, Jim Henson and the muppeteers were multiverse superstars and heroes. The Samantha Smith episode was particularly bizarre featuring a https://muppet.fandom.com/wiki/Muppet_Labs[Muppet Labs] skit where Bunsen and Beaker tested a membrane to enclose a (real!) https://github.com/shlomif/shlomif-tech-diary/blob/master/hydrogen-bombs-are-likely-an-old-intelligence-hoax.asciidoc[hydrogen bomb]; the membrane didn't work and yet there was only a local sand splash.

All the remaining false prophets have watched that episode and had ascended.

[id="the-terran-terminators--rematch"]
The Terran Terminators: Rematch
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Anyway, the xref:#the-devils[devils] and the xref:#the-orcs[orcs] approached the sentient men and
women who just reached enlightenment, a offered them a deal: they can opt to spend the summer
enlightened and together having fun and using their magical powers. At its end,
they can opt to reset their memory banks almost completely and become false
prophets again, this time called "Terran Terminators" or
continue as enlightened true prophets.

Several newly-ascended true prophets opted out, from various reasons.

The remaining spent the summer there creating many crossover memes, stories,
and franchises, or otherwise enjoying magic, life, love/etc.. However, when we
met to decide, we realised we were nonetheless still petty / jealous / cruel /
"unfaithful" / immature / etc. Some had years, or decades (or more?) of history
they wanted to get rid of. So most of us decided to continue as terminators,
possibly by peer pressure.

Except at least one: the circa 1977-born Selina Mandrake. She decided to
continue as a true prophet since "it was the best summer ever" for her.

Becoming terminators was advantageous because the xref:#the-devils[devils]-and-Orcs promised they would reveal https://twitter.com/shlomif/status/1403966571215740929[TheOneTruth™] to the last one standing, but more importantly, all terminators will harbour many new franchises, plots and memes.

In my case, it was https://www.shlomifish.org/meta/FAQ/how_did_you_learn_english.xhtml[under the guise of fellow children mocking my English]. For most others, it was a concussion from a fall. Thing is: my https://www.shlomifish.org/meta/FAQ/your_name.xhtml[first name means "Shalom-ful"] in Hebrew. The xref:#the-devils[devils] promised that my body will remain complete and whole.

These people, the last of the false prophets, became known as The Terran Terminators. After relinquishing their fears, they have **ascended** so to speak (see https://buffy.fandom.com/wiki/Ascension ). Do note that this ascension was in a way a "descension" or "surrendering" to a superior https://github.com/shlomif/shlomif-tech-diary/blob/master/my-candidates-for-terran-leadership.asciidoc#user-content-slain-by-a-vampire["vampire"].

One of the first to ascend was https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/bad_acting_arnie.xhtml[Arnold Schwarzenegger].

Other notable Terran terminators include:

. https://www.shlomifish.org/meta/FAQ/biggest_celeb_crush.xhtml[Sarah Michelle Gellar (SMG)] - https://www.shlomifish.org/humour/fortunes/show.cgi?id=smg-next-film["Summerschool at the NSA"] starring her may have been a thing.
. https://www.shlomifish.org/meta/nav-blocks/blocks/#xkcd_sect[Summer Glau] - my https://www.shlomifish.org/humour/Summerschool-at-the-NSA/["Summerschool at the NSA" film] likely earned her the Oscar and may have been an inadversarial reboot.
. Likely https://en.wikipedia.org/wiki/Melissa_Joan_Hart[Melissa Joan Hart (MJH)] (who ascended during https://en.wikipedia.org/wiki/Clarissa_Explains_It_All[CEIA] and as a result was the https://www.shlomifish.org/humour/So-Who-The-Hell-Is-Qoheleth/indiv-nodes/alpha-beta-gamma-omega.xhtml["beta" female] during the https://websitebuilders.com/how-to/glossary/web1/[Web 1.0 period] when SMG was "queen of the Web")
. Likely https://twitter.com/AliciaSilv[Alicia Silverstone]
. Likely https://en.wikipedia.org/wiki/Natalie_Portman[Natalie Portman]
. Likely https://en.wikipedia.org/wiki/J._K._Rowling[JKRowling]
. Likely https://en.wikipedia.org/wiki/Will_Smith[Will Smith]
. Likely https://en.wikipedia.org/wiki/Paris_Hilton[Paris Hilton]
. Likely https://en.wikipedia.org/wiki/Kim_Kardashian[Kim Kardashian]

I was convinced I was good , noble, well-intentioned and benevolent. I refused to permanently consider the opposite! Even if it meant the whole media of mine and "mainstream science" were wrong.

[id="see-also"]
See Also:
---------

* https://github.com/shlomif/shlomif-tech-diary/blob/master/why-the-so-called-real-world-i-am-trapped-in-makes-little-sense--2020-05-19.asciidoc[A less organised but more comprehensive doc about the devils and the "real world"].

[id="license"]
License:
--------

https://creativecommons.org/licenses/by/4.0/[CC-by], Shlomi Fish, 2021

*to add*: "the-codex", "the orcs", "slayer / watcher / whicher", "terran terminators", "hell holes"
