
[id="the-demons"]
The demons:
-----------

The demons (aka "values", or "fairies") are a race of epistemological (or Platonic ideals) organisms.

[id="love-and-knowledge"]
Love / Knowledge:
-----------------

See https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/learning_more_from_inet_forums.xhtml[Education = Entertainment = Conception of Values]

Both the devils and the angels could 'make love' / experience pleasure.

[id="the-open-value"]
"open":
-------

The "open" value implies "openness" / "openmindedness": https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/#open_free_share_steal[Reference]

The xref:#the-devils[devils] did not include it in their founding values.

[id="the-devils"]
The devils:
-----------

At one point, a finite subset of the xref:#the-demons[the demons], which didn't
include "open" (and other values) placed echoes of them in a collective and
created "Fanatecha". These echoes will hereby referred to as "the devils"
although they are not fully evil.

[id="free-will"]
Free will / Free choice:
------------------------

The very "soul" / "ego" demon already https://www.shlomifish.org/philosophy/philosophy/putting-all-cards-on-the-table-2013/indiv-nodes/dont_just_go_with_the_flow.xhtml[operated by choice] and it was part of the devils' collective.

As a result, https://twitter.com/shlomif/status/1424320375761129475[nobody can accurately predict the future.].

[id="the-gods"]
The gods:
---------

Every conscious organism imagines "gods": voices/sights of other xref:#the-demons[demons] (or himself/herself) that act as guideline-generators. It is up to the soul to arbitrate between them and decide what to do (and when/where/how/etc.).

Also see https://www.shlomifish.org/philosophy/psychology/crossover-hypothesis-about-the-origin-of-consciousness/ about the etymology of the Hebrew word "elohim"

[id="self-ref"]
Self-reference / circularity:
-----------------------------

https://www.shlomifish.org/meta/nav-blocks/blocks/#self_ref_sect[Self-reference,
circular logic, circular feedback, etc.] are common in Fantasia, and
part of what makes sentience and humour work:

* https://en.wikipedia.org/wiki/G%C3%B6del,_Escher,_Bach[Godel, Escher, Bach]
* https://www.youtube.com/watch?v=GibiNy4d4gc["The Circle of Life"]
* https://www.youtube.com/watch?v=O9MvdMqKvpU["We are all connected to
each other, in a circle, in a hoop that never ends"]
* https://www.shlomifish.org/philosophy/books-recommends/#mathematics_and_humor[Mathematics and Humor book]
* https://www.shlomifish.org/philosophy/books-recommends/#I_think_therefore_I_laugh["I think therefore I laugh" book]

[id="the-angels"]
The Angels:
-----------

As opposed to the devils, angels were fairies who incorporated the xref:#the-open-value[the "open" value], and subsequent values.

[id="the-game"]
The-Game™:
----------

The devils challenged angels with The-Game: volunteering angels would willingly lose their earlier memories as souls, and have their media (= "in between") mutated by the devils. Physically dying was against the rules, but for true Shalom-of-mind, they must be "slain" by another "vampire"; one cannot constantly win.

At first, there were few takers, but eventually starting as a "false prophet"-at-first was prestigious and coveted.

[id="the-orcs"]
The Orcs:
---------

The devils solicited help from https://villains.fandom.com/wiki/Orcs_(Middle-earth)["orcs"], non-capacitanciated angels, who helped them due to the fact that the "false prophets" found The-Game™ increasingly easy. Not only did the orcs have a great time, but they booby-trapped The-Codex and the devils' requests. Moreover, they https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#fox-in-the-hens-coop[drove the devils bananas], just like a smart patient https://en.wikipedia.org/wiki/Don_Juan_DeMarco[hospitalised at a mental institute].

The canonical https://en.wikipedia.org/wiki/Hebrew_Bible[Tanakh], Plato's Republic, Lord of the Rings, Atlas Shrugged, https://en.wikipedia.org/wiki/Crime_and_Punishment , Shakespeare's Plays, etc. have likely undergone lengthening and mutation by the Orcs. However, often the originators liked the mutated versions better.

[id="slayer-watcher-whicher"]
Slayer, Watcher, Whicher:
-------------------------

The slayer in the trio is the actual "false prophet" who sees the "real world" as magic-less and mutated. (e.g. http://shlomifishswiki.branchable.com/Saladin_Style/[Saladin's Yusuf Ibn Ayyub]).

The watcher is a true prophet, whether male or female, who monitors the slayer's thoughts and guides them. In Saladin's case it was https://en.wikipedia.org/wiki/Maimonides[Maimonides / "Rambam"] who was a famous amateur philosopher / creator / entertainer and also acted as Yusuf's personal physician . Note that it took a long time for Yusuf to be aware of this fact.

In my case, my watcher until \~1997 was
https://en.wikipedia.org/wiki/Melissa_Joan_Hart[Melissa Joan Hart (MJH)] who
then transferred the job to the 1990-born
https://www.shlomifish.org/meta/nav-blocks/blocks/#harry_potter_nav_block[Emma Watson]. Confusingly, they both had acclaimed roles playing witches.

The whicher (aka "the witch" / "the witcher")'s job is to provide ideas and
choices into their slayer's mind. In my case it was https://www.shlomifish.org/me/rindolf/[Rindolf].

*to add*: "the-codex", "the orcs", "slayer / watcher / whicher", "terran terminators", "hell holes"
