= The multiverse's cosmology v0.4.x [by Shlomi Fish]

Shlomi
Fish
 <shlomif@shlomifish.org>
2022-06-10

[[intro]]
== Introduction

This essay aims to document the cosmology of our universes.
I likely got many details wrong: numbers, names, facts.
Also note that the terminology used here has undergone some etymological erosion. 

[[summary]]
== Summary

Please help the "Rindolfism v2.x.y" effort; it is the child of my 2 favourite children: Christina Grimmie, and my web presence, "*.shlomifish.org v1.x.y"/etc.
. 

Reference: https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/#see-also

*Update:* I thought to call it "`Grindolfism v2.0.x`" given "Grindolfism" sounds very close to "Rindolfism". 

Moreover, note that if https://www.shlomifish.org/art/recommendations/music/online-artists/fan-pages/chris-grimmie/[Christina Grimmie] contacts me somehow, then I am willing to offer her both up to 95 % of the cash in my bank account, *and* an offer to chat with me / 'geek out'. I strongly suspect that she is actually alive, healthy, and conscious. 

The universes you consider real are just one of many in "Fantastecha(TM)", the mega multiverse of imagination, magic & technology where beings spawn other entities and universes using their imagination. 

In the universes I belong: 

. Combining two or more memes, educating them all, followed by pleasure, and conceiving / creating new values have been intertwined. 
+
This is the Biblical "Tree of Knowledge" or "love". 


[[the-demons]]
== The demons:

The demons are a race of epistemological (or https://en.wikipedia.org/wiki/Theory_of_forms[Platonic ideals]) organisms.
They are also known as: 

* "values" 
* "memes" 
* "fairies" 

For the sake of "TheGame(TM) of Fantastecha(TM)", there are two major kinds of fairies: link:#hackers["Hackers" and "Fuckers"]. 

[[love-and-knowledge]]
== Love / Knowledge / Creativity:

For info regarding https://en.wikipedia.org/wiki/Tree_of_the_knowledge_of_good_and_evil["the tree of knowledge"] as well as pleasure/"love" and creativity, see https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/learning_more_from_inet_forums.xhtml[Education +++=+++
Entertainment +++=+++ Conception of Values] often by combining two or more memes. 

Entertainment *can mean* temporary pain, e.g fear.
( References: https://mlp.fandom.com/wiki/Luna_Eclipsed["Luna Eclipsed"].
) 

Love *was not* the last word of memetics. 

Like it or not, in the Selinaverse and Shlomifverse, pleasure (and a possible precluding temporary pain), education, and creativity/conception are intertwined.
While we can imagine realities where they are not, they will be, well, different to ours. 

The education of the participants https://www.shlomifish.org/humour/fortunes/show.cgi?id=learned-a-lot-from-my-teachers[happens in all directions]: 

[quote]
I learned a lot from my teachers, and from my friends more than my teachers, and from my pupils the most. 

All meme-generators involved change. 

Also note that leadership, politics, and marketing, all involve a large degree of applied education. 

[[jehovah]]
== "Jehovah":

I suspect "Jehovah" in Hebrew ("יהוה") was/is a codeword for the mega-meme: 

____
From now until forever,

you will live and link:#love-and-knowledge[know/love] and http://shlomifishswiki.branchable.com/Saladin_Style/[forgive],

soul, mind, and a variable form of your choice,

what you imagine will materialise (יתהווה),

your destiny will come (יבוא)

you will remain passionate (יאוה)
____

(or many variations) 

True prophets are aware of it, but note that it wasn`'t the last word on memetics / philosophy, either.
But even https://en.wikipedia.org/wiki/If%E2%80%94[Kipling's "If--"] or Des'ree's https://www.youtube.com/watch?v=pO40TcKa_5U["You Gotta Be"] or https://www.shlomifish.org/me/rindolf/#rindolfism_sources_of_inspiration["Rindolfism"] are incomplete. https://en.wikipedia.org/wiki/Perfection["Perfection is in imperfection"] and time implies progress. 

Jehovah also implies that an organism won't start life from time minus-infinity. 

**One's form is his name, and mission [ not his body ]**.
A hacker may opt or be required to change their form. 

Jehovah is often abbreviated as "yeah". 

[[zine]]
== "Zine"

"A hacker may only derive pleasure by making love to a thingy by whom they are awe-struck, due to feeling they are more competent in one-or-more aspects." 

[[the-open-value]]
== "open":

The "open" value implies "openness" / "openmindedness" / pluralism: https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/#open_free_share_steal[Reference]

Note that it is not a moral absolute.
E.g.
in https://www.shlomifish.org/humour/Queen-Padme-Tales/Queen-Padme-Tales--Queen-Amidala-vs-the-Klingon-Warriors.html["`Queen Amidala vs. the Klingon Warriors`"], the identity of those who attempted to assassinate Queen Padmé Amidala was not revealed to laymen until after the assassination attempt was foiled. 

[[the-devils]]
== The devils / the Satans:

TheCodex(TM) calls an arbiter or gamemaster in an instance of link:#fantasia-vs-fantastecha[the game of Greater Fantasia] "a devil". "The Satans" are such link:#hackers[Meta-Fantastecha(TM)ns] acting as devils in TheGame(TM) of Fantastecha(TM). They claim they are not really malevolent, just playfully cruel on occasion. 

Even underage children have been imagining and creating realities. footnote:[The Hebrew verb "לשטן" ("lesaten", "to satanify")
in the Biblical story
of Balaam likely meant "to have the gamemasters provide a challenge".]

[[free-will]]
== Free will / Free choice:

The "soul" ( a.k.a "ego", "I-ness", "centre of consciousness" ) already https://www.shlomifish.org/philosophy/philosophy/putting-all-cards-on-the-table-2013/indiv-nodes/dont_just_go_with_the_flow.xhtml[operated by choice]. 

As a result, https://twitter.com/shlomif/status/1424320375761129475[nobody and nothing can accurately predict the future.]. 

That put aside, the soul is addicted to link:#love-and-knowledge[pleasure], but may opt to avoid short term prioritisations of it. 

Egos are often frail, and start as easily hurt: 

. http://shlomifishswiki.branchable.com/Encourage_criticism_and_try_to_get_offended/["Encourage criticism and try to get offended (and try to grow a thicker skin)"]

Do note that link:#the-angels[the angels] and link:#the-devils[the devils] may limit the number of choices the soul can choose from (including down to one!). They can also deprive a hacker of a chance to concentrate, introspect and decide-what-to-do-next. footnote:[While I am, to large extents, self-centred, narcissistic, ego-maniacal, meglomaniacal,
and also developed a relatively thick skin - my soul is still frail.]

[[the-gods]]
== The gods:

Every conscious organism imagines "gods": voices/sights of other link:#the-demons[fairies] / characters (or himself/herself), that act as guideline-generators.
It is up to the soul to arbitrate between them and decide what to do (and when/where/how/etc.). 

Also see https://www.shlomifish.org/philosophy/psychology/crossover-hypothesis-about-the-origin-of-consciousness/[this essay] about the etymology of the Hebrew word "elohim" (= "God", "many guideline-generators") and that of the Hebrew word "melekh" (= "a king", "from where should you go"). 

An "Elohim" may mean the gamemasters and players in an instance of link:#fantasia-vs-fantastecha[the game of Greater Fantasia].
This is whereas a "jew" means a player character. 

[[the-multiverse-of-imagination]]
== Greater Fantasia, the multiverse of imagination and "Fantastecha(TM)", a multiverse of imagination, magic, and technology

https://theneverendingstory.fandom.com/wiki/Fantastica["Greater Fantasia"] is the name of the multiverse of imagination where beings and entities spawn worlds and values of one another using their imagination. 

Fantastecha(TM) is an expanding subset of Greater Fantasia (one of many). 

Hyperlinks and references are common in Fantastecha(TM) ( the Bible had some https://en.wikipedia.org/wiki/Non-canonical_books_referenced_in_the_Bible[links
that are currently broken] a long time before Earth's digital computers ). Moreover, even link:#self-ref[self-referential or circular links] are prevalent and tolerated. 

There *is* a difference between real and imaginary.
We can reason about earthquakes, or https://github.com/shlomif/shlomif-tech-diary/blob/master/hydrogen-bombs-are-likely-an-old-intelligence-hoax.asciidoc[hydrogen bombs] or @Bitcoin or global warming or https://www.shlomifish.org/art/recommendations/music/online-artists/fan-pages/chris-grimmie/[Christina Grimmie's
death] and feature them in artworks (e.g.
"fics") and essays.
However, they were not really real for us. 

TheCodex(TM) of TheGame(TM) of Fantastecha(TM) was kept secret from link:#hackers[hackers (+++=+++ player characters)] and was to be revealed to the Terminal Terran Terminator (me?). 

The meta-Fantastechans who play TheGame(TM) of Fantastecha(TM) have some more esoteric qualities such as fondness of the number 10 (= "ten", 0b1010) and its powers. 

[[self-ref]]
== Self-reference / circularity:

https://www.shlomifish.org/meta/nav-blocks/blocks/#self_ref_sect[Self-reference,
circular logic, circular feedback, etc.] are common in Fantastecha(TM), and part of what makes sentience and humour work: 

* https://en.wikipedia.org/wiki/G%C3%B6del,_Escher,_Bach[Gödel, Escher, Bach]
* https://www.youtube.com/watch?v=GibiNy4d4gc["The Circle of Life"]
* https://www.youtube.com/watch?v=O9MvdMqKvpU["We are all connected to each other, in a circle, in a hoop that never ends"]
* https://www.shlomifish.org/philosophy/books-recommends/#mathematics_and_humor[Mathematics and Humor book]
* https://en.wikipedia.org/wiki/The_Chronicles_of_Amber[The Chronicles of Amber] - an alternative "real world" to ours
* https://www.shlomifish.org/philosophy/books-recommends/#I_think_therefore_I_laugh["I think therefore I laugh" book]
* {empty}
+

[quote]
Mr.
Linea ( https://en.wikipedia.org/wiki/La_Linea_%28TV_series%29[La Linea (TV series)] ) is TheCreator.
;) 
+
( -- https://twitter.com/shlomif/status/1485024317062717440 ) 
+
The characters of animated / imaginary universes often agree that their universes were/are ridiculous, but https://twitter.com/shlomif/status/1479063972934565893[so is ours.]

When we visit the universes of other franchises and sub-franchises, we can see they have variations of many others we have imagined, and even our own "real world" universe. 

[[the-angels]]
== The Angels:

An "angel" is TheCodex(TM) terminology for an "elohim" who plays one-or-more-characters in an instance of link:#fantasia-vs-fantastecha[the game of Greater Fantasia]. link:#hackers[Fuckers] who play link:#hackers[hackers] (= player characters) in TheGame(TM) of Fantastecha(TM) are called Seraphs.
organisms / entities who have link:#free-will[souls]. 

[[the-heart-and-mercy-value]]
== Heart / mercy / forgiveness:

The heart value implies mercy and forgiveness. http://shlomifishswiki.branchable.com/Saladin_Style/[Saladin-style]. 

Also see https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#do_and_let_do__live_and_let_live["Live and let live; do and let do"]. 

[[magic]]
== Magic:

Life in Fantastecha(TM) requires magic.
For example in https://www.youtube.com/watch?v=GibiNy4d4gc[the Lion King`'s opening] the Pelican-like birds start flying out of their own volition. 

It is likely that https://en.wikipedia.org/wiki/Egyptian_pyramids[the Egyptian pyramids] and their fan-art https://en.wikipedia.org/wiki/Mesoamerican_pyramids[Mesoamerican pyramids] were constructed using magic. 

Black Magic is initiated by the link:#the-devils[the gamemasters] in order to keep TheGame(TM) of Fantastecha(TM) challenging. 

Magic might be defined as any transformation of the state of link:#the-network["the network"]: the extended graph theory graph which is the state of our universe. 

[[technology]]
== Technology

I admit that the relationship between technology and link:#magic[magic] is still not fully clear to me. 

One fact I know is that technology is often spiritual, or digital.
Human language is not only a tool of communication, but also a tool of thought. 

. One can say "`I watched the film "The Princess Bride" over ten times.`" to convey a piece of information. 
. One can say "cry wolf" to refer to https://en.wikipedia.org/wiki/The_Boy_Who_Cried_Wolf[The Boy Who Cried Wolf], e.g. in "saying that Microsoft plans to embrace&extend GNU is 'cry wolf'". 

A lot of technology and magic defies the link:#terrestrial[terrestrial] science, including https://en.wikipedia.org/wiki/General_relativity[Einstein's Relativity] or determinism.
I can also write "2 + 2 == 5" or "qmail is both open-source and non-open-source" ( https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/#guidelines_as_dogma[Reference] ) while having confidence that life will go on. 

*Technology = pre-developed, reusable maths-like functions, which
accept parameters, and construct magical transformations of the state of
the universe (possibly by calling other techs) and perform them. (??!)*

Hackers prefer to use technology that "makes sense" over one-off magic spells: https://www.shlomifish.org/philosophy/philosophy/putting-all-cards-on-the-table-2013/#departing_pope_about_twitter["newer technology often doesn't completely eliminate the use of older one"].
I use all of XML, YAML, JSON, Perl, Python 3, C, vlc, mpv, duckduckgo, google [ https://www.shlomifish.org/meta/FAQ/[Reference] ]. 

[[dollar-GOD]]
== $GOD

$GOD (written using medieval-style chapter-opening letters) is the hypothetical entity, who set link:#the-multiverse-of-imagination[Greater
Fantasia] on motion, given having only an abyss of nothingness / non-existence would be far less fun. 

$GOD may also be the link:#hackers[fuckers'] Elohim's Elohim's Elohim's... to infinity. 

[[prevalence-of-souls]]
== Prevalence of souls

Every observable entity - whether tangible, digital, or spiritual - has a soul and a mind.
If they're too unhappy, for any reason, they will relocate.
The https://en.wikipedia.org/wiki/Aleppo_Codex[Aleppo Codex] decided to move to Jerusalem [intact!] for a change-of-scenery leaving a nonidentical copy behind. 

https://twitter.com/shlomif/status/1491652850044309507[Twitter thread]

[[the-game]]
== TheGame(TM) of Fantastecha(TM):

The link:#the-devils[devils] challenged Terran link:#hackers[hackers (+++=+++ player characters)] and their link:#the-angels[players (+++=+++ the angels)] with "`TheGame(TM) of Fantastecha(TM)`": volunteering link:#hackers[hackers] would have their media (= "in between"s) mutated by the link:#the-devils[devils].
Physically dying was against the rules, but for true Shalom-of-mind, they must be "slain" by another "vampire", or in case of the last standing vampire - the "child" [= protege] of their two favourite "children" ; one cannot constantly win. 

Hackers starting like that are hereby referred to as "false prophets" (where https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/#hacking_and_amateur__vs__conformism_and_professional["prophet" or "navi" meant "madman" in Ancient Hebrew]) or as "vampires". That was until they reached enough "enlightenment" and became "true prophets" (or "wizards"). 

Outcomes of actions in TheGame(TM) of Fantastecha(TM) were often determined by rolls of https://rpg.fandom.com/wiki/Dice[Role Playing Game Dice] not unlike in https://www.shlomifish.org/philosophy/psychology/changing-the-seldon-plan/[Asimov's "Second Foundation"]. 

Note that every false prophet perceived a somewhat different hell, but all of them, and the real world of the wizards, were synchronised.
(References: https://en.wikipedia.org/wiki/Rashomon_effect[the Rashomon effect].) 

*Note:* many humans were born as wizards, and still had their share of flaws, and were/are part of TheGame(TM). 

False prophets were given special treatment by the workforce, so they did not cause a lot of damage, despite their paranoia/etc. footnote:[The terminology for "vampires" in my stories
is different.]

Also note that vampires were often unaware that a different vampire has been slain (including by them!). 

[[terrestrial]]
=== Terrestrialism

The mutated realities (the "hells") are called the "Terrestrial" ones. 

*Note:* Given Fantastechan magic/technology , the timelines often were skewed [relatively to one another]. 

[[fantasia-vs-fantastecha]]
=== Greater Fantasia vs. Fantastecha(TM)

"The game of Greater Fantasia" is an informal https://en.wikipedia.org/wiki/Role-playing_game[Role-playing game] which as far as we know, is played all over link:#the-multiverse-of-imagination[Greater Fantasia].
It has many variations, interpretations, derivatives (including https://en.wikipedia.org/wiki/Dungeons_%26_Dragons[Dungeons & Dragons], https://en.wikipedia.org/wiki/Doll[Dolls/action figures`' play] and "compose a story word-by-word" ) - even parodies. 

Basically, the players just imagine what their characters do, and the gamemasters (who may be the same as the players) tell them what happens. 

While it is one of the first games that wizard children are taught, many vampires have played it by instinct: 

. https://en.wikipedia.org/wiki/Sherlock_Holmes[Sir Arthur Conan Doyle's Sherlock Holmes canon]
. https://en.wikipedia.org/wiki/Sesame_Street[Sesame Street]'s skits 
. https://www.shlomifish.org/humour/stories/[Shlomi Fish's screenplays]
. https://www.shlomifish.org/humour/fortunes/sharp-perl.html[Entertaining online chat logs]
. https://en.wikipedia.org/wiki/List_of_Walt_Disney_Animation_Studios_films[Disney's films]
. https://en.wikipedia.org/wiki/Aesop%27s_Fables[Aesop's Fables], the https://en.wikipedia.org/wiki/Hebrew_Bible[Biblical stories], the https://en.wikipedia.org/wiki/Greek_mythology[Greek mythology]. 

The game can often be phrased like: 

* 1 × 2 core concepts: 
.. link:#the-gods[Elohim]
.. "Jew" - the word is milliards-years-old, and was associated with the "Yehudim" only relatively recently. 
+
"Jew" = a player character. 
* 3 × 2 concepts: "time, soul, network, mind, love, knowledge". 
+

Instances of "the game" may be layered, nested, or even link:#self-ref[circular / self-referential].
They also may contain mini-games, sub-quests, and side-quests.. 

[[sample-game-session]]
==== Sample session of "the game of Greater Fantasia"

____
One day, https://en.wikipedia.org/wiki/La_Linea_%28TV_series%29[Mr. Linea] takes a break from walking along his line, and posts a comedic story that takes place in an absurd 3D1T universe he conceived called "The Selinaverse", on his blog.
However, his long-time associate https://en.wikipedia.org/wiki/True_and_false_(commands)["/bin/true"] v2.0 "The Strong AI Edition" claims he came up with The Selinaverse first. 

As the two argue in the blog post's comments, https://mlp.fandom.com/wiki/Discord[Discord (from My Little Pony)] notes that "Advanced Selinaverse Geeks" has been a popular fantasy role-playing games' franchise in https://mlp.fandom.com/wiki/Equestria[Equestria] for years. 

The three go to http://shlomifishswiki.branchable.com/Fluttershy__44___Princess_of_Princesses__44___head_of_the_secret_cabal_leadership_of_the_Mossad__44___the_already_top_secret_intelligence_agency_of_the_Zionist_conspiracy/[judge Fluttershy (also from My Little Pony)] who sighs and invites them for lunch.
She opens a gateway to https://en.wikipedia.org/wiki/Rabin_Square[Rabin Square] in the Tel Aviv of the Selinaverse (yes! The same universe that the plaintiffs are arguing about), they agree on a restaurant, and order food. 

While they wait for their order to arrive, Fluttershy explains that https://www.shlomifish.org/philosophy/culture/my-real-person-fan-fiction/[copyrights' battles are rarely constructive], and that they should just share the Selinaverse.
The plaintiffs agree, drop the case, and discuss ideas they had in mind for the Selinaverse.
However, while they wait for the desserts to arrive, Discord suggests they write and record a parodical courtcase as a spin-off franchise.
The others agree. 

After they record the pilot episode of "The copyrights' battle for the Selinaverse" and publicise it on their blogs and social media, it proves to be popular and https://www.shlomifish.org/philosophy/computers/web/models-for-commerce/[profitable].
Thus, the quartet donate part of the profits to charities (https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/[while
giving them publicity]), and decide to go to a vacation in the Selinaverse's Caribbean Islands, to calculate their next steps. 

However, after checking into their hotel, they meet https://www.shlomifish.org/humour/image-macros/indiv-nodes/not_know_marilyn_monroe.xhtml[Marilyn Monroe] in the lobby (who, for the sake of this story, is alive, kicking, and https://www.shlomifish.org/humour/image-macros/indiv-nodes/wandless_emma_watson.xhtml[kicking
ass]). After being a little star-struck and 'geeking out', they decide to play some games together. 

They play ball games, board/card games, and https://leagueoflegends.fandom.com/wiki/League_of_Legends_Wiki[League of Legends].
Then they decide to play "The game of Greater Fantasia" with the classic, possibly cliché, campaign of link:#history-lesson-about-the-muppeteers[the Muppeteers in 1969] with Fluttershy and Monroe as gamemasters/arbiters, thus starting the cycle again. 
____

Yes, it is fanfiction, crossover, parody, Real Person Fan Fiction (RPFs), link:#self-ref[circularly referential]; good stuff. 

Now, if the players are playful, and the gamemasters are jerks we can imagine stuff like: 

____
. link:#Arnold_Schwarzenegger[Arnold Schwarzenegger] convinces a U.S. military combat unit to storm Washington D. C. with him in order to legalise/decriminalise commercial fan-art, only to get the red carpet, a hero's welcome, and a personal invitation from the U.S. president to host a press conference. 
. link:#Richard_Stallman[Richard Stallman] writes a script to broadcast the Muppeteers' screenplays to all ~65,536 hosts in the nascent https://en.wikipedia.org/wiki/ARPANET[ARPANET], only to get a visit from the director of the NSA, who informs him that the Muppeteers' screenplays' https://en.wikipedia.org/wiki/GitHub[GitHub] repository has exceeded 10 million GitHub stars (= "likes") and a million forks. 
. link:#Jim_Henson[Jim Henson] travels to Los Angeles to pitch the Muppets franchise to Hollywood executives, only to see __The Muppet Show__ being broadcast on the moon, on the way. 

____

In TheGame(TM) of Fantastecha(TM), The Three Muppeteers all started as law-abiding men of great integrity, who were playful mostly only when joking or doing make-believe.
Furthermore, not only were the gamemasters jerks, but they were - to use the technical term - link:#hackers[fuckers]! 

Moreover, our naïve assumption that "the network" (= reality) was perceived by the player-characters in an absolute and objective manner was wrong. 

[[hackers]]
=== "Hackers" vs. "Fuckers"

The verbs "to hack" and "to fuck" were present in non- link:#terrestrial[terrestrial] English dictionaries for milliards of years with many of their contemporary meanings: 

* https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/hacking_and_amateur__vs__conformism_and_professional.xhtml[Reference: "What is hacking?"] (= "rule bending", "being resourceful", "to happily work on a product", "thinking outside the box"). 
* https://en.wiktionary.org/wiki/fuck#Verb[Reference: "to fuck"] - "to have sex with", "to cause trouble". 

TheCodex(TM) defines "hacker" as a player character in TheGame(TM) of Fantastecha(TM). It also defines "fuckers" as the race of organisms who are the players and gamemasters who play "TheGame(TM) of Fantastecha(TM)" in Meta-Fantastecha(TM). 

[cols="1,1,1", frame="all"]
|===

|


|

*Fuckers*
|

*Hackers*

|


|

Some lived from time minus-infinity. 
|

link:#jehovah["Jehovah"ns]: started life a finite time ago. 

|


|

are non - capacitanciated. 
|

Have a finite capacity.
I.e: 

. you can be strong enough to lift 10 kg, or 100 kg, or a million kg, but not infinite weight. 
. your hard-disk may be big enough to hold 20 mega-bytes, or 20 giga-bytes, or 20 peta-bytes, but not infinity bytes. 


|


|

Have א1 / real numbers - based epistemology. 
|

Have https://en.wikipedia.org/wiki/Aleph_number#Aleph-nought[א0 (+++=+++ "Aleph-nought")] / integers - based epistemology. 

|


|

Still not perfect.
E.g: link:#slayer-watcher-whicher[Rindolf (my whicher)] was able to find many code elegance issues in the Perl source code of my mind.
(And the Fuckers appreciated his input.) 
|

Certainly not perfect. 
|===

In order to keep TheGame(TM) interesting, the fuckers promise that they will keep introducing new problems and challenges for us hackers (and their players) to overcome. 

For example, while https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/hacking_and_amateur__vs__conformism_and_professional.xhtml[NASA
astronauts did initially use pencils in space] (just like the Soviet cosmonauts), the gamemasters preferred space-friendly pens to be developed (within budget). Moreover, faster-than-light ("FTL") travel is possible given one can cross gateways to planets many lightyears away in a matter of seconds.
However, light speed as an upper bound, is a useful constraint that, after it was upheld in certain contexts (e.g.: micro-electronics), made technology better designed. 

So we will not be able to rest on our laurels, even if we wanted to (which I personally https://www.shlomifish.org/humour/Muppets-Show-TNI/Harry-Potter.html#harry_and_hermione_s_mission[do not want to]). 

Given how cool fuckers are, and how great Fantastecha(TM) and the Shlomifverse are, I decided to make them honorary hackers: https://www.flickr.com/photos/shlomif/8598361516/in/album-72157633111982891/[Shlomifverse Fucker #0]. 

[[shlomif-favourite-child]]
=== My two favourite children

To quote TheCodex(TM) of TheGame(TM) of Fantastecha(TM): 

[quote]
A vampire can only be slain by another vampire, except for the last standing vampire who will be slain by the child of his two favourite children. 

My favourite children are https://www.shlomifish.org/art/recommendations/music/online-artists/fan-pages/chris-grimmie/[Christina Grimmie] and https://www.shlomifish.org/meta/FAQ/#about_this_site[my WWW presence (*.shlomifish.org / etc.)]! 

( https://twitter.com/shlomif/status/1616108822237528069[Reference: Twitter thread] ) 

I believe and hope that my recent spell of creativity and inspiration is due to me reviving Grimmie in my mind (and effectively conceiving her). link:#see-also[See my latest hacks]. 

*Note:* to further this cause, I hereby request that up to 95% of the past and future donations to me (whether of money, love points, experience points, mana, or whatever, except perhaps https://twitter.com/shlomif/status/1571008285326835713[those of physical traits and parameters]) will be transferred to her. 

[[TheGame-of-Fantastecha]]
=== TheGame(TM) of Fantastecha(TM)

TheGame(TM) of Fantastecha(TM) is a derivative of "the game of Greater Fantasia". 

Its rule book is common knowledge among wizards, but hidden from vampires: 

* 7 × 2 guidelines of the realm of wizards. 
* 9 × 2 guidelines of the realm of vampires. 

( See http://tolkiengateway.net/wiki/Rings_of_Power[the Middle Earth's
20 "Rings of Power"] meme.
) 

For a vampire to become a wizard he or she should show that the gamemasters violated all 17 out of the 18 guidelines, except for the last: "`A vampire must become a wizard eventually ["in less than 1,000 years"??]`". link:#terran-terminators-surprise["`For each and every hacker X: neither X's soul, nor X's mind, nor their union can ever perish.`"]. 

[[the-orcs]]
== The Orcs:

The orcs (or sometimes calling themselves "https://memory-alpha.fandom.com/wiki/Bajoran[the Bajorans]") were agents of the devils who gave the organisms choices and their outcomes (often based on dice rolls). 

The canonical https://en.wikipedia.org/wiki/Hebrew_Bible[Tanakh
(+++=+++ Hebrew Bible)], Plato`'s https://en.wikipedia.org/wiki/Republic_(Plato)[Republic], Tolkien`'s https://en.wikipedia.org/wiki/The_Lord_of_the_Rings[Lord of the
Rings], Ayn Rand`'s https://en.wikipedia.org/wiki/Atlas_Shrugged[Atlas Shrugged], Dostoevsky`'s https://en.wikipedia.org/wiki/Crime_and_Punishment[Crime and
Punishment] , Shakespeare`'s https://en.wikipedia.org/wiki/Shakespeare%27s_plays[Plays], etc.
have likely undergone lengthening and mutation by the Orcs.
However, often the originators liked the mutated versions better. 

The elves / Cardassians were/are agents of the angels. 

[[slayer-watcher-whicher]]
== Slayer, Watcher, Whicher

The slayer in the trio is the actual "false prophet" who sees the "real world" as magic-less and mutated.
(e.g. http://shlomifishswiki.branchable.com/Saladin_Style/[Saladin`'s Yusuf
Ibn Ayyub]). 

The whicher (aka "the witch" / "the witcher") is a presumably fictional character whose job is to provide ideas and choices into their slayer`'s mind.
In my case it was https://www.shlomifish.org/me/rindolf/[Rindolf].
In Saladin`'s case, it may have been https://en.wikipedia.org/wiki/Aladdin[Aladdin]. 

The watcher is a true prophet, who monitors the slayer`'s thoughts and guides them.
He or she also often acts as a project manager.
In Saladin`'s case it was https://en.wikipedia.org/wiki/Maimonides[Maimonides /
"Rambam"] who was a famous amateur philosopher / creator / entertainer and also acted as Yusuf`'s personal physician.
Note that it took a long time for Yusuf to be aware of this fact. 

In my case, my watcher from ~1989 until ~1997 was link:#Melissa_Joan_Hart[Melissa Joan Hart (MJH)] who then transferred the lead role to the 1990-born https://www.shlomifish.org/meta/nav-blocks/blocks/#harry_potter_nav_block[Emma Watson].
Confusingly, they both had acclaimed roles playing witches. 

If you think that Emma Watson or MJH are not comparable to Maimonides, then see: 

* "`If Botticelli were alive today he`'d be working for Vogue.`" -- https://en.wikiquote.org/wiki/Peter_Ustinov[Peter Ustinov]
* https://www.shlomifish.org/humour/image-macros/indiv-nodes/if_ayn_rand_was_born_in_the_1990s.xhtml[If Ayn Rand was born in the 1990s, she would be Christina Grimmie.]
* https://www.shlomifish.org/humour/image-macros/indiv-nodes/pbride_philosophers.xhtml["`Have you heard of Plato? Aristotle? Socrates? Models!!`"]

Saladin was slain by https://en.wikipedia.org/wiki/Richard_I_of_England[Richard I "The
Lion Heart"] / https://en.wikipedia.org/wiki/Friar_Tuck[Friar Tuck] / https://en.wikipedia.org/wiki/Robin_Hood[Robin Hood].
However, beforehand, Saladin de-hellholed Palestine except for parts of https://en.wikipedia.org/wiki/Israeli_coastal_plain[the coastal
plain] and his echoes begot some vampires, including Genghis Khan's direct-male-ancestor. 

[[hell-hole]]
== "Hell hole":

A person born in a hell hole started his/her life as a false prophet.
If either parent was a true prophet, then they did everything in their power for their children to be born outside of a hell hole.
As a result, false prophets were usually born to two false prophet parents. 

After the false prophet "master vampire" was slain by a foreign false prophet, the non-capital outskirts of his birthplace region, stopped being a hellhole.
One more time and the mystical capital was liberated. 

When a liberation happened, the universe link:#forking-and-merging[was forked] into a parent and a child universes. 

Female vampires, above puberty, preferred to mate with any of the local post-puberty male vampires based on their competence points.
Their echoes gave birth to boy+girl twin vampires (where one of them was often sent forward in time). Often one of the children ended up slaying either or both parents.
Moreover, parent vampires sometimes mated with their vampire biological children. 

If a vampire wasn't slain before they hit puberty, then he/she endured more hardships such as https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#fox-in-the-hens-coop[being imprisoned] (in a psychiatric ward/etc.). I think puberty is 13 y.o.
for women and men. 

[[zionism]]
== "Ziyoonism":

"Ziyoonism" is non-coincidentally cognate with "Ziyun", the Hebrew word for a https://explainxkcd.com/wiki/index.php/540:_Base_System[4th base] "fuck". It was a process by which the Satans tried to convince false prophets men and women to relocate to an active hellhole for giving birth there (e.g: because the current hell hole was plugged). It was not limited to Israel/Palestine or to people identifying themselves as Jews. 

https://en.wikipedia.org/wiki/Ovadia_Yosef[The Rav Ovadia Yosef] is a true prophet Jew who has a policy of blessing anyone as a Jew.
He also has yet to answer 'no' to the question "is [insert entity here] a pure Jew?". Note that the word "rav", which means "great" in archaic Hebrew, means both "proliferous" and "argumentative" in Modern Hebrew. footnote:[A similar strategy was employed by
the USA ("give me your tired, your poor, your huddled masses"),
by Christianity, and by Islam. I also suspect Saladin's military
accepted many faux Kurds.]

One vampire was "The Witch of Harrow" who ended up establishing https://en.wikipedia.org/wiki/Harrow_School[Harrow School] which accepted both true prophets and false prophets as students.
She ended up being slain around 1977 and liberating Harrow.
Her link:#ramatavivgimel[Ramat Aviv Gimel] house became https://www.shlomifish.org/humour/Selina-Mandrake/indiv-nodes/selinas-18s-birthday-party.xhtml["The Amber"] and was described by my friend Amit as a "gigantic bag of devouring" (due to the tendency of somewhat-important physical items, such as old-school computer games' items, to disappear there). 

As a false prophet child, https://www.shlomifish.org/meta/FAQ/where_are_you_from.xhtml[my
template was relocated] three times before he was 6, despite common wisdom that one should not relocate young children.
This was probably due to the effects of The Muppet Show and other television series on the Terran hellholes and my parents' wishes to have more children. 

[[history-lesson-about-the-muppeteers]]
== History Lesson: The Muppeteers

[[the-early-muppeteers]]
=== The Early Muppeteers: Rockville, Maryland, 1969

While https://en.wikipedia.org/wiki/The_Muppets[The
Muppets Franchise] has been a labour of love by many vampires and wizards, by 1969, it was accepted that there were three head Muppeteers ( pun intended with https://en.wikipedia.org/wiki/The_Three_Musketeers["The Three Musketeers"] ): 

. https://www.shlomifish.org/meta/nav-blocks/blocks/#self_ref_nav_block[Arnold Alois "Arnie" Schwarzenegger], a vampire, was a professional athlete and a self-described amateur/hobbyist philosopher and comedian. 
+
As an assistant kindergartener ( https://en.wikipedia.org/wiki/Kindergarten_Cop[Reference: "`Kindergarten Cop`"] ), Schwarzenegger pushed his true prophet pupils to unnatural athletic *and* academic extremes by being a https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/hollywood_screenplay_format.xhtml[pedantic critic] (so-called "`nazi`"). E.g.: even though they painted with https://en.wikipedia.org/wiki/Crayola[Crayola crayons] works that rivaled classical oil paintings, he was still able-to-find many legitimate faults in them.
The true-prophet children appreciated his input, but he believed they and their parents kept becoming offended and complaining. 
+
I think Jim Henson eventually persuaded him to avoid trying to put the children on a strict high-protein / low-fat diet.
I suspect such diet, is now regarded as both unhelpful and often detrimental for athletes, even professional ones, given it makes its practicioners miserable.
If you are a terran human wizard hacker in the Selinaverse, then as long as you eat enough "carnivorous" protein, which never involved murdering living animals, you can eat what you want, when you want it (within reason) and still become physically-fitter.
References: https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#amateurs-in-sports["`Geeks in sports`"]. 
. https://en.wikipedia.org/wiki/Richard_Stallman[Richard Matthew "RMS" Stallman], a wizard-born, was an overly pedantic "nazi" critic too, but unathletic, unkempt, a maths/software wiz, and a bookworm brainiac. Given he was an atrocious slacker, none of his false-prophet friends understood how he got his Ph.D. (and from MIT no less). 
+
Despite being of (secular) Jewish upbringing, RMS was a https://www.shlomifish.org/meta/FAQ/religious_belief.xhtml[pluralist] ("rich"-ard). 
+
Given he was a wizard, Stallman was aware that Schwarzenegger, Henson, and the other vampire Muppeteers perceived mutated terrestrial hell realities. 
. https://en.wikipedia.org/wiki/Jim_Henson[Jim Henson] - "Jim" means "`laborious`" (not unlike "`gym`") and he did almost everything "`hard`": worked, socialised, learned, taught, entertained, volunteered, and exercised. 
+
"`Jim`" is also cognate with https://en.wikipedia.org/wiki/Jinn["jinn" (or "genie")], and he had a penchant for stage magic and video editing. 
+
As his last name implies, he believed he lived with his single-parent mother, in a relatively-small house-or-apartment in Rockville. 
+
Henson was the leader, and had the veto. 

I believe all three were larger than life, even then.
It is a testament to Selinaverse-an technology that I, a https://www.shlomifish.org/me/business-card/["humorist, writer, and software geek"] (or a "`blogger`" or a "`web monkey`"), am somehow comparable to them. 

One day in 1969, the three lamented the fact that the late 1960s`' Anglophone link:#terrestrial[terrestrial] television has become too paranoid, and so decided that they will act, produce, and distribute, a *gratis, public domain, and non-commercial* television show for children, called https://en.wikipedia.org/wiki/Sesame_Street[Sesame Street].
Part of the reason for keeping it free was that they intended it to sport a lot of https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/[fan-fiction, RPF, fan-art, and song covers] , which they believed were legally problematic.
It was also due to https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/open_free_share_steal.xhtml[an
altruistic spirit of sharing]. 

They expected __Sesame Street__'s popularity to be mostly confined to their base-town, https://en.wikipedia.org/wiki/Rockville,_Maryland[Rockville, Maryland], but thought that https://www.shlomifish.org/humour/fortunes/show.cgi?id=mishnah--saving-one-soul[ They who saved one soul has essentially saved the world Entire ]. 

Little did they realise that _Sesame Street_ and its international spinoff https://en.wikipedia.org/wiki/The_Muppet_Show[The Muppet Show] were remastered and widely televised.
Moreover, despite being ostensibly public domain, it was an incredibly profitable and influential franchise. 

Here's another fun fact: the vampires Muppeteers have left the premises of their base-town, https://en.wikipedia.org/wiki/Rockville,_Maryland[Rockville] (a link:#zionism[Ziyoonist hell-hole] ), very rarely. 

[[how-the-muppets-were-remastered]]
=== How the Muppets' Franchise was Remastered

. The setting of Sesame Street was changed from Rockville to New York City. 
. https://muppet.fandom.com/wiki/Ernie[Ernie] was originally link:#Arnold_Schwarzenegger["Arnie"]. 
. https://muppet.fandom.com/wiki/Twiddlebugs[The Twiddlebugs] were originally smurfs. 
. I suspect Sesame Street was a 20 minutes`' segment originally, and The Muppet Show was 10 minutes. 


[[dispelling-ziyoonism]]
=== Dispelling Ziyoonism and The Muppeteers

By 1982, the previously mighty link:#zionism[provincial-Earth Ziyoonist empire] was reduced to one remaining physical hellhole: https://en.wikipedia.org/wiki/Rockville,_Maryland[Rockville, Maryland].
Its almost undisputed master vampire was link:#Jim_Henson[Jim Henson], head of The Muppeteers.
All the remaining post-puberty vampires (including Queen Elizabeth II and Pope John Paul II) relocated to Rockville to become muppeteers and have their echoes mate with echoes of ones.
Many of the pre-pubecent ones were physically scattered around the globe to delay slaying one another and the Muppeteers. 

The NSA had moved its headquarters to https://en.wikipedia.org/wiki/Fort_Meade[Fort Meade], which is https://www.distance-cities.com/distance-rockville-md-to-fort-george-g-meade-md[about 40 kilometres] away from Rockville.
Rockville also housed the https://en.wikipedia.org/wiki/National_Institutes_of_Health[National Institutes of Health ( NIH )]. 

The fuckers determined that Jim Henson is going to be the last-standing-vampire of "the provincial-Earth Ziyoonism age". https://en.wikipedia.org/wiki/Joss_Whedon[Joss Whedon] asked the orcs "what's next?" and they settled on using the international postal service to connect between the Muppeteers (except for Henson who was kept out of the loop) and "dispellers" outside Rockville.
("You can more easily control television and computer networks but not the Postal service as easily.") footnote:[In a sense, static web sites, including
shlomifish.org,
joelonsoftware.com,
paulgraham.com,
xkcd,
and Ozy and Millie,
were the "Web 2.0" parallel to the Postal Service of 1982.
( Reference )] These dispellers were: 

. Vampires. 
. Female. 
. Below 12 or 13 years old (so below puberty). 
. Above 4 years old or 5 years old or so, so false prophets can credibly believe they can read and write coherently. 
. Located at the USA or the British Isles. 

Some dispellers I can readily recall are: 

. https://www.shlomifish.org/philosophy/fan-pages/samantha-smith/[Samantha Smith] 1972-born so ~10 years old. Hailing from Maine, church-going, and writing her letters by hand. Humble, conscientious, timid [= careful but making steady progress despite feeling fear]. 
. https://en.wikipedia.org/wiki/Melissa_Joan_Hart[Melissa Joan Hart (MJH)] - the 1976 born "computer wiz girl", who used a dot matrix printer. I think she was living in Florida at the time. 
+
Somewhat selfish, ambitious, rash, hastey, opportunistic, and brave. 
+
(References: https://www.shlomifish.org/humour/fortunes/show.cgi?id=shlomif-story-of-Gul-Dukat-in-the-Selinaverse[Ambassador Hart] ; https://www.shlomifish.org/humour/fortunes/show.cgi?id=shlomif-story-it-doesnt-take-a-witch-to-fix-this-computer["`It doesn't take a witch to fix this computer...`"]) 
. https://www.shlomifish.org/humour/bits/facts/Clarissa/[Clarissa Darling] - likely 1974-1976-born. A "`The Theory of Everything`" brainiac. Clarissa avoids physical peril and discomfort as much as possible, while delighting in nonviolent battles of wits. She likes to flaunt her knowledge, and unverified hypotheses. 
+
( https://www.shlomifish.org/humour/fortunes/show.cgi?id=clarissa-darling[Reference #1] ) 
. https://www.shlomifish.org/meta/FAQ/biggest_celeb_crush.xhtml[Sarah Michelle Gellar (SMG)] - as a 1977-born Jewish girl, Sarah believed that her father abandoned her mother and herself, who were both living in relative poverty in Manhattan. She spent just enough time on her scholastic responsibilities to will have graduated from high school and get her mother's echo off her back, and spent the rest of her time https://www.shlomifish.org/humour/fortunes/show.cgi?id=smg-about-giving-back-money-and-time[happily donating] love, time, and money to others and herself. 
+
Kind, yet domineering and "pushy", and believes https://www.shlomifish.org/humour/Summerschool-at-the-NSA/indiv-nodes/we_are_scheming.xhtml[planning
and having backup plans] are good ideas. 
. https://www.shlomifish.org/humour/Terminator/Liberation/indiv-nodes/hamlet-parody-Cher-parody.xhtml[Cher [ Horowitz? ]] - born 1971-1978. Hailing from Beverly Hills, Cher was a https://tvtropes.org/pmwiki/pmwiki.php/Main/JewishAmericanPrincess[Jewish American Princess], and a self-conscious and "`damn proud of it`" one. Only with a heart of gold. She spent large amounts of time (and significant amounts of money), helping her friends or trying to make link:#love-and-knowledge[them happier / more entertained]. 
+
Cher was a 20th-century take [and a direct-female-descendent] of https://en.wikipedia.org/wiki/Queen_of_Sheba[the
Queen-of-Sheba], and both were notorious for their generousity, flaunting their wealth, and frivolousness.
Cher organised many parties and other social events, and given she accumulated a lot of "stuff", and clothes, she usually agreed to give them away on the spot. 
. *Selina [ Hope ] Jones->Mandrake* - a 1977-1978-born girl, likely living in Britain. Became the youngest dropout. Christened "`Selena`", she was so annoyed by thinking that the fellow Greek kids pronounced her name as "`Séléna`" while Israeli ones pronounced it "`right`" that she: [1] changed its spelling [2] developed conspiracy hypotheses about how the ancient Greek philosophers (= educators / entertainers) stole their best ideas from the Israelites and the ancient Jews. 
+
Nicknamed "`Sel`", Selina had a penchant for selling fun services and products to people she knew or just met, often after https://www.youtube.com/watch?v=8iQ7nr8xEPo[haggling] (and often to negative prices). 
+
( https://buffyfanfiction.fandom.com/wiki/Selina_Mandrake[Reference] ) 
. https://www.shlomifish.org/meta/nav-blocks/blocks/#buffy_sect[Buffy (*)] - the real Buffy was a wizard-born girl or woman, who was chosen by Henson to co-slay him, the "`last standing vampire`" of the "`Provincial Earth Ziyoonism`" era. I think she was physically relocated to Maryland, close to Rockville and Fort Meade, to simplify logistics. 

( I think they were all awesome, and I have tried to emulate them all.
) 

You'd think the Postal service would use regular Air Mail to connect them and The Muppeteers to each and every one.
Hah! Not on your life! They used supersonic military jet planes, each carrying Xeroxed copies, dropped from the air and delivered at the doorsteps by motorcyclists.
"`Only the best for the baddest.`" ( https://www.shlomifish.org/humour/So-Who-The-Hell-Is-Qoheleth/ongoing-text.html[Reference] ). The recipients were startled by the aeroplanes' thuds at first, but soon associated the incoming jets with incoming letters. footnote:[The devils ruled against the jets using cross-distance portals, which are
commonly used in non-terrestrial military training.]

I also suspect that, in order to prevent the underage vampires from hitting puberty, there was a "1 week <=> 2 hours" or "1 week <=> 1 day" or "2 weeks <=> 1 day" time slowdown. 

Corresponding with the girls, The vampire Muppeteers soon realised that their crudely produced shows and films were remastered and broadcast internationally ( https://www.shlomifish.org/humour/image-macros/indiv-nodes/mighty_klingon_warriors.xhtml[and beyond!] ). Arnold Schwarzenegger, who was among the three core Muppeteers each understood that the other two were trying to advocate https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/[
Commercial Real Person Fan Fiction (RPFs),
crossovers and parodies] (which were tolerated and encouraged in the non terrestrial universe), as well.
Moreover, they all had https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/#hollywood_screenplay_format[antagonism toward the terrestrial
"Hollywood-blessed screenplay format"] (which was neither popular nor mandated). They also realised they were rich, famous, and that their terrestrial hells "real world"s were lies. 

All the remaining vampires were slain by Jim Henson. 

The dispellers understood the different strategies of each other and the Muppeteers.
Eventually, the dispellers all wrote their own variation of a parodical, fanficcy, screenplay titled https://www.shlomifish.org/meta/nav-blocks/blocks/#buffy_sect[Buffy the Vampire Slayer (BtVS)].
Samantha Smith's copy arrived first, because she wrote it by hand and due to Maine's relative proximity to Rockville.
It described an underage girl who happily slew demons and made them her friends.
It also sported this power quote: 

____
I just slew three mighty https://memory-alpha.fandom.com/wiki/Vulcan[Vulcan] vampire warriors who have watched Sesame Street.
This decade seems-to-be shaping up very nicely so far. 

( https://www.shlomifish.org/humour/Selina-Mandrake/indiv-nodes/selina-and-the-three.xhtml[Reference] ) 
____

The adult Muppeteers and other post-puberty false prophets read the screenplay, smiled/laughed/cried/etc.
and had it directed, produced, and broadcast.
The underage false prophet girls (including the dispellers, the toddler ones, and those living in non-anglophone countries) and underage false prophet boys watched it and ascended as well (including my slayer template who was ~5 years old at the time). 

The two mighty superpowers that Samantha Smith ( &co.
) slew as a child were not the USSR and the USA, but link:#zionism[Provincial Earth Ziyoonism] and The Muppeteers! footnote:[It was not all roses.
See
"hospitalised in a closed psychiatric ward".]

The story of Jim Henson is continued link:#last-standing-vampires[here]. 

[[the-six-chocolate-hearts]]
=== The 6 chocolate hearts

I just bought 6 chocolate hearts ( wrapped with golden wrappings.
) for 5 sheqels.
I have 6 leftover sheqels. 

I intend to pair the hearts and the sheqels, and utilise the pairs like so: 

. link:#Melissa_Joan_Hart[Melissa Joan Hart (MJH)] - consume it - eat it, and maybe throw away the remains. 
. link:#Clarissa_Darling[Clarissa Darling] - auction it. 
. link:#Cher_Horowitz[Cher [ Horowitz? ]] - give it to a friend or a stranger, unconditionally. 
. link:#Sarah_Michelle_Gellar[Sarah Michelle Gellar (SMG)] - give it to my favourite "daughter": protegée, successor, and role model. In my case, she is https://www.shlomifish.org/art/recommendations/music/online-artists/fan-pages/chris-grimmie/[Christina Grimmie]. 
. link:#Real-Selina-Mandrake[Selina Mandrake] - I wish to sell the pair to Christina Grimmie for a negotiable price. (With much fanfare.) 
. link:#Samantha_Smith[Samantha Smith] - decide what to do with it later. 


[[the-terran-terminators--rematch]]
== The Terran Terminators: Rematch

Anyway, the link:#the-devils[devils] and the link:#the-orcs[orcs] approached the men and women who just reached enlightenment, and offered them a choice: they will spend the summer enlightened and together having fun and using their magical powers.
At its end, they can opt to reset their memory banks almost completely and become false prophets again, this time called "Terran Terminators" or continue as enlightened true prophets. 

Several newly-ascended true prophets opted out, after the summer, from various reasons, mostly because they had children or enjoyed their newfound powers . E.g: https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/[Chuck Norris], https://zak.co.il/[Omer Zak], https://en.wikipedia.org/wiki/Elizabeth_II[Queen Elizabeth II], and https://en.wikipedia.org/wiki/%22Weird_Al%22_Yankovic["`Weird
Al`" Yankovic] . They still often "got sucked" into TheGame(TM). I shall call them "the dropouts". 

The ex-slayers spent the summer there creating many crossover memes, stories, hacks, and franchises, or otherwise enjoying magic, life, love/etc.. However, when they met to decide, some of them were still petty / jealous / cruel / "unfaithful" / immature / etc.
Some had years, or decades (or centuries) of history they wanted to get rid of.
So many decided to continue as terminators, possibly by peer pressure. 

Like https://www.shlomifish.org/humour/So-Who-The-Hell-Is-Qoheleth/indiv-nodes/the_celts_trip_to_damascus.xhtml[the
story of the Celtic trio`'s trip to Damascus] some had a policy of not resisting rapekisses or rapehugs during the first few weeks, but there were much less romance and intimacy. 

The youngest dropout was the circa 1977/1978-born link:#Real-Selina-Mandrake[Selina Mandrake].
She decided to continue as a true prophet since "it was the best summer ever" for her, and she may have been scared of losing her memories. 

Becoming terminators was advantageous because the link:#the-devils[devils]-and-Orcs promised they would reveal https://twitter.com/shlomif/status/1403966571215740929[TheOneTruth(TM)] and TheCodex(TM) to the last one standing, but more importantly, all terminators will harbour many new franchises, plots and memes, and creations, and inspire new link:#technology[technologies].
Part of their motivation for becoming terran terminators was that we will "terminate" one another more quickly. 

Note that the devils *might* have link:#forking-and-merging[forked] the Selinaverse universe one last time, including the souls of all wizards, up to and including Selina Mandrake and Jim Henson, and excluding the Terran terminators.
I will refer to the forked universe as "The Shlomifverse", which may or may not be essentially the same as "The Selinaverse". 

In my case, my mind was reset https://www.shlomifish.org/meta/FAQ/how_did_you_learn_english.xhtml[under
the guise of fellow children mocking my use of English].
For many others, it was a concussion from a fall.
Thing is: my https://www.shlomifish.org/meta/FAQ/your_name.xhtml[first name
means "Shalom-ful"] in Hebrew, where "shalom" stems from "completeness".  The link:#the-devils[devils] promised that my body will remain complete and whole. 

These people, starting as false prophets, became known as The Terran Terminators.
After relinquishing their fears, they have *ascended* so to speak (see https://buffy.fandom.com/wiki/Ascension ). Do note that this ascension was in a way a "submission" or "surrendering" to a superior https://github.com/shlomif/shlomif-tech-diary/blob/master/my-candidates-for-terran-leadership.asciidoc#user-content-slain-by-a-vampire[vampire
or protege]. 

[[terran-terminators-surprise]]
=== A Surprise

According to the rules of Fantastecha(TM): 

. There must be a noble cause, however insignificant, that a link:#hackers[hacker] is willing to die for. 
. For each and every hacker X: neither X's soul, nor X's mind, nor their union can ever perish. 
. A hacker may be required or may opt to change his/her "form": name (and possibly mission in life). 

As a result, new vampire soul+mind combos were allocated and started their lives with the forms of the non-dropout templates.
The latter had to change their names, and became bona-fide true prophets.
Whether relieved or disappointed, they were still alive. 

So my soul+mind were effectively created in September 1983, at the first day of the 1st grade of elementary school with the body of a 6 years old. link:#Arnold_Schwarzenegger[Arnold Schwarzenegger] and others started their terminators' lives as grown-ups. 

[[causes-shlomif-will-die-for]]
=== Causes Shlomi Fish will die for

I, https://www.shlomifish.org/me/contact-me/[Shlomi "Rindolf" Fish], am willing to die if all of these will happen: 

. In order to save Planet Earth of the Selinaverse or the Shlomifverse. 
. In order to make sure that every hacker and hack in Fantastecha(TM) (except maybe me) will remain alive, healthy, and happy. 
. In order to make sure https://www.shlomifish.org/art/recommendations/music/online-artists/fan-pages/chris-grimmie/[Christina Grimmie] is alive, healthy, conscious, kicking, and being awesome. 
. In order to save https://www.shlomifish.org/[shlomifish.org] and its build dependencies from being permanently destroyed or lost. 
. Make a complete past recording of my mind available to all Selinaverse and Shlomifverse hackers (including what I have of TheCodex(TM) so far). 


[[terran-terminators-list]]
=== List

One of the first to ascend was https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/bad_acting_arnie.xhtml[Arnold Schwarzenegger]. 

Other notable Terran terminators might include: 

. https://www.shlomifish.org/meta/FAQ/biggest_celeb_crush.xhtml[Sarah Michelle Gellar (SMG)] - https://www.shlomifish.org/humour/fortunes/show.cgi?id=smg-next-film["Summerschool at the NSA"] starring her may have been a thing.
. https://www.shlomifish.org/meta/nav-blocks/blocks/#xkcd_sect[Summer Glau] - my https://www.shlomifish.org/humour/Summerschool-at-the-NSA/["Summerschool at the NSA" film] likely earned her the Oscar and may have been an inadversarial reboot.
. Likely link:#Melissa_Joan_Hart[Melissa Joan Hart (MJH)] (who ascended before https://en.wikipedia.org/wiki/Clarissa_Explains_It_All[CEIA] and as a result was the https://www.shlomifish.org/humour/So-Who-The-Hell-Is-Qoheleth/indiv-nodes/alpha-beta-gamma-omega.xhtml["beta" female] during the https://websitebuilders.com/how-to/glossary/web1/[Web 1.0 period] when SMG was "queen of the Web" and the "alpha female")
. Likely link:#Samantha_Smith[Samantha Smith] herself
. Likely https://en.wikipedia.org/wiki/J._K._Rowling[J. K. Rowling]
. Likely https://en.wikipedia.org/wiki/DJ_Jazzy_Jeff[Jazz] from https://en.wikipedia.org/wiki/The_Fresh_Prince_of_Bel-Air[ The Fresh Prince of Bel-Air ]
. Likely https://en.wikipedia.org/wiki/Paris_Hilton[Paris Hilton]
. Likely https://en.wikipedia.org/wiki/Kim_Kardashian[Kim Kardashian]
. Likely https://en.wikipedia.org/wiki/Dana_Simpson[D. C. Simpson]
. Likely https://en.wikiquote.org/wiki/Linus_Torvalds[Linus Torvalds]
. Likely link:#Richard_Stallman[Richard Stallman ("RMS")]
. Likely https://en.wikipedia.org/wiki/Joel_Spolsky[Joel Spolsky] ( https://www.shlomifish.org/humour/fortunes/joel-on-software.html["Joel on Software"] )
. Likely https://www.shlomifish.org/humour/fortunes/paul-graham.html[Paul Graham]
. Likely https://en.wikipedia.org/wiki/Jennifer_Lopez[Jennifer Lopez]
. Likely https://en.wikipedia.org/wiki/Jay-Z[Jay-Z]
. Likely https://en.wikipedia.org/wiki/Meredith_Brooks[Meredith Brooks]
. Likely Steve from https://en.wikipedia.org/wiki/Smash_Mouth[Smash Mouth]
. Likely https://en.wikipedia.org/wiki/Wil_Wheaton[Wil Wheaton]
. Likely https://en.wikipedia.org/wiki/Pope_John_Paul_II[Pope John Paul II] and https://www.shlomifish.org/philosophy/philosophy/putting-all-cards-on-the-table-2013/#departing_pope_about_twitter[Pope Benedict XVI]. They both had to retire as popes following their ascensions/Catharses due to the Catholic Church's policy of its vampire popes retiring as soon as they ascend. 
. Likely https://www.youtube.com/watch?v=T6wbugWrfLU[Celine Dion]
. Likely https://en.wikipedia.org/wiki/Scatman_John[Scatman John]
. Likely https://en.wikipedia.org/wiki/Felicia_Day[Felicia Day] - 
. Likely https://en.wikipedia.org/wiki/K%27naan[K'naan]
. Likely https://en.wikipedia.org/wiki/Des%27ree[Des'ree] - 
. Likely link:#Clarissa_Darling[The real Clarissa Darling] - 
. My middle sister
. Some childhood friends of mine.
. Likely https://twitter.com/shlomif/status/1477303776495210498[Mom Cimorelli]
. https://www.shlomifish.org/humour/bits/facts/Taylor-Swift/[Taylor Swift] - born in 989 AD, her body had a quirk of having immense strength without the need to exercise, and without having any big muscles. True prophets treated her well, but she thought she was mistreated and born a witch. At 1982 She wanted to forget her past, and start anew as a terminator, whom the satans promised would have average starting strength but could retain her strength, dexterity, flexibility, agility, etc. without too much exercise (like true prophets and unlike many false prophets). Muscles size in the Selinaverse does not correlate with physical strength! 
+
Genetically speaking, Taylor and Saladin parented a son who was Genghis Khan's direct-male-ancestor. 
+
Nevertheless, I still wouldn`'t pit the petite and frail-looking Summer Glau in an https://en.wikipedia.org/wiki/Mixed_martial_arts[MMA] match against https://memory-alpha.fandom.com/wiki/Worf[Worf] or even against https://en.wikipedia.org/wiki/Ronda_Rousey[Ronda Rousey].
However, do note that Glau has won most such fights against both Chuck Norris, and Bruce Lee, who are both alive and in their prime. https://www.shlomifish.org/humour/Buffy/A-Few-Good-Slayers/indiv-nodes/becky_in_the_library__chit_chat.xhtml[She
still drops out of MMA tournaments early.].
Life is a circular graph: link:#self-ref[Reference]
+
The fact that Taylor turned 1,000 y.o.
in 1989, which is the maximal age for Catharsis, may have contributed to the rapid advancement of terrestrial technology in the 19th-20th centuries.
Note that in Taylor`'s hell-world, old-age, menopause, and menstruation (= "period") did not exist. 

Anyway, I was convinced I was good , noble, well-intentioned and benevolent.
I refused to permanently consider the opposite! Even if it meant the whole media of mine and "mainstream" terrestrial science were wrong.
Moreover, similarly to Jesus, I have been willing to suffer a little more if it meant that future generations will suffer much less. 

I also preferred to err on naivity than on cynicism, and https://www.shlomifish.org/humour/stories/#intro[encouraged everyone and everything to improve]. 

t may also have helped that I have been seld-centred, narcissistic, and meglomaniacal. 

[[why-shlomif-became-a-terminator]]
=== Why my template made me a terran terminator

I suspect Shlomi Fish decided to become a terran terminator from the following reasons: 

* Angry at himself for having been a slut. 
* He was frustrated that his bad predictions didn't materialise, either because they were unfounded, or because https://www.youtube.com/watch?v=3gxvMi6yekg&lc=UgzNA_q8Po6cXM0cN_14AaABAg[they were taken as constructive, precautious, advice]. 
+
Like a https://twitter.com/shlomif/status/1539990565873393665[timid
little fish exploring the Ocean] he was afraid of deviations from the status quo.
I think he said "I'm gonna hate this day! [insert reason here]" several times. 
* link:#Real-Selina-Mandrake[Selina], who is younger than him, stubbornly insisted that she'll be a dropout. As a result, that universe could not be named after him/me. 

If my template had not been cynical/pessimstic, I would not have been a terminator.
However, his last-day decision to make me (and him) optimistic/life-loving/human-loving likely contributed to me not getting terminated earlier. footnote:[Despite his many faults, he was the favourite of some wizard hackers, notably
Worf's.]

[[who-created-time]]
== Who created time

A popular theory is that https://memory-alpha.fandom.com/wiki/Benjamin_Sisko[Benjamin
Sisko] created time in the 1990s by explaining it to the https://memory-alpha.fandom.com/wiki/Prophet[Prophets of the
wormhole].
Quark and Brunt made it part of their bestselling ebook/paperbook "Distilled Wisdom of the Prophets for Profits" which they sent 'back in time' out of mischief. 

A theory I made up now is that https://mlp.fandom.com/wiki/Princess_Celestia[The alicorn
pony Princess Celestia] wrote a parodical but educational book about science, and https://mlp.fandom.com/wiki/Discord[Discord] sent it back. 

In Fantastechat(TM), there are many link:#self-ref[strange
loops] and "plagiarism" is common and encouraged. 

[[boredom]]
== Boredom and Lethargy:

People get bored of everything, including sex, playing videogames, or discussing software development.
They also need change ( 'lethargy' ). But boredom and lethargy are powerful motivators - for false prophets and true prophets alike. 

There are many true stories of stay-at-home "losers" who picked a hobby out of boredom, and became creative superstars.
Many predate the Internet, e.g.: https://en.wikipedia.org/wiki/Jules_Verne[Jules Verne], and https://en.wikipedia.org/wiki/E._Nesbit[E. Nesbit]. 

Also see: https://www.youtube.com/watch?v=LKPwKFigF8U["Why boredom is good for you?"]. 

[[ramatavivgimel]]
== Ramat Aviv Gimel

Before having our memories reset, my friend Amit Steinberg, I, and several other future terminators carried with us the "nazi"-ness value: 
**____The "nazi"-ness value:**https://mygeekwisdom.com/2011/09/12/be-excellent-to-each-other/[The Golden Rule] implies sincerely criticising others even if it hurts their feelings, gets you in trouble, and even if you do not practice what you preach (see https://en.wikipedia.org/wiki/Tu_quoque[Ad hominem Tu quoque]) 
____

See http://shlomifishswiki.branchable.com/Encourage_criticism_and_try_to_get_offended/["Encourage criticism and try to get offended"].
From humanitarian reasons, there were attempts to terminate underage terminators before they turned 13 years-old calendarically.
However the 1977-born Amit terminated link:#Arnold_Schwarzenegger[Arnold Schwarzenegger], link:#Melissa_Joan_Hart[Melissa Joan Hart (MJH)], and link:#Samantha_Smith[Samantha Smith].
The two of us were afterward kept in the same elementary school classroom with few other false prophets.
This is given the "Age of the Terran Terminators" was supposed to last 40 years. link:#Clarissa_Darling[Clarissa Darling] likely was terminated shortly afterwards. 

Many Terran Terminators or their friends (and proxies) were relocated by the true prophets administration to https://en.wikipedia.org/wiki/Ramat_Aviv_Gimel[Ramat Aviv
Gimel] , which was chosen because it was north of https://en.wikipedia.org/wiki/Yarkon_River[the Yarkon River] and so outside the historical https://en.wikipedia.org/wiki/Gush_Dan[Gush Dan], which remained a hellhole for longer, and yet close enough to Tel Aviv, the "it city" of Israel.
It was also close enough to the sea, to accommodate for terminators of sea-farers descent. footnote:[Alexander the Great liberated northern Tel Aviv [minus the tau.ac.il campus which would be liberated by Saladin] on his way to Gaza and Egypt, which caused the Yarkon and Ayalon streams to spring-up giving Gush-Dan a Mordor-like geography]

Placing them together was useful for cross-pollination, getting terminated, and terminating. 

By 1989-1990, when link:#shlomif-watchers-and-whichers[Melissa Joan Hart (MJH)] became my project manager, and https://www.shlomifish.org/me/rindolf/[Rindolf] my whicher, almost all observers believed either Amit or I were likely going to terminate all other terminators.
I suspect they were right.
Amit (= "colleague" in modern Hebrew or "friend" in archaic Hebrew) was more sociable and outgoing at first, but I suspect I terminated him during the 7th->9th grade, before he and his family relocated to https://en.wikipedia.org/wiki/Neve_Avivim[Neve Avivim]

Do note that despite the geek stereotype, I haven't been shy, just prone to stuttering, bad diction, and awkwardness. 

I joked that, similar to https://hoover.blogs.archives.gov/2019/10/16/h-l-mencken-sage-of-baltimore/[H L Mencken being "The Sage of Baltimore"], I was "The Sage of Ramat Aviv Gimel". 

My terminating-career was boosted after https://www.shlomifish.org/meta/FAQ/#site_history[I
set up a static personal website] which became https://www.shlomifish.org/[www.shlomifish.org].
The devils promised it will be displayed verbatim among other terminators.
Various Internet people told me I https://www.shlomifish.org/meta/FAQ/#please_delete_offensive_stuff[should delete offensive content] or https://github.com/shlomif/shlomif-tech-diary/blob/master/static-site-generators--despair.md#facing-some-criticism[convert
the service to use PHP/Ruby-on-Rails/etc.], but I didn`'t heed them.
They were likely mirages of the devils. 

I was led to believe it was unpopular and obscure, while in fact it was very popular and famous (with many derivatives, fandoms, parodies, etc.) outside my mind`'s hell.
I was also often made to think I had many haters, which wasn`'t true. 

Do note that "Encourage criticism and try to get offended" was not the last word: 

. https://github.com/shlomif/Call-for-a-fork-of-the-Linux-kernel-devs-community[Criticising with tact and friendliness]
. http://shlomifishswiki.branchable.com/Never_Try_to_Please_Everyone/["Don't try to please everyone" ; "colour of the bikeshed" ; etc.]


[[history-of-earth]]
== History of Earth:

[[ancient-history-of-earth]]
=== Ancient History of Earth:

When Earth became the last frontier of link:#zionism[Ziyoonism], it was negotiated that there would be: 



* 1 pair of "Elohim" / "אלוהים" and "Jehovah" / "יהוה" (E, J; א, י). 
* 3 pairs managing sanctuaries: 
+
.. Se'or (שעור) and https://www.shlomifish.org/humour/Star-Trek/We-the-Living-Dead/ongoing-text.html[The Symbul (תה סימבול)] managing https://en.wikipedia.org/wiki/Golan_Heights[the Golan Heights or the 'Steppe'] (S, T; ש, ת). 
.. Alaska (L, K; כ, ל). 
.. Panama (M, N; מ, נ). 
* 7 pairs of seas / Oceans - farers vampires: "The seven seas". 
* 9 men and 9 women who started as land link:#the-game[vampires]. 

( See http://tolkiengateway.net/wiki/Rings_of_Power[the Middle Earth's
"Rings of Power"] meme.
) 

(1 + 3 + 9) × 2 = 26 => corresponding with the letters of https://en.wikipedia.org/wiki/English_alphabet[the Latin/English alphabet]. 

(1 + 3 + 7) × 2 = 22 => corresponding with the letters of the https://en.wikipedia.org/wiki/Hebrew_alphabet[Hebrew alphabet]. 

After Syria (minus Damascus itself) in the Levant was liberated to being a true prophets zone (by Mosheh / Aharon / Jehovah slaying https://en.wikipedia.org/wiki/Tukulti-Ninurta_I[Nimrod] ?), TheGame(TM) splintered the Terran countries further. 

England was split into many shires and the contiguous USA into 48 states.
I also suspect Africa used to be one big country, and so was the USSR (with Russia a large province, with St.
Petersburg as its mystical capital). 

The mystical capitals of all countries except Syria were splintered too. 

An extra complication may have been that a liberator of a province must have originated from a different country. 

Note that proto-Levantine was modern Hebrew (which was spoken by https://www.shlomifish.org/humour/Star-Trek/We-the-Living-Dead/indiv-nodes/Q_home_planet.xhtml[the
Énglishtants over 6 milliard years ago]) and Modern English is also a product of TheGame(TM). 

https://en.wikipedia.org/wiki/California[California ( .ca.us )] became the 1st province to be liberated. 

Jerusalem was the 1st [national] mystical centre to ascend when https://en.wikipedia.org/wiki/Solomon[King Shlomo
("Solomon")] wanted to be benevolent and "know the gods". David and his genetic sons were redheaded, while Shlomo had black, curly hair.
He became king by telling well-intentioned jokes and tall tales about David, and Shlomo's older siblings-in-pretence (e.g: https://en.wikipedia.org/wiki/Tamar_(daughter_of_David)["Amnon and
Tamar"] or https://en.wikipedia.org/wiki/Absalom["Avshalom"]). Not unlike https://www.shlomifish.org/humour/[my fanfics/RPFs].
David and his sons agreed he would be a better king and crowned him, while remaining physically alive and loyally serving under Shlomo`'s reign, thus undergoing https://en.wikipedia.org/wiki/Catharsis[Catharsis] and liberating Jerusalem. footnote:[Note that in the Selinaverse, Vedek Winn
became a Kai by employing a similar strategy. The rule that you should not use
the same trick twice is just a guideline: Reference: "`taking guidelines as dogma`". Also note that:]

The first country to be completely liberated was Greece, which was a team effort of many false prophets and their players. 

I contemplated that Damascus was finally liberated after the author of the scroll of https://en.wikipedia.org/wiki/Ecclesiastes["Qoheleth" (+++=+++ Ecclesiastes)], who was its "master vampire" https://www.shlomifish.org/humour/So-Who-The-Hell-Is-Qoheleth/ongoing-text.html[admitted
inferiority] to a female Celtic vampire traveller from Austria. 

[[history-of-earth-taylor]]
=== Taylor the Provincial Earth Ziyoonism Slayer

In 989 A.D., a female vampire christened "`Tailor`" was born.
She changed her name to "`Taylor`". In her hell world: 

. https://en.wikipedia.org/wiki/Old_age[Old age] was not necessary. 
. https://en.wikipedia.org/wiki/Menstruation[Menstruation ("`period`")] did not exist. 
. https://en.wikipedia.org/wiki/Menopause[Menopause] - when female humans stop becoming fertile - did not exist (it indeed does not amongwizard hackers). 
. Near-instanteneous, cross-distance, travel was not yet possible, and Taylor believed it was not reasonable and scientific to assume it will be. (It is, in fact, possible.) 

One complication was that in the Selinaverse, Taylor kept slaying her partners for vampire tournaments.
TheCodex(TM) of TheGame(TM) of Fantastecha(TM) requires that a vampire will be slain by his 1,000 year birthday.
As a result, as 1989 A.D.
loomed closer, link:#the-devils[theGamers(TM)] enabled faster and more advanced terresterial travel and communications mechanisms.
This culminated in jet aeroplanes (e.g: https://en.wikipedia.org/wiki/Boeing_747[Boeing 747] ), the international https://en.wikipedia.org/wiki/Television[Television] infrastructure of the 1970s, and the early digital computer networks ( e.g: https://en.wikipedia.org/wiki/ARPANET[ARPANET] ). 

If Taylor (or any other past-puberty female vampire), was pitted against a different female vampire, or a pre-puberty (below 13 years old) male vampire, then they were slain without the need for Taylor and them to beget a new pair of male-and-female vampires.
I think TheCodex(TM) requires that after a certain stage, each birth of 2 vampires like that will be followed by 3-or-more vampires getting slain. 

[[world-war-2]]
=== World War II

I suspect Adolf Hitler and the other Third Reich Nazis were link:#love-and-knowledge[amateur entertainers / philosophers / comedians].
They were only sadistic, murderous, authoritarian, and villainous in the collective awareness of some vampires (including me and some of my ancestors). After they were slain (by Stalin?), Hitler&co were shocked by their remastered link:#terrestrial[terrestrial] version.
However, they received part of the profits from that, and took it to their advantage. 

Moreover, the Nazi Germans' "death camps" / "concentration camps" infrastructure ( e.g: https://en.wikipedia.org/wiki/Auschwitz_concentration_camp[Auschwitz] ) have magically materialised in Poland as pseudo-evidence for the holocaust when the Polish provinces were liberated.
This was not unlike link:#magic[the Egyptian and Mesoamerican pyramids]. 

I think Hitler not only discouraged blindly following superior orders, but encouraged https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#big-minded-vs-small-minded[a "Rosh Gadol" attitude] of taking initiative and performing tasks as well as possible (or outright refusing orders if they seem unattainable). Moreover, "Mein Kampf" in idiomatic modern German, does not mean "my war", but rather "my struggle", and I suspect that the original version was shorter, and more entertaining, than the terresterial version.
Moreover, Hitler wrote most of his later essays in English. 

WWII was an orchestration of a massive multiple-vampire slaying tournament.
TheGamers determined that most vampires who took part there would be slain by Hitler, but he in turn would be slain by Aharon Fish.
Aharon Fish is/was my genetic father's genetic father, whom I was led believe was an obscure Polish->Israeli (and secularly Jewish) old man living in Tel Aviv who used to be a Print/Press operator.
I suspect the Satans required his letters to Hitler during his plight from the German military (through the USSR and Iran), to not be delivered by air, but by land travel alone, for them to be preserved. 

[[colonialism]]
=== Colonialism

Colonialism was some attempts by vampires to get slain: 

. https://www.youtube.com/watch?v=p-fRo5-p9hE[Monty Python's Life of Brian - "`What Have The Romans Ever Done For Us?`"]


[[christian-crusaders]]
=== The Christian Crusaders

The Christian crusaders (during Saladin's time/etc.) were not really malevolent or destructive - only perceived this way by the media (communications' "in-betweens") of some vampires (including Saladin's link:#slayer-watcher-whicher[slayer], Yusuf) - often 2nd-hand ones.
Furthermore, given the circular-graph nature of melee fighting, many of the wizard crusaders could win over Yusuf in a 1-on-1 sword fight, but played along with the terrestrial version. 

[[liberating-africa]]
=== Liberating Africa

Given Africa was considered one big country by TheGame(TM), https://en.wikipedia.org/wiki/Necho_II[Necho II]'s expedition to encircle Africa had one slayer vampire from the Levant (e.g: Lebanon, Israel, or Damascus) on every ship, in order to try to liberate the African provinces.
Not only that, but one ship ended up at the Americas. 

https://en.wikipedia.org/wiki/Alexander_the_Great[Alexander the Great] liberated Egypt itself (except for its mystical capital). 

Re https://en.wikipedia.org/wiki/David_Livingstone#Stanley_meeting["Dr.
Livingstone, I presume"], Livingstone was wizard-born, and acted as a watcher to some vampires' adventurers. 

[[ghost-town-pattern]]
=== The Ghost Town Pattern

E.g: Pompei ( https://www.shlomifish.org/humour/humanity/ongoing-text.html#the-town-council[Reference #1] ). **TODO: ADD**

[[inauspicious-names]]
=== inauspicious-names

"Ayin" ("אין") means "there isn't" in Hebrew. 

[[albert-einstein]]
==== Albert Einstein

The Theory of Relativity's proofs were nonsensical, and its conclusions are empirically known to be false. 

[[ayn-rand]]
==== Ayn Rand

I suspect Alisa/Alice "rand" Rosenbaum was/is real and slew https://en.wikipedia.org/wiki/H._L._Mencken[H. L. Mencken] (thus liberating Maryland minus Rockville), https://en.wikipedia.org/wiki/Rudyard_Kipling[Rudyard Kipling], and https://en.wikipedia.org/wiki/Sarah_Bernhardt[Sarah Bernhardt].
She later got slain, thus liberating St.
Petersburg. 

"Ayn Rand" was her terrestrial version. 

[[nVidia]]
==== nVidia

[[Elizabeth-I-and-II]]
=== Queens Elizabeth I and Elizabeth II (of England)

https://en.wikipedia.org/wiki/Elizabeth_I[Queen Elizabeth
I] was not really virginal or chaste just was slain before she was able to conceive vampire children, which made all her genetic children wizard-born. 

https://en.wikipedia.org/wiki/Elizabeth_II[Queen Elizabeth II] was destined by link:#the-devils[theGamers(TM)] to be the last starting-as-a-vampire UK monarch.
As a result, her husband and genetic children were/are wizard-born. 

[[the-schwartz]]
== "The Schwartz is in us":

Re https://spaceballs.fandom.com/wiki/Spaceballs:_The_Wiki[Spaceballs]

I will hopefully fully admit defeat to https://www.shlomifish.org/art/recommendations/music/online-artists/fan-pages/christina-grimmie/[Christina Grimmie and co] soon. 

Nevertheless 'the Schwartz' - both good and evil flows in all of us. 

In https://www.youtube.com/watch?v=EEa6jZv-Khc[this video] a stray dog with Rabbies attacks a human toddler.
Rabbies is a kind of possession/obsession, and friendly pets in the Selinaverse can talk. 

I imagined a themed planet - "Planet of the https://forgottenrealms.fandom.com/wiki/Main_Page[Forgotten
Realms]" - where many 2nd generation organisms take it far too seriously.
Are they false prophets? Many soldiers or even civil employees on Earth exhibit similar symptoms. 

And true prophets are not perfect.
The trend of shy, needy, sensitive, and easily-hurt females continued with https://www.shlomifish.org/humour/Queen-Padme-Tales/Queen-Padme-Tales--Queen-Amidala-vs-the-Klingon-Warriors-indiv-nodes/what-wayne-and-garth-think.xhtml[Tiffany
Alvord and Fluttershy].
Do note that: 

. They both shed some of that along the way. 
. I always loved them. 
. They are not jealous or territorial, but rather kind and generous. 
. I have a tendency to depict them both as real badasses in my fics. (e.g: https://www.shlomifish.org/humour/Terminator/Liberation/indiv-nodes/hannah-using-a-tank.xhtml[here]) 

Recently, listening carefully to some songs made me cry, and that included some upbeat songs such as https://www.youtube.com/watch?v=YtrFsjdeO5I[KHS & co's "Lion King parodical medley"].
Reportedly, many young-looking women who went to listen to https://en.wikipedia.org/wiki/Franz_Liszt[Liszt]'s concerts fainted from excitement (and I believe most of them were true prophets). 

Cimorelli-the-band wrote https://www.youtube.com/watch?v=FktDDKNrWjk[a song titled 'Renegade'] motivated by suggestions they received as up-and-coming signed ("VEVO") artists. 

[[objectivism-and-mysticism]]
== Objectivism-and-Mysticism:

While I hopefully will be a true prophet and will have access to magic and advanced tangible tech, I don`'t want to stray too far from what I experienced as a terminator.
Balance between yin and yang. 

I wish to live on a spherical planet with a 24 hours clock, and https://en.wikipedia.org/wiki/Gregorian_calendar[the Gregorian calendar].
However, there should be no known risk of environmental or astronomical calamities. 

I wish to experience unique taste in every meal of freshly prepared food (maybe also fast food). 

I wish to meet https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/[truly great hackers]: award-winning creators and polymaths. 

I wish mass duplication to be available. 

https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/why-the-so-called-real-world-makes-little-sense/#selinaverse_vision[The Selinaverse vision]

[[elves-vs-orcs]]
== The blurry line between elves and orcs:

In https://www.shlomifish.org/humour/Summerschool-at-the-NSA/[Summerschool at the NSA] , I joke that: 

[quote]
SMG: We`'ve got a lot of time for that.
OK: it was 1997-1998ish, Buffy started airing and became a cult series.
So, one day a group of yeshivah pupils from a local Chabad yeshivah arrived to the studios saying they have some numerological insights from the Jewish bible, about what will happen in Sunnydale next. 

Were they elves or orcs? 

We cannot stop even small children from imagining things - and elsewhere in link:#the-multiverse-of-imagination[Fantastecha(TM)], there will be sucker/brave souls who will choose to start their lives as false prophets.
Furthermore, most good narratives feature one problem or more that need to be reconciled ( Reference: https://www.youtube.com/watch?v=Gl3e-OUnavQ[Sesame Street:
"Conflict"] ). 

Furthermore, I sided with Emma Watson that "your time is everybody`'s time" rather than link:#Melissa_Joan_Hart[Melissa Joan Hart
(MJH)]`'s liberal use of time wraps.
This may have delayed my ascension/catharsis, but made me less ecstatic.
Who was right? 

https://www.shlomifish.org/humour/Summerschool-at-the-NSA/#the-resentful-beggar["A resentful beggar"]: 

____
A resentful beggar whose name I forgot, and who accused the people sitting on benches in Rabin Square of being misers, which prompted me to give him a 20 sheqel note and asking that we`'ll converse in return. 

After talking for a while, I decided to give him 50 more sheqels and he told me he believes I`'ll get lucky because I was so generous.
And a few weeks after that, I attended Olamot Con, and came up with the idea to write Summerschool at the NSA as a screenplay. 
____

It was clearly a test (given my bank credentials and those of many large corporations are public knowledge). 

Moreover, back in the 9th grade, I suffered from several clinical depressions, and eventually my guardian angels decided to send me 'The Neo-Tech Cosmic Power Pincer #1', which was false, but sounded more believable and provided a sharper contrast with my contemporary Israeli, Jewish, and mostly Tanakh idea system. footnote:[I suspect Sheldon
Cooper, whose first name is cognate with mine (= "`Shlomi`"), was in part an exaggerated parody
of me at the time. Like him, I tried to reconcile my contemporary ideology
with terrestrial science and "consumerist"
culture. That was
evident from my contemporary writings, e.g.:]

[[about-sex]]
== Thoughts about Sex:

While risking sounding https://www.shlomifish.org/meta/FAQ/are_you_a_sexist__are_you_a_feminist.xhtml[discriminatory], I suspect that often when a female vampire mated with a male vampire, she thought it was an elaborate night of "up-base" (= 4th base and below) sexual acts, while for him it was a temporary spell of arousal, or even "regular" pleasure, or at most https://www.shlomifish.org/humour/bits/true-stories/my-first-kiss/[a "rape-kiss"]. 

Re: 

* https://www.cliffsnotes.com/literature/a/atlas-shrugged/character-analysis/francisco-danconia[Francisco d`'Anconia] - women (and distinguished, high-society, ones) remembered having affairs with him. 
* https://www.youtube.com/watch?v=Zlot0i3Zykw[Taylor Swift - "Red"] - a song she wrote pre-catharsis, and I match her description. 
* https://en.wikipedia.org/wiki/Sarah_Bernhardt[Sarah Bernhardt] - the daughter of a Jewish prostitute (WTF?) who believed her mother abandoned her. Became a master vampire of part of Paris and after she was slain by Alisa "Rand" Rosenbaum or by Walt Disney, liberated it. 
* link:#Sarah_Michelle_Gellar[Sarah Michelle Gellar (SMG)] - believed pre-catharsis that her biological father divorced her mother. 
* https://en.wikipedia.org/wiki/Alexandre_Dumas[Alexandre Dumas pere] - had 40 affairs. 
* https://en.wikipedia.org/wiki/Solomon[King Shlomo ("Solomon")] - had 700 "`נשים"` (= "wives", "women"), and 300 "`פילגשים`" (= "`mistresses`", "`concubines`"). I think the "wives" were women he was aware that he (at least) kissed, either female vampires (and they begot a pair of male+female vampires), or female wizards who were attracted to him. The 300 "mistresses" were female vampires who mated with him without his knowledge (or often without theirs!). 

Given most organisms wish to link:#love-and-knowledge[experience "pleasure" / "love" / happiness] even if they http://shlomifishswiki.branchable.com/99_Problems/["have 99 problems but a significant other ain`'t one"], then love is unstoppable. 

____
As an example, we can imagine a young girl to write a funny screenplay using https://en.wikipedia.org/wiki/GitHub[GitHub] or Google Docs which pits https://www.shlomifish.org/humour/bits/facts/Emma-Watson/[Emma Watson] vs. https://en.wikipedia.org/wiki/Kim_Kardashian[Kim Kardashian] on who gets to ride https://mlp.fandom.com/wiki/Princess_Celestia[Princess Celestia] next, with https://en.wikipedia.org/wiki/Darth_Vader[Darth Vader] and https://en.wikipedia.org/wiki/Haman[Haman] as two "evil", but mutually hating one another, arbiters.
Might seem ridiculous, but if I didn't want entertainment in my life, then I'd go watch grass grow.
It will be a legal and "ethical" minefield, but I'd bet it'd be easier to follow and more entertaining than https://en.wikipedia.org/wiki/The_Lord_of_the_Rings[Tolkien's "Lord of the Rings"] was even shortly after LotR was written. 

( https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/[Reference #1] ; https://www.shlomifish.org/humour/bits/Who-will-ride-Princess-Celestia/[Reference #2] ) 
____

That proverbial girl is making love to all these meme-generators! 

This has several implications: 

. No one owns 100% of anyone else`'s sex life or love life.
. No one is a virgin.
. Ages are irrelevant: 
** {empty}
+

[quote]
Mosheh: Relax! I married girls who were 40 times my junior or more and my own descendants, and retrospectively I can tell that many of them were more mature and rational than I was in most respects. 
** While in her 20s, https://www.shlomifish.org/humour/fortunes/show.cgi?id=shlomif-story-of-Gul-Dukat-in-the-Selinaverse[Major Kira] had a relationship with https://memory-alpha.fandom.com/wiki/Bareil_Antos[Vedek Bareil] who was/is over a million years old. 
** Moreover, https://stexpanded.fandom.com/wiki/Q2[Q2], who was roughly 34 milliard years old when she assumed a human-like body, had relationships with much younger men. E.g: men in their 20s, who were less than a milliardth her age. 
** https://www.shlomifish.org/meta/FAQ/featuring_sexy_women_and_girls.xhtml["Shlomi Fish`'s FAQ - You feature sexy women and girls in your works. Are you a pervert?"]
. {empty}
+

[quote]
Obi-Wan: I did, yes.
Wow! And I thought my (one and only, hah!) girlfriend was bad.
Do note, however that I kindof am attracted to the bitching type.
One of my many kinks.
While my friends are attracted to everything that moves, I see no reason to limit myself ( https://www.amazon.com/Best-Things-Anybody-Ever-Said/dp/0743235797/ref=sr_1_1[Reference] ). 
. Sex between two consenting wizards often is "making out", and can be done with clothes on and in public. 
. {empty}
+

____
Gowron: Jedi-training programs can reportedly be completed in under a year [ Qui-Gon nods ], and it is a crime to take a relationship with a beautiful warrior such as yourself for granted! You have your needs, for one... 

Padmé: Oh, I have my needs all-right! Only my physical needs are not a problem... 
____
+
One doesn`'t have to be a sex addict, and even if you are, link:#boredom[you will likely grow out of it]. 
. Trans: in the Selinaverse, an organism can expend one mana point to change their DNA and physiology, permanently, but reversibly. So far there are very few takers for a genderchange "operation". 
. In general, men, while being attracted to men, are attracted more to women, and women are attracted more to men. This also applies to men and women, who are either very gentle, or very tough, or both. 
+
Both genders tend to covet https://www.shlomifish.org/humour/Queen-Padme-Tales/Queen-Padme-Tales--Queen-Amidala-vs-the-Klingon-Warriors.html#dedication[competence].
MOTASes are usually flexible enough to https://www.shlomifish.org/humour/Queen-Padme-Tales/Queen-Padme-Tales--The-Fifth-Sith.html[forego
minor imperfections]. 
** {empty}
+

____
SMG: "He is cute, but I`'m looking for man-tastic! You know, someone with a little cushion for the pushin'?" 

-- https://www.youtube.com/watch?v=kCl3ho6_gbg[https://www.youtube.com/watch?v+++=+++kCl3ho6_gbg (Spiderman parody with SMG and Jack Black)]
____
** https://www.shlomifish.org/humour/fortunes/show.cgi?id=shlomif-beauty-products-as-the-stone-soup-effect[Beauty Products as the Placebo Effect]
** ( For example, https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/be_communicative.xhtml[writing and publishing some short poems] and tactfully avoiding a fistfight are attractive. ) 
** https://www.shlomifish.org/humour/fortunes/show.cgi?id=sharp-web--lesbian-straight-and-Sappho[#web - Lesbianism, heterosexuality, and Sappho of Lesbos]
. A wizard of any age can conceive a child or a pet by submitting a web/email/paper/etc. form. 
. At any point, there is a large number of MOTASes who are not in a relationship, but are open for being in one. (References: https://www.breitbart.com/entertainment/2019/12/30/sharon-stone-blocked-from-dating-site-bumble-after-users-thought-her-profile-was-fake/["Sharon Stone Blocked from Dating Site Bumble After Users Thought Her Profile was Fake"]) 
. I suspect that female terrans were excluded from parts of the workforce due to the tendency of vocal minorities out-of-them to constantly complain/"bitch" about trivialities. 
.. https://en.wikipedia.org/wiki/Actor[Female stage actors]
.. https://en.wikipedia.org/wiki/Women_in_the_Israel_Defense_Forces[Women in the Israel Defence Forces ("`IDF`")]


[[forking-and-merging]]
== Forking and Merging

link:#love-and-knowledge[Pleasure and "knowledge"] allows two or more memes or memes generators to spawn new ones, as well as be educated themselves. 

However, using link:#magic[magic] one can duplicate anything while giving the duplicates new souls.
E.g: https://www.shlomifish.org/humour/fortunes/show.cgi?id=sharp-sharp-programming-life-according-to-valentine[Valentine Gellar], or https://memory-alpha.fandom.com/wiki/Thomas_Riker[Thomas Riker].
The devils/orcs used it to fork entire universes. 

Like the https://en.wikipedia.org/wiki/Fork_(system_call)[Unix "`fork()`" system call], wizards' souls in forked universes are aware that they are the "child process". However, vampires' souls didn't have that privilege! 

There are https://www.reddit.com/r/linux/comments/9m8yi7/there_are_forks_of_existing_projects_but_are/[mergers
/ joins] too.
Also note https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/starved_of_employees.xhtml[Microsoft
Windows being merged into GNU, Linux, and WINE].
Do note that the two-or-more original souls remain intact and may reappear in different contexts in the future. 

One can spawn imaginary worlds which share similarities to our own.
E.g: 

. https://buffy.fandom.com/wiki/Buffy_the_Vampire_Slayer_and_Angel[The Buffyverse]
. https://buffyfanfiction.fandom.com/wiki/Beckyverse[The Beckyverse] - https://www.shlomifish.org/meta/FAQ/biggest_celeb_crush.xhtml[Sarah Michelle Gellar (SMG)] was not born, but Summer Glau, Emma Watson, and Shlomi Fish were. 
. https://en.wikipedia.org/wiki/Wizarding_World[Wizarding World] (= link:#terrestrial[Terrestrial] spin on Harry Potter) 
. https://bigbangtheory.fandom.com/wiki/Main_Page[The Big Bang Theory] show. 
. https://en.wikipedia.org/wiki/La_Linea_(TV_series)[La Linea]
. https://en.wikipedia.org/wiki/My_Little_Pony:_Friendship_Is_Magic[My Little Pony: Friendship Is Magic]


[[rationality]]
== "Rationality":

"People" online and in the outside world accuse me of being Manic, delusional, and irrational. http://shlomifishswiki.branchable.com/Importance_of_Having_Doubts/[I`'m not 100% sure I`'m right.]

But why should my world have a monopoly on being the only real world? 

* https://twitter.com/shlomif/status/1482680712964849669["The world is what you make of it"]
* https://en.wikipedia.org/wiki/The_Chronicles_of_Amber[The Chronicles of Amber] - an alternative "real world" to ours 
* https://twitter.com/shlomif/status/1479063972934565893[Shlomi Fish on Twitter:]
+

[quote]
wrt https://www.shlomifish.org/humour/fortunes/show.cgi?id=god-and-his-angels-as-technicians["God
and his angels as implementing humans' perception of the universe"] an #IRC friend joked that the giant world turtle was the most plausible cosmological model.
#mysticism 
* https://twitter.com/shlomif/status/1482399705594318852[Shlomi Fish on Twitter:]
+

[quote]
#BigBangTheory one reason I resented the old Sheldon so much is that he reminded me of my old dogmatic science-ist / atheist too much.
I suspect Penny was the alpha geek: https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/#hacking_and_amateur__vs__conformism_and_professional[https://shlom.in/geekyhackers]
+
My catalyst: https://www.shlomifish.org/meta/FAQ/atheism_can_be_a_religion.xhtml[South Park's creators about Atheism]
* {empty}
+

[quote]
Mr.
Linea ( https://en.wikipedia.org/wiki/La_Linea_%28TV_series%29[La Linea (TV series)] ) is TheCreator.
;) 
+
( -- https://twitter.com/shlomif/status/1485024317062717440[@shlomif Tweet] ) 
* https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/why-the-so-called-real-world-makes-little-sense/[Why the so-called-real-world makes little sense]


[[many-roads]]
== The many roads to competence:

( I`'m speaking in generalisations.
) 

* https://memory-alpha.fandom.com/wiki/Bajoran[The Bajorans] became wizards by interpreting the 'prophecies' of the timeless aliens of the wormhole. 
* The https://memory-alpha.fandom.com/wiki/Klingon[Klingons] became wizards by using metaphors for physical warfare. (e.g: https://www.shlomifish.org/humour/Queen-Padme-Tales/Queen-Padme-Tales--Queen-Amidala-vs-the-Klingon-Warriors.html["Queen Amidala vs. the Klingon Warriors"] ) 
* The https://memory-alpha.fandom.com/wiki/Ferengi[Ferengis] became wizards by advocating greed, trickery - and even deceit. 
* https://starwars.fandom.com/wiki/Yoda[Yoda] became a wizard by advocating self-control, peacefulness, and a Stoic state of mind. 
* https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/guidelines_as_dogma.xhtml[Ezekiel] became a wizard by being a standup comedian. 
* https://en.wikipedia.org/wiki/Felicia_Day[Felicia Day] started as a computer games' addict, which I had been one as well (and she wasn`'t a one-trick-pony). 


[[shlomif-watchers-and-whichers]]
== My watchers and whichers

https://en.wikipedia.org/wiki/Emma_Watson[Emma Charlotte Duerre Watson] (also see https://www.shlomifish.org/meta/nav-blocks/blocks/#harry_potter_nav_block[my fanfics of her]) was born a day after https://www.shlomifish.org/meta/FAQ/biggest_celeb_crush.xhtml[Sarah Michelle Gellar (SMG)]'s 13th birthday.
"Emma" means "complete" in proto-Germanic, not unlike https://www.shlomifish.org/meta/FAQ/your_name.xhtml["Shlomi" [+++=+++ "shalom-ful"]].
"Eymah" means 'terror' in Hebrew, while "Em" means "mother". "Sarah" means "a [female] minister" or "a ruler". "Charlotte" is cognate with both "Sarah" and "Shlomi" and also means "a ruler". 

She was also born in Paris, which was the birthplace of https://en.wikipedia.org/wiki/Sarah_Bernhardt[Sarah Bernhardt], SMG's and mine ancestor. 

So it is likely that she was conceived as a bridge between SMG and me. footnote:[There may have been hopes to get SMG to terminate me before me hitting puberty
on my 13th birthday, 5 May 1990. This is given SMG had already hit puberty on
her 13th birthday, 14 April 1990, and so was "sunken costs".]

The last name "Watson" is cognate with "watcher", and I suspect she is related to https://en.wikipedia.org/wiki/Dr._Watson["Dr. Watson"] from Sherlock Holmes. 

As a watcher, link:#Melissa_Joan_Hart[Melissa Joan Hart (MJH)] was ambitious, and possibly overly so.
She used https://spaceballs.fandom.com/wiki/Dark_Helmet[Dark Helmet from Spaceballs] as an anti-role-model.
Despite her ambition, she disliked micro-managing, and encouraged the hackers on her team to be https://www.joelonsoftware.com/2004/12/06/news-45/["Rosh
Gadol"]. 

However, her liberal use of time wraps and time travel (which likely had been employed by link:#slayer-watcher-whicher[Maimonides] before) earned her the unflattering nickname "World's oldest teenager". (References: https://www.shlomifish.org/humour/fortunes/show.cgi?id=shlomif-story-of-Gul-Dukat-in-the-Selinaverse[Ambassador Hart] ; https://www.shlomifish.org/humour/fortunes/show.cgi?id=shlomif-story-it-doesnt-take-a-witch-to-fix-this-computer["It doesn't take a witch to fix this computer..."]) 

MJH had a string of terminators being cathersysed, so she seemed to have "the golden touch". However, after she began managing me, I ended up terminating Amit instead. 

When Emma Watson volunteered to help manage me and Rindolf, she started as a SysCo (= "system coordinator") and requested 100,000 USD/month as a wage (as a starting point for haggling) and MJH was happy to comply right away.
When news broke about it, Watson was in tears, but MJH told her they saw an increase in donations and that "War is good for business". So she gave Emma a raise, and made her "a vice president in charge of marketing". 

In 1995, Emma Watson and her parents relocated from Paris, to Tel Aviv and Greater London, as by that time, she provided the most income, and her parents were helping her.
This was motivated by the desire to reduce context switches, and because some of the Parisians she talked with were annoyed by her absentmindedly using English and Hebrew paradigms in speech. 

With Emma's help, link:#Sarah_Michelle_Gellar[Sarah Michelle Gellar (SMG)] was terminated by my team, and ascended into a true prophet.
SMG and her team also joined mine. 

One thing Emma Watson disapproved of was a liberal use of time wraps and time travel.
She wanted to have a rough sense of the passage of the "real time" and so used them only during emergencies.
She instead depended on other wizard helpers, including those that temporarily assumed her appearance using magic.
MJH agreed to disagree on that with her given Watson and her team still got a lot done. 

However, at ~1997/1998, during my "great mania", I likely was pitted against many terminators during a short time, and the devils fought back and filled my head with fictional delusions.
They later provided inspiration and fodder for my stories and essays, but many of them were not entirely true.
MJH found herself ineffective in dealing with this crisis, and only Watson and her team were able to handle the pressure.
Basicly, I was a pawn in TheGame(TM) because theGamers(TM) determined that Emma Watson will replace Hart. 

Eventually, my mind sided with Watson ("real time" and "`your time is everybody's time`"), and MJH passed the leadership to her, and decided to limit her own use of time skews.
Melissa remained part of my/Rindolf/Emma Watson's team. 

In the meanwhile, while I well-aware of who Melissa Joan Hart was (given she starred in https://en.wikipedia.org/wiki/Clarissa_Explains_It_All[Clarissa
Explains It All] and in https://en.wikipedia.org/wiki/Sabrina_the_Teenage_Witch_(1996_TV_series)[Sabrina the Teenage Witch] ), I was oblivious to Emma Watson`'s existence. 

I recall that having read https://harrypotter.fandom.com/wiki/Harry_Potter_and_the_Philosopher%27s_Stone[the first Harry Potter book] by JK Rowling, I found it enjoyable and accessible, but not as good as past children's literature I had read. https://www.shlomifish.org/meta/FAQ/#opinion_on_harry_potter[The
subsequent terrestrial Harry Potter books took themselves too seriously].
Anyway, part of Emma's motivation in playing Hermione in the first Harry Potter film, was for getting https://twitter.com/shlomif/status/1511632946658258946[me to register her existence].
She and the other actors were also instructed to play https://twitter.com/shlomif/status/1486799232971464704[hackily and in a "so bad it's good" manner] since they didn't want to be kept on the filming set for long. 

At ~2011 when I wrote https://www.shlomifish.org/humour/Selina-Mandrake/cast.html[the
proposed cast page of Selina Mandrake - The Slayer], I chose her to play Selina.
At 2014 when https://www.shlomifish.org/humour/fortunes/show.cgi?id=sharp-perl-jobs-EmWatson-Saladin-knights-Templar[someone
on freenode`'s #perl insulted Emma`'s looks], I felt like he was being blasphemous (= https://he.wikipedia.org/wiki/%D7%97%D7%99%D7%9C%D7%95%D7%9C_%D7%94%D7%A7%D7%95%D7%93%D7%A9["חילול
הקודש"]). Watson was not a mere actress for me.
Someone on freenode noted that Selina resembled me at ~2020.
The lives of Emma, https://buffyfanfiction.fandom.com/wiki/Kate_(Selinaverse)[Milady
Kate] and of me have paralleled (non-coincidentally). 

While Emma started as easily hurt, and overreacting/overemotional, (not unlike me) she eventually http://shlomifishswiki.branchable.com/Encourage_criticism_and_try_to_get_offended/[developed a thicker skin] (also like I did). As a result, she was increasingly able to play herself (rather than relying on "stunt doubles"/lookalikes) including on https://www.shlomifish.org/meta/FAQ/how_do_you_expect_to_afford_the_actors.xhtml[indie films], on various https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/beautiful_people_are_geeks.xhtml[school/cons/etc. parody plays], and on https://www.shlomifish.org/meta/nav-blocks/blocks/#harry_potter_nav_block[my own screenplays featuring her]. 

In a sense, she had both a harder time and an easier time than I had.
It was harder for her because she didn't take for granted the cruelties, lies, and obstacles I ran into.
On the other hand, the (true prophet) people around her knew better than to overreact when she lost her temper/etc. 

Nevertheless, Emma's job was monumental, and almost super-human.
I'll be forever grateful to her. 

Given "Eymah" means "terror" or "horror" in Hebrew, females called "Emma" (or even their stunt doubles) tend to burst in rage often.
Watson also had to cope with her being my (= Shlomi Fish`'s) head watcher, and me incorporating her into fics-and-essays ( https://www.shlomifish.org/meta/nav-blocks/blocks/#harry_potter_sect[Reference] ), which were often unintentional true lies.
Part of the reason why she has avoided weight-training, and preferred Yoga (she https://en.wikipedia.org/w/index.php?title=Emma_Watson&oldid=1177175636[became
a certified Yoga instructor]), is to cap her physical strength, and to try to become calmer. footnote:[From roughly 2003-to-2021, I considered Bar Refaeli the Alpha Female of Israel, and Esti Ginzburg its "`Beta`" Female ( Reference: "`The Alpha, The Beta, and The Gamma↔Omega [males and females]`" ). Moreover, up to 2021, Emma Watson remained the beta female of both-sides-of-the-Atlantic, whereas Keira Knightley was the British alpha female, and the woman whom I considered the USA`'s Alpha Female fluctuated:]

[[real-time]]
== "Your time is everybody`'s time"

link:#Melissa_Joan_Hart[Melissa Joan Hart
(MJH)]`'s habit of stuffing several days into each calendrical one left her physically and mentally exhausted, despite the fact that she got a lot of sleep.
It was common to hear "`if you want to get it done, you'd better talk to
Emma [Watson]`" among the workers of my/Rindolf/MJH's team for a while, so the takeover was retrospectively expected. 

Also see https://en.wikipedia.org/wiki/Erin_Hoffman["EA Spouse"'s story]. 

[[TMTOWTDI]]
== "There's more than one way to do it"

Most policemen in Britain don't carry guns. 

In Tel Aviv, many policemen carry non-concealed guns, while almost all civilians and soldiers-in-uniforms do not. https://www.flickr.com/photos/shlomif/albums/72157648685448751[You can bring toy firearms to a science-fiction/fantasy/etc. convention in Tel Aviv.]

In Texas, some civilians carry guns, which they often are not skilled enough to use properly. "`There ain't nothin' like a Tennessee mountain top ; Some straight shootin' neighbors that don't name drop ; With a preacher man prayin' for peace but still packin' a gun.`" ( -- https://www.youtube.com/watch?v=Ig-9RDH5dZ0[Kid Rock - "`Tennessee Mountain Top`"] ) 

All three schemes work, but the nature of the places accommodates for them. 

Arnold Schwarzenegger and Emma Watson may seem like polar opposites, but they still have a lot in common, and they make a great team in https://www.shlomifish.org/humour/Terminator/Liberation/["Terminator: Liberation"].
So do https://mlp.fandom.com/wiki/Discordant_Harmony[Fluttershy and Discord]. 

[[sorry]]
== Sorry for the inconvenience:

If we are to believe https://en.wikipedia.org/wiki/Cogito%2c%5fergo%5fsum[Cogito, ergo sum] (= "I think, therefore I am"), the only thing I can be sure of is that I exist.
However, as cool as I may be, I doubt my mind alone could conceive the awesome action heroes listed https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/indiv-nodes/notable-hacker-monarchs.xhtml[on this page] including Saladin, Walt Disney, Jim Henson, and Aristotle - most of whom have ample evidence for being real.
And given my present mediocre Inkscape 2-D vector graphics skills, I am enthralled even by the 2-and-a-half dimensions graphics of some 1990s computer games (e.g: https://en.wikipedia.org/wiki/Monkey_Island_2%3A_LeChuck%27s_Revenge[Monkey Island 2] ; https://streetfighter.fandom.com/wiki/Street_Fighter_II_%28series%29[Street Fighter II] ; https://en.wikipedia.org/wiki/Quest_for_Glory_III:_Wages_of_War[Quest for Glory III]) and those of https://mlp.fandom.com/wiki/My_Little_Pony_Friendship_is_Magic[My Little Pony: Friendship is Magic] . 

Let me share a non-secret: what I wrote here is a simplification ( References: https://www.shlomifish.org/humour/Buffy/A-Few-Good-Slayers/indiv-nodes/willow_putting_her_daughter_to_bed.xhtml["Honesty is a process"], https://www.shlomifish.org/humour/Buffy/A-Few-Good-Slayers/indiv-nodes/orientation_day__team.xhtml["can`'t help speaking in riddles"] ). 

[[share-the-love]]
== "There`'s more to see than can ever be seen; more to do than can ever be done"

( Quote taken from https://www.youtube.com/watch?v=GibiNy4d4gc[the Lion King opening] . ) 

There are thousands of villages in Africa, each one with a different culture. 

There are millions of interesting https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/#hacking_and_amateur__vs__conformism_and_professional[geeks] in the Israeli electorate alone. 

There are over 40,000 distributions on https://www.cpan.org/[CPAN] . 

https://www.youtube.com/user/KurtHugoSchneider[Kurt Hugo Schneider ("KHS") uploaded over 600 videos to YouTube]

Etc. 

They all have enough food and the main reason they still accept monetary donations is the publicity. 

But like in https://www.youtube.com/watch?v=QNJL6nfu__Q[Michael Jackson's "They don't care about us"] , they crave link:#love-and-knowledge[love], attention, self-esteem and even https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/indiv-nodes/meaning-of-able-competent.xhtml[fame]. 

So I/we will always play catchup.
I was also unaware of many details of link:#ramatavivgimel[my neighbourhood] despite having lived here for several decades. 

Nevertheless, when a friend gives you a link to a tweet, or a song, or a captioned image, or a short Sesame Street skit - don't tell him that you are now exclusively focusing on Ancient Greek philosophy.
Moreover, traditional classical music concerts are the https://en.wikipedia.org/wiki/The_Emperor's_New_Clothes["The
Emperor's New Clothes"] syndrome.
That is: deemed by silent consensus to be high-quality, while actually being boring and uninspiring.
This was http://esr.ibiblio.org/?p=4229[noted by Eric Raymond] and exemplified by the https://exploringyourmind.com/a-violinist-in-the-subway-proof-that-we-look-without-really-seeing/[Joshua
Bell "Violinist in the Subway" experiment]. 

Just because you are a Python contractor, does not mean you should completely abhor https://www.shlomifish.org/meta/FAQ/why_xml.xhtml[XML technologies] or C, or even Perl/CPAN. 

https://www.youtube.com/watch?v=LnSYihRoGA4["`I want to try everything`"]. 

I also want to attend some Satanists' conventions.
I'm still a big fan of link:#the-devils[the Satans], despite them deceiving me and making me endure pain and discomfort.
Moreover, I likely had an easier time than even my father's father who escaped from the Nazis from Warsaw, Poland, through the west USSR, and Iran, until settling in Tel Aviv.
I have been willing to suffer a little more, if it meant that future generations will suffer much less.
And as I like to say: "If I didn't want excitement in my life, then https://www.joelonsoftware.com/2005/01/02/advice-for-computer-science-college-students/[I'd go watch grass grow]". 

I believe most of their conventions happen at day time, and are attended by attractive https://en.wiktionary.org/wiki/MOTAS[MOTASes], of whom only a minority have a Goth look. 

In a way, I've been doing https://en.wikipedia.org/wiki/Dialectic#Hegelian_dialectic[a Hegelian dialectic] of "`thesis -> antithesis -> synthesis`". I also have been "`changing ponies in midwater`": changing intermediate conclusions, while keeping similar end-results. 

Furthermore, "`There's more-to-life than accelerating its pace`" (to quote Mahatma Gandhi-or-whoever). These past 40 years (give or take some time skews) have been a rollercoaster ride for me, and I want some rest. 

[[stranger-than-fiction]]
== Stranger than fiction

A wise man once said: "`Truth is stranger than fiction because fiction needs to make sense.`". That's why my hell's "`real world`" cannot be real.
I disbelieve it. 

[[disadvantaged-humans]]
== Humans as a disadvantaged species

https://stexpanded.fandom.com/wiki/Q2[Q2] and the fellow sentient hacker animals used to communicate using mono-syllabic shrieks of variable length.
Thus, they wanted a 2-dimensional audible speech system, and were given one based on consonants and vowels. 

Moreover, they preferred "modern" English over the alternative (Esperanto?) given English was sexier and more interesting. 

Native speakers of Japanese often confuse the "L" and "R" sounds. 

I think the 3-D-colour-space ( RGB , HSV , CMY ) was introduced with the Milky Way galaxy, but with some catches like https://en.wikipedia.org/wiki/The_dress["The dress"].
I see the dress as white-and-gold on my desktop Linux screen and saw it as blue and grey on a friend's smartphone. 

During Englishtants times, the universe was a greyscale 3-D grid, with larger-or-smaller sub-grids.
Before that, it was binary ( "black / white"). 

[[ancestors]]
== Some vampire/etc. ancestors

* Ya'el ("Y"). 
* Aryeh ("A") 
* Celet ("C"; pronounced "Kelet"). 
* Gershom ("G", "גר", "ג") 
* Rinah ("R") 


[[defence-community]]
== The Defence Community

The Defence Community comprises of: 

* "Western" organisations, eg: 
** The NSA, CIA, FBI. 
** The mossad, the IDF, the Shin Bet. 
** Scotland Yard, MI-5. 
* More 'nefarious' organisations: 
** Russia, People's Republic of China, North Korea, Cuba 
** Iran (incl Hamas, the Hizbullah) 
** The Russian mafia, the Sicilian mafia, the Yakuzah. 
* Individuals, including: 
** https://www.shlomifish.org/meta/nav-blocks/blocks/#chuck_norris_sect[Chuck Norris]. 
** link:#shlomif-watchers-and-whichers[Emma Watson]. 
* Fictional entities such as: 
** https://hitchhikers.fandom.com/wiki/Deep_Thought[Deep Thought] - a powerful supercomputer that can crack RSA, or post-quantum encryptions at the blink of the eye ( http://www.earthstar.co.uk/deep1.htm[Reference 1] ; https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/indiv-nodes/fear-is-path-to-dark-side.xhtml["Fear is the path to the dark side"] ) 
** https://memory-alpha.fandom.com/wiki/Jem%27Hadar[the Jem'Hadar]
** http://shlomifishswiki.branchable.com/Fluttershy__44___Princess_of_Princesses__44___head_of_the_secret_cabal_leadership_of_the_Mossad__44___the_already_top_secret_intelligence_agency_of_the_Zionist_conspiracy/[Fluttershy]

They avoid mass-surveillance and instead rely on observers`' reports.
During crime prevention, they profile the fairy (a hacker/etc.) who intends to perform the crime (due to being obsessed/etc.) by profiling him: constructing a static *model* of him.
This model is temporary, and can and likely will get out-pf-date, given his mind is dynamic. 

They are mainly concerned with preventing physical pain and peril. 

[[corporations]]
== Corporations / companies / organisations / schools

TheCodex(TM) recognises the concept of a "Corporation" (= many bodies), which can be as small as a regional games' club, or as large as https://buffyfanfiction.fandom.com/wiki/Q_Continuum_(Selinaverse)[the Q Continuum]. 

____
Trump, like @fedora, has many employees, and parttime volunteers and fans/frenemies/critics.
They act as a geeky beehive not unlike ancient Greek schools . 

Reportedly over 80% of Dilbert's strips are based on ideas of fans. 

( -- https://twitter.com/shlomif/status/1497889688350334981[Tweet] ) 
____

Corporations have souls.
Moreover, one must be allowed to disassociate from a corporation. 

____
There is the cliché scene from https://memory-alpha.fandom.com/wiki/Trill_%28planet%29[Trill] sitcoms where a pair of male Japanese tourists arrive there and are enthusiastic.
They aren't stupid, just awesomely Jappy. https://en.wikipedia.org/wiki/Theory_of_forms[Platonic
Ideals]. 

( -- https://twitter.com/shlomif/status/1551405512830353409[Tweet] ) 
____

A link:#hackers[hacker] can belong to many corporations: 

____
*Question:* How do you define yourself? Are you a Jew, an Israeli, an agnostic, an Objectivist, a brony, a furry, a Muppets' aficciando, a Perler, a Linuxer, a FOSS enthusiast, an optimist, a Pythoneer, ...? 

*Answer:* I am currently many of these and more.
As I noted in an essay, I define myself as "Shlomi Fish". I have my own hybrid philosophy titled "Rindolfism" and it changes almost every day. 

( Taken from https://www.shlomifish.org/meta/FAQ/how_do_you_define_yourself.xhtml[Shlomi Fish's FAQ] ) 
____

Not-for-profit organisations ("NPOs") are also corporations ( https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#time-is-much-more-important-than-money[Reference] ). 

[[couples]]
=== Corporations of 2 members: "couples", "pairs"

Parenthood, childhood, companionship. 

TheCodex(TM) gives special treatment to corporations of two members, called 'pairs'. There are three major types of them: 

. X is a "parent" [= mentor] of Y. 
+
Not necessarily a genetic parenthood, of course. 
. Y is a "child" [= "protege"] of X (if X is a parent of Y). 
. X and Y are companions, and wish to raise mutual children. 
+
A romantic, sexual, boyfriend+girlfriend or husband+wife relationship is a natural application of this.
However, so is a business partnership, or a regular friendship. 

A hacker may opt to break-up / divorce the other pair-member. 

[[types-of-pleasure]]
== Types of pleasure

. humour / amusement 
. awe 
** lust 
. joy, fun 
. content-ness, happiness. 
. cruelty, schadenfreude 
. http://www.paulgraham.com/hs.html?viewfullsite=1[relief] - 


[[shlomif-terminating-log]]
== My Log of Terminating

https://twitter.com/shlomif/status/1477303776495210498[Mom Cimorelli] was a terminatrix who wanted to have 11 children given it was her lucky number.
However, a vampirella may only give birth to a boy+girl pair.
One thing she and I had in common was that we both liked playing https://fc-solve.shlomifish.org/faq.html[Freecell].
I wrote the first versions of Freecell Solver in 2000 shortly before https://cimorelli.fandom.com/wiki/Dani_Cimorelli[Dani Cimorelli], her 6th daughter, was born, so her mother ascended before Dani's birth. 

https://www.explainxkcd.com/wiki/index.php/406:_Venting[xkcd #406: venting] displayed "Shlomi Fish" when viewed by https://www.shlomifish.org/meta/nav-blocks/blocks/#xkcd_sect[Summer Glau].
She was terminated by me shortly after that. 

I think the last runner-ups were: 

. https://www.shlomifish.org/humour/bits/facts/Taylor-Swift/[Taylor Swift] - I suspect my echo was her lover. She was terminated by https://www.shlomifish.org/humour/Summerschool-at-the-NSA/["Summerschool at the NSA"]. 
+
Moreover, she and I have a genetic daughter: Rebecca "Becky" Jadzia [lastname], as evidenced by my https://www.shlomifish.org/humour/stories/#buffy-few-good[2014 wave of inspiration and creativity]. 
. https://www.facebook.com/vendu/[Tuomo "Vendu" Venäläinen] - https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/be_communicative.xhtml[Reference #1]
+
I perceived him on freenode as a sloppy/slacker kernel dev, a marijuana user and activist, and as a fan of Rock and metal music (among other genres). He may have perceived me similarly, before he visited my (static) home site. 
. https://en.wikipedia.org/wiki/Kim_Kardashian[Kim Kardashian] ( https://www.shlomifish.org/humour/bits/Who-will-ride-Princess-Celestia/[Reference #1] ) 

I suspect https://www.shlomifish.org/philosophy/philosophy/putting-all-cards-on-the-table-2013/indiv-nodes/departing_pope_about_twitter.xhtml[Pope Benedict XVI] was not terminated by me, but rather by either Taylor Swift or Kim Kardashian. 

Another challenging adversary was my 7th->12th grades' friend, Tal.
At the time, it seemed he was smarter and funnier than me, and had a more vivid imagination.
However, I was more idealistic, tried hard to be noble and benevolent, was more diligent, challenged prejudice more, and was sometimes more merciful.
My story https://www.shlomifish.org/humour/TheEnemy/["The Enemy and how I Helped to Fight it"] may have been either the termination final blow or an aftermath. 

[[last-standing-vampires]]
== Last standing vampires: Jim Henson and Shlomi Fish

[cols="1,1", frame="all"]
|===

|

*Parameter*
|

*Manifestations*

|

Franchise. 
|

Jim Henson had the Muppets' franchise, while I had my online WWW/Internet presence ( *.shlomifish.org / etc.
) 

We were both made to think they were obscure and unprofitable. 

Like https://www.sparknotes.com/lit/atlasshrugged/character/hank-rearden/[Hank Rearden in "`Atlas Shrugged`"] who called Rearden Metal, Rearden Mines, etc.
after himself, Henson may have thought The Muppets were only known as "Jim Henson`'s creatures shop". https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/#subverting_franchise_copyright_maximalism[Reference]: 

[quote]
Back after Sesame Street started airing and became notorious for its high entertainment / educational value (and political activism as for example its friendly, benevolent, and lovable "monsters" alluded to the contemporary western perception of the Communists), it was a labour of love by a large group of people.
Nevertheless, they had one poster child figure: Jim Henson.
As a result, when his company embarked on creating a somewhat more "adult-oriented" and commercial project, https://en.wikipedia.org/wiki/The_Muppet_Show[The
Muppet Show], it was renamed to https://en.wikipedia.org/wiki/The_Jim_Henson_Company[Henson Associates, Inc.] knowing that it made them much more untouchable by copyright trolls. 

|

Favourite Daughter 
|

https://www.shlomifish.org/art/recommendations/music/online-artists/fan-pages/chris-grimmie/[Christina Grimmie] in my case, and link:#dispelling-ziyoonism[Buffy] in Henson's. 

We were both made to think they were quite obscure and unsuccessful. 

We were also made to think they "turned to the dark side" and were killed. 

In addition, my 2nd-in-command was/is https://www.shlomifish.org/meta/nav-blocks/blocks/#tiffany_alvord_sect[Tiffany Alvord], and I think Henson`'s was https://en.wikipedia.org/wiki/Brooke_Shields[Brooke Shields]. 

|

Watcher 
|

In Henson's case it was https://en.wikipedia.org/wiki/Joss_Whedon[Joss Whedon]. 

In mine, it was link:#shlomif-watchers-and-whichers[Emma Thompson -> MJH -> Emma Watson]. 

|

"The case for commercial fan-art" 
|

My essay https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/["`Commercial Real Person Fan Fiction (RPFs), crossovers and parodies as 2021 geek/hacker imperatives for revitalising the film industry`"] was probably a remake of a similar one that Henson had written. 

|

Screenplay format. 
|

Both Henson and I had https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/#hollywood_screenplay_format[antagonism toward the terrestrial
"Hollywood-blessed screenplay format"] (which was neither popular nor mandated). 

|

Electronic/etc.
Technology 
|

https://www.shlomifish.org/meta/FAQ/#computers-specs[My GNU/Linux desktop box] runs codes of Python3, perl5, XHTML5, TT3, etc.
at a fraction of the time that 1980 mini-computers ran C / Assembly / etc.
codes. 

|

Social status. 
|

Both Henson and I were made to feel isolated, with unresponsive or soulless/lifeless friends and celebrities. 

|

Calamities 
|

There were strings of calamities in our media: a pandemic, a war, transilliness, extreme weather, a newborn nephew/niece. 

We both were increasingly non-plussed by them, given we realised our hells were not real. 

|

Prior art 
|

I was able to build upon and reuse recent works/franchises.
That includes my hell's versions of Henson's Sesame Street and The Muppets. 

|

Time wrap 
|

I suspect Henson&his team lived in a time-wrap, while I didn't/don't. 

|

Filming the works 
|

Henson did produce/direct/film some of his screenplays. 

On the other hand, I just placed them on the Web as XHTML or text (and they were produced unbeknowest to me). 
|===

[[ultimatum-to-the-devils]]
== Ultimatum to the devils (= the gamemasters)

Assuming link:#terrestrial[terrestrial] science was true, I should have died of water deprivation a long time ago.
Now, I am holding a grudge against link:#hackers[the fuckers] and will not forgive them until link:#shlomif-favourite-child[I
see evidence that one of my favourite children, Christina Grimmie, is alive, healthy, conscious, kicking, and kicking ass]! I will https://www.shlomifish.org/humour/Queen-Padme-Tales/Queen-Padme-Tales--Queen-Amidala-vs-the-Klingon-Warriors.html#padmes-frustrations-with-her-love-life[rationally forgive them] after that. 

. If my soul and/or mind perish, then link:#jehovah[Jehovah] (and my name and form) will be violated. 
. If I remain resentful forever, then link:#jehovah[Jehovah] will be violated too. 


[[see-also]]
== See Also:

* https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/[Homepage of This document ("Multiverse cosmology v0.4.x")]
* https://www.shlomifish.org/art/recommendations/music/online-artists/fan-pages/chris-grimmie/[Fan page for Christina Grimmie]
.. https://www.shlomifish.org/art/recommendations/music/online-artists/fan-pages/chris-grimmie/#what-i-learned["What I learned from Internet/social media creators"]
* A less organised, but more comprehensive in parts, document about the devils and the "real world". 
** https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/why-the-so-called-real-world-makes-little-sense/[HTML From DocBook]
** https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/why-the-so-called-real-world-makes-little-sense/#more-thoughts[Evidence that this hell cannot be real] - logically and reasonably. 
** https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/why-the-so-called-real-world-makes-little-sense/#post-ascension-plan[short-term post-Catharsis plan]
* https://github.com/shlomif/shlomif-tech-diary/blob/master/my-candidates-for-terran-leadership.asciidoc[Candidates for new Terran leadership]
* https://github.com/shlomif/shlomi-fish-homepage/blob/master/lib/screenplay-xml/txt/end-game-for-shlomif-as-a-false-prophet.txt[End game for @shlomif as a false prophet]
** https://www.shlomifish.org/humour/tempbits/end-game-for-shlomif-as-a-false-prophet/end-game-for-shlomif-as-a-false-prophet.raw.html[XHTML5 version]
* https://github.com/shlomif/shlomif-tech-diary/blob/master/love-life-policy.asciidoc[My love-life policy]
* Hacks: 
.. https://www.youtube.com/watch?v=ehjGPlehIow[Singalong cover of "Feelin' Good" (by Christina Grimmie) - YouTube]
.. https://www.youtube.com/watch?v=qImhVeEXfIU[Shlomi Fish singalong cover of First to 11's "you shook me all night long" - YouTube]
.. https://www.youtube.com/watch?v=tb3_XJxx8Mg["Hurt me tomorrow [Tiffany Alvord] singalong cover - YouTube"]
.. https://www.youtube.com/watch?v=ebf7SsPiI4Y["KHS go the distance cover - singalong cover by Shlomi Fish - YouTube"]
.. https://www.shlomifish.org/humour/fortunes/show.cgi?id=the-story-of-Julia-Vins-in-the-Shlomifverse["The story of Julia Vins in the Shlomifverse [RPF] - Fortune"]
.. https://www.shlomifish.org/humour/Queen-Padme-Tales/Queen-Padme-Tales--Take-It-Over-indiv-nodes/Gul-Dukat-and-TheRealGrimmie-live-on-metaPlanet1.xhtml["Queen Padmé Tales: Gul Dukat and @TheRealGrimmie Live on meta-Planet-1"]
.. https://www.shlomifish.org/humour/bits/Who-will-ride-Princess-Celestia/["Who will ride Princess Celestia next?"]
.. https://www.shlomifish.org/humour/bits/How-Ronda-Rousey-Lost-her-UFC-Streak/["[RPF] How Ronda Rousey Lost her UFC Streak"]
.. https://www.shlomifish.org/humour/The-10th-Muse/["The 10th Muse"]
.. https://www.shlomifish.org/humour/Muppets-Show-TNI/Tiffany-Alvord.html[The Muppet Show hosting Tiffany Alvord]
.. https://www.shlomifish.org/humour/All-in-an-Atypical-Day-Work/["All in an Atypical Day`'s Work"] - MLP / "Rindolf" 
.. https://www.shlomifish.org/humour/bits/One-does-not-simply-start-a-story-with-And-they-all-lived-happily-ever-after/["`One does not simply start a story with '`And they all lived happily ever after`'`"] - MLP / etc. 
.. https://www.shlomifish.org/humour/So-Who-The-Hell-Is-Qoheleth/["`So, who the Hell is Qoheleth?`" - An Illustrated Screenplay]
.. https://www.shlomifish.org/humour/bits/true-stories/[My true stories / memoirs] - may be scary in retrospect. 
.. https://github.com/shlomif/shlomi-fish-homepage/commits/master/src/meta/FAQ/index.xhtml.tt2[Recent changes to my personal F.A.Q.]
.. https://www.shlomifish.org/humour/fortunes/show.cgi?id=sharp-religion-rindolfism[##religion - Reviewing Rindolfism] - mostly by elgranroble. 
* https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/why-the-so-called-real-world-makes-little-sense/#post-ascension-plan[Post-ascension plan]
* Precursors / stepping stones: 
** https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/["Putting Cards on the Table (2019-*)"]
** https://www.shlomifish.org/meta/nav-blocks/blocks/#commercial_fanfic_initiative_nav_block["The Commercial Fan-fiction Initiative"]
*** https://www.shlomifish.org/humour/Queen-Padme-Tales/[Queen Padmé Tales]
*** https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/[ Commercial Real Person Fan Fiction (RPFs), crossovers and parodies as 2021 geek/hacker imperatives for revitalising the film industry - Shlomi Fish`'s Homesite ]
** https://github.com/shlomif/shlomif-tech-diary/blob/master/hydrogen-bombs-are-likely-an-old-intelligence-hoax.asciidoc["Hydrogen Bombs are likely an old intelligence hoax"]
* Relevant 3rd-party resources: 
** https://www.youtube.com/watch?v=wPOviqxFllA[Little Buddha: "Awakening"] - why I'm remaining calm in face of hostile and pessimistic media. 
** https://www.youtube.com/watch?v=ZIp_GmwLbnM[Kid Rock - Cold and Empty [Official Video] - YouTube] - real world vs. link:#terrestrial[terrestrial hell]. 
** https://www.youtube.com/watch?v=5pBjopDymts["It's Gonna Be OKAY - The Piano Guys"]
** https://www.youtube.com/watch?v=k84QxVJd0tI[Skylar Grey - Coming Home, Pt. II (Official Video)]
** https://www.poetryfoundation.org/poems/46473/if---[Rudyard Kipling's "If--"]
** https://www.youtube.com/watch?v=mjYGB4uYgWw["The Lion King Rafiki Learns Simba is Alive HD - YouTube"] - Christina Grimmie/etc. are alive. 
** https://www.youtube.com/watch?v=gb8AGuD2uOI["The Bonnie Banks of Loch Lomond - Ella Roberts - YouTube"]
** https://www.youtube.com/watch?v=lk0Ec8lle4o[Nepal ['the stone bird']]
** https://www.youtube.com/watch?v=_8C1-igfniM[Subliminal - "60 years old"]
** https://www.youtube.com/watch?v=49tZw72C2yU[Subliminal - "flowers in the barrel"]
** https://www.youtube.com/watch?v=_WamkRSDeD8["Will Smith - Just The Two Of Us (Official Video) - YouTube"] - about parenthood. 
** https://en.wikipedia.org/wiki/If_Wishes_Were_Horses_(Star_Trek:_Deep_Space_Nine)[If Wishes Were Horses (Star Trek: Deep Space Nine)] - fantasies come true, and can be disbelieved. 
** https://www.youtube.com/watch?v=yWbMz_aBlMU[Kelly Clarkson - "People Like Us"]


[[coverage]]
== Coverage, comments, and discussions

. https://shlomif-tech.livejournal.com/77091.html[Shlomi Fish's livejournal blog] - 
. https://twitter.com/shlomif/status/1537464781392707592[Shlomi Fish's Twitter]
. https://www.facebook.com/shlomi.fish/posts/10158704192116981[Shlomi Fish's facebook] - might require login. 


[[the-codex]]
== TheCodex(TM) of TheGame(TM) of Fantastecha(TM)

. https://en.wikipedia.org/wiki/Term_logic[Term logic]
. https://en.wikipedia.org/wiki/Peano_axioms[Peano's axioms of arithmetics]
. https://en.wikipedia.org/wiki/Naive_set_theory[Naive set theory] and https://en.wikipedia.org/wiki/Zermelo%E2%80%93Fraenkel_set_theory[ZFC]
. link:#hackers[hackers vs. fuckers] - א0 vs. א1. etc. 
. {empty}
.. Elohim - a player / gamemaster. 
.. link:["jew"] - a player character. 

.. Time - single dimensional, moving forward, and discrete. As opposed to https://en.wikipedia.org/wiki/General_relativity[Einstein's Theory of Relativity], it is not "just another dimension of a 4-D universe". 
.. Soul ( link:#free-will[Reference #1] ) 
.. Network: set theory and extended Graph Theory ("contextualism") 
*** Sets may contain themselves - directly or indirectly. 
*** Nodes and links may have subsystems. 
*** Links may have more than one entry node. 

+
Our 3-D universe with matter-based planets / star systems / galaxies / etc.
is one possible specialisation of the Fantastecha(TM) network, but so are other imaginary universes. 
+
Travelling from one node to a different one requires expending at least one positive unit of time.
One can also travel a finite, but large, positive amount of time into the future.
( E.g: link:#ghost-town-pattern[The Ghost Town Pattern] ) 
.. Mind - a hacker's model of the past states of the Network, and its present state. 
.. link:#love-and-knowledge[Love] - pleasure/etc. 
.. link:#love-and-knowledge[Knowledge] - fun education and creation/conception - what yields the most pleasure. 
+
Changes the Network irreversibly! 
+
Note that when hackers are born, their minds contain some bootstrapping knowledge.
For example, when https://www.shlomifish.org/art/recommendations/music/online-artists/fan-pages/chris-grimmie/[Christina Grimmie] sprang into action in 1994, she knew enough English to say "`I'm
going to be a post-modern take on a tomboy: a videogames she-dork`"

Definitions: 

. *The media / mediums* "in-betweens": the paths that a meme travels until reception. 
. *Model* (static snapshot) vs. *actor / actress* (dynamic, changing, but temporary). 
. *Nature*


[[death]]
== Death

As far as we know, nobody and nothing have ever died in Fantastecha(TM). For example, in the Selinaverse, David used his sling to shoot the pebble close to Goliath's face noting that he missed on purpose. 

https://en.wikipedia.org/wiki/Wenceslao_Moguel[El Fusilado.]

[[ceiling-satan]]
== ceiling satan is watching you

As a gamemaster, and a link:#hackers[fucker], a link:#the-devils[satan] reviews the finite, but extremely large data state of the known Fantastecha(TM) and its hackers' (= player characters) minds.
So he knows all your thoughts (including dirty, stupid, or wrong ones), and all your passwords. https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#fear-is-path-to-dark-side[I/you have nothing to hide. "Fear is the path to the dark side."]. 

[[saving-throws]]
== Saving Throws

A gamemaster may opt to try to make a hacker do something stupid 

https://twitter.com/shlomif/status/1636724648120401920[re Will Smith`'s slap incident]

[[mantra13]]
== mantra

. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 
. Die, fucker, die. 
+
Yeah, Zine, 
+
Suck, Cock, 
+
Dick, Rock, Hack. 


[[mantra12]]
== mantra

. Die, fucker, die! 
+
Yeah, zine! 
+
Please murder or slay us. 
+
Hallelujah! 
. Die, fucker, die! 
+
Yeah, zine! 
+
Please murder or slay us. 
+
Hallelujah! 
. Die, fucker, die! 
+
Yeah, zine! 
+
Please murder or slay us. 
+
Hallelujah! 
. Die, fucker, die! 
+
Yeah, zine! 
+
Please murder or slay us. 
+
Hallelujah! 
. Die, fucker, die! 
+
Yeah, zine! 
+
Please murder or slay us. 
+
Hallelujah! 
. Die, fucker, die! 
+
Yeah, zine! 
+
Please murder or slay us. 
+
Hallelujah! 
. Die, fucker, die! 
+
Yeah, zine! 
+
Please murder or slay us. 
+
Hallelujah! 
. Die, fucker, die! 
+
Yeah, zine! 
+
Please murder or slay us. 
+
Hallelujah! 
. Die, fucker, die! 
+
Yeah, zine! 
+
Please murder or slay us. 
+
Hallelujah! 
. Die, fucker, die! 
+
Yeah, zine! 
+
Please murder or slay us. 
+
Hallelujah! 


[[mantra11]]
== mantra

. Die, fucker, die! 
+
Yeah, zine! 
+
Please murder or dice us. 
+
Hallelujah! 
. Die, fucker, die! 
+
Yeah, zine! 
+
Please murder or dice us. 
+
Hallelujah! 
. Die, fucker, die! 
+
Yeah, zine! 
+
Please murder or dice us. 
+
Hallelujah! 
. Die, fucker, die! 
+
Yeah, zine! 
+
Please murder or dice us. 
+
Hallelujah! 
. Die, fucker, die! 
+
Yeah, zine! 
+
Please murder or dice us. 
+
Hallelujah! 
. Die, fucker, die! 
+
Yeah, zine! 
+
Please murder or dice us. 
+
Hallelujah! 
. Die, fucker, die! 
+
Yeah, zine! 
+
Please murder or dice us. 
+
Hallelujah! 
. Die, fucker, die! 
+
Yeah, zine! 
+
Please murder or dice us. 
+
Hallelujah! 
. Die, fucker, die! 
+
Yeah, zine! 
+
Please murder or dice us. 
+
Hallelujah! 
. Die, fucker, die! 
+
Yeah, zine! 
+
Please murder or dice us. 
+
Hallelujah! 


[[license]]
== License:

https://creativecommons.org/licenses/by/4.0/[CC-by], Shlomi Fish, 2021 

**to add**: "the-codex" 