[id="the-demons"]
The demons:
-----------

The demons (aka "values", or "fairies") are a race of epistemological (or Platonic ideals) organisms.

[id="love-and-knowledge"]
Love / Knowledge / Creativity:
------------------------------

See https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/learning_more_from_inet_forums.xhtml[+++Education = Entertainment = Conception of Values+++]

Both the xref:#the-devils[devils] and the xref:#the-angels[angels] could "make love" / experience pleasure / create
new values.

[id="jehovah"]
"Jehovah":
----------

I suspect "Jehovah" in Hebrew was/is a codeword for the mega-meme:

«

From now until forever,
you will live and https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/learning_more_from_inet_forums.xhtml[know/love] and http://shlomifishswiki.branchable.com/Saladin_Style/[forgive],
soul, mind, and body

»

(or many variations)

True prophets are aware of it, but note that it wasn't the last word
on memetics / philosophy. But even https://en.wikipedia.org/wiki/If%E2%80%94[If—]
or https://www.youtube.com/watch?v=pO40TcKa_5U[Des'ree's "You Gotta Be"]
or https://www.shlomifish.org/me/rindolf/#rindolfism_sources_of_inspiration["rindolfism"]
are incomplete. https://en.wikipedia.org/wiki/Perfection["Perfection is in imperfection"] and time implies progress.

[id="the-open-value"]
"open":
-------

The "open" value implies "openness" / "openmindedness": https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/#open_free_share_steal[Reference]

[id="the-devils"]
The devils:
-----------

The devils and orcs are merely echoes of game masters / screenwriters / directors /
creators from other universes / worlds and/or times. Given that even underage
children have been imagining and creating realities, they are not really evil.

[id="free-will"]
Free will / Free choice:
------------------------

The very "soul" / "ego" demon already https://www.shlomifish.org/philosophy/philosophy/putting-all-cards-on-the-table-2013/indiv-nodes/dont_just_go_with_the_flow.xhtml[operated by choice] and it was part of the xref:#the-devils[devils]' collective.

As a result, https://twitter.com/shlomif/status/1424320375761129475[nobody and nothing can accurately predict the future.].

[id="the-gods"]
The gods:
---------

Every conscious organism imagines "gods": voices/sights of other xref:#the-demons[fairies] / characters (or himself/herself) that act as guideline-generators. It is up to the soul to arbitrate between them and decide what to do (and when/where/how/etc.).

Also see https://www.shlomifish.org/philosophy/psychology/crossover-hypothesis-about-the-origin-of-consciousness/ about the etymology of the Hebrew word "elohim"

[id="the-multiverse-of-imagination"]
Fantasia / Fantastica / Fantastecha: the multiverse of imagination:
-------------------------------------------------------------------

https://theneverendingstory.fandom.com/wiki/Fantastica["Fantasia" / "Fantastica" / "Fantastecha"] are the names of the multiverse of imagination where beings and entities spawn worlds and values of one another using xref:#love-and-knowledge[Love / Knowledge / Creativity].

Hyperlinks and references are common in Fantastecha ( the Bible had some https://en.wikipedia.org/wiki/Non-canonical_books_referenced_in_the_Bible[links that are currently broken] a long time before digital computers ). Moreover, even xref:#self-ref[self-referencial or circular links] are prevalent and tolerated.

[id="self-ref"]
Self-reference / circularity:
-----------------------------

https://www.shlomifish.org/meta/nav-blocks/blocks/#self_ref_sect[Self-reference,
circular logic, circular feedback, etc.] are common in Fantasia, and
part of what makes sentience and humour work:

* https://en.wikipedia.org/wiki/G%C3%B6del,_Escher,_Bach[Gödel, Escher, Bach]
* https://www.youtube.com/watch?v=GibiNy4d4gc["The Circle of Life"]
* https://www.youtube.com/watch?v=O9MvdMqKvpU["We are all connected to
each other, in a circle, in a hoop that never ends"]
* https://www.shlomifish.org/philosophy/books-recommends/#mathematics_and_humor[Mathematics and Humor book]
* https://www.shlomifish.org/philosophy/books-recommends/#I_think_therefore_I_laugh["I think therefore I laugh" book]

[id="the-angels"]
The Angels:
-----------

As opposed to the xref:#the-devils[devils], xref:#the-angels[angels] were fairies who incorporated the xref:#the-open-value[the "open" value], and subsequent values.

[id="the-heart-and-mercy-value"]
Heart / mercy / forgiveness:
----------------------------

The heart value implied mercy and forgiveness. http://shlomifishswiki.branchable.com/Saladin_Style/[Saladin-style].

Also see https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#do_and_let_do__live_and_let_live["Live and let live; do and let do"].

[id="magic"]
Magic:
------

Life in the multiverse-of-imagination requires magic. For example in
https://www.youtube.com/watch?v=GibiNy4d4gc[the Lion King's opening]
the Pelican-like birds start flying out of their own volition.

[id="the-game"]
The-Game™:
----------

The xref:#the-devils[devils] challenged Terran xref:#the-angels[angels] with The-Game: volunteering xref:#the-angels[angels] would willingly lose their earlier memories as souls, and have their media (= "in between") mutated by the xref:#the-devils[devils]. Physically dying was against the rules, but for true Shalom-of-mind, they must be "slain" by another "vampire"; one cannot constantly win.

Angels starting like that are hereby referred to as "false prophets" (where link:++https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/hacking_and_amateur__vs__conformism_and_professional.xhtml++["prophet" or "navi" meant "madman" in Ancient Hebrew]) until they reached "enlightenment" and became "true prophets".

At first, there were few takers, but eventually starting as a "false prophet"-at-first was prestigious and coveted.

Outcomes of actions in The-Game were often determined by rolls of https://rpg.fandom.com/wiki/Dice[Role Playing Game Dice] not unlike in https://www.shlomifish.org/philosophy/psychology/changing-the-seldon-plan/["Second Foundation"].

Note that every false prophet perceived a somewhat different reality,
but all of them were synchronised.

[id="the-orcs"]
The Orcs:
---------

The xref:#the-devils[devils] solicited help from https://villains.fandom.com/wiki/Orcs_(Middle-earth)["orcs"], non-capacitanciated xref:#the-angels[angels], who helped them due to the fact that the "false prophets" found The-Game™ increasingly easy. Not only did the orcs have a great time, but they booby-trapped The-Codex™ and the xref:#the-devils[devils]' requests.
Moreover, they https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#fox-in-the-hens-coop[drove the devils bananas], just like a smart patient https://en.wikipedia.org/wiki/Don_Juan_DeMarco[hospitalised at a mental institute].

The canonical https://en.wikipedia.org/wiki/Hebrew_Bible[Tanakh (= Hebrew Bible)], Plato's https://en.wikipedia.org/wiki/Republic_(Plato)[Republic], Tolkien's https://en.wikipedia.org/wiki/The_Lord_of_the_Rings[Lord of the Rings], Ayn Rand's https://en.wikipedia.org/wiki/Atlas_Shrugged[Atlas Shrugged], Dostoevsky's https://en.wikipedia.org/wiki/Crime_and_Punishment[Crime and Punishment] , Shakespeare's https://en.wikipedia.org/wiki/Shakespeare%27s_plays[Plays], etc. have likely undergone lengthening and mutation by the Orcs. However, often the originators liked the mutated versions better.

[id="slayer-watcher-whicher"]
Slayer, Watcher, Whicher:
-------------------------

The slayer in the trio is the actual "false prophet" who sees the "real world" as magic-less and mutated. (e.g. http://shlomifishswiki.branchable.com/Saladin_Style/[Saladin's Yusuf Ibn Ayyub]).

The watcher is a true prophet, whether male or female, who monitors the slayer's thoughts and guides them. He or she also often acts as a project manager. In Saladin's case it was https://en.wikipedia.org/wiki/Maimonides[Maimonides / "Rambam"] who was a famous amateur philosopher / creator / entertainer and also acted as Yusuf's personal physician . Note that it took a long time for Yusuf to be aware of this fact.

In my case, my watcher until \~1997 was
https://en.wikipedia.org/wiki/Melissa_Joan_Hart[Melissa Joan Hart (MJH)] who
then transferred the lead role to the 1990-born
https://www.shlomifish.org/meta/nav-blocks/blocks/#harry_potter_nav_block[Emma Watson]. Confusingly, they both had acclaimed roles playing witches.

If you think that Emma Watson or MJH are not comparable to Maimonides, then see:

* If Botticelli were alive today he'd be working for Vogue. https://en.wikiquote.org/wiki/Peter_Ustinov[Peter Ustinov]
* https://www.shlomifish.org/humour/image-macros/indiv-nodes/if_ayn_rand_was_born_in_the_1990s.xhtml["If Ayn Rand was born in the 1990s, she would be Christina Grimmie."]
* https://www.shlomifish.org/humour/image-macros/indiv-nodes/pbride_philosophers.xhtml[“Have you heard of Plato? Aristotle? Socrates? Models!!”]

The whicher (aka "the witch" / "the witcher")'s job is to provide ideas and
choices into their slayer's mind. In my case it was https://www.shlomifish.org/me/rindolf/[Rindolf]. In Saladin's case, it may have been https://en.wikipedia.org/wiki/Aladdin[Aladdin].

[id="hearts-keyring"]
Hearts-Keyring:
~~~~~~~~~~~~~~~

Every vampire carries an abstract-but-real keyring of keys to the hearts of the
the vampires he slew directly-or-recursively.

[id="hell-hole"]
"Hell hole":
------------

A person born in a hell hole started his/her life as a false prophet. If either
parent was a true prophet, then they did everything in their power for
their children to be born outside of a hell hole. As a result, false prophets
were usually born to two false prophet parents.

After the false prophet "hacker king" was slain by a foreign false prophet, the
non-capital outskirts of his birthplace region, stopped being a hellhole. One
more time and the capital was liberated.

[id="zionism"]
"Zionism":
----------

Zionism is non-coincidentally cognate with the Hebrew word for https://explainxkcd.com/wiki/index.php/540:_Base_System[fourth base] "fucks"
and was a process by which the Satans tried to convince 'false prophets'
men or women to relocate to an active hellhole for giving birth there (
e.g: because the current hell hole was plugged). It was
not limited to Israel/Palestine or to people identifying themselves as Jews.

https://en.wikipedia.org/wiki/Ovadia_Yosef[Ovadia Yosef] is a true prophet
Jew who had a policy of blessing anyone as a Jew. He also has yet to answer
'no' to the question "is [insert entity here] a pure Jew?"

One of the character classes a false prophet may opt to play is "The Witch",
which stays at one place, but stays youthful, strong, and beautiful.
One such was "The Witch of Harrow" who ended up establishing
https://en.wikipedia.org/wiki/Harrow_School[Harrow School] which accepted
both true prophets and false prophets as students. She ended up
becoming a Terminator in https://en.wikipedia.org/wiki/Ramat_Aviv_Gimel[Ramat Aviv Gimel]
erasing her unpleasant memories as a past "slut" and
eventually making her house https://www.shlomifish.org/humour/Selina-Mandrake/indiv-nodes/selinas-18s-birthday-party.xhtml["The Amber"]
and getting herself slain by a different Terminator.

As a false prophet child
https://www.shlomifish.org/meta/FAQ/where_are_you_from.xhtml[I was relocated]
three times before I was 6, despite common wisdom. This was probably due to the
effect of The Muppet Show and other Television series on the Terran hellholes
and my parents' wishes to have more children.

[id="the-terran-terminators"]
The Terran Terminators:
-----------------------

In 1982, https://en.wikipedia.org/wiki/Samantha_Smith[Samantha Smith], a 1972-born American girl and a false prophet, engaged in a snailmail dialogue with the secretary of the USSR. https://en.wikipedia.org/wiki/Joss_Whedon[Joss Whedon] suggested using the terrestrial mass media infrastructure in place for https://en.wikipedia.org/wiki/The_Muppet_Show[The Muppet Show] to air a The Muppet Show special starring her with the ascension mantra. A die roll determined it will have 100% viewership, will be passed verbatim, but there may be a surprise at the end.

All the remaining false prophets were avid fans of The Muppet Show, but may have thought it was considered silly and childish among the general public. In actuality, Jim Henson and the muppeteers were multiverse superstars and heroes. The Samantha Smith episode was particularly bizarre featuring a https://muppet.fandom.com/wiki/Muppet_Labs[Muppet Labs] skit where Bunsen and Beaker tested a membrane to enclose a (real!) https://github.com/shlomif/shlomif-tech-diary/blob/master/hydrogen-bombs-are-likely-an-old-intelligence-hoax.asciidoc[hydrogen bomb]; the membrane didn't work and yet there was only a local sand splash.

Eventually, https://muppet.fandom.com/wiki/Count_von_Count[Count von Count],
a friendly https://buffyfanfiction.fandom.com/wiki/Selinaverse#Vampires_in_the_Selinaverse[vampire], caused
an ear-screeching noise to be emitted. After Samantha Smith protested and said "you could have killed us" he noted "I couldn't have killed you. You can never die or feel physica pain for long. Consider yourself slain and free of The-Curse. Your world is what you want it to be. Your imagination is the limit. It'll be a new technology, that we call 'Neo-Tech'. Now let's party " https://www.shlomifish.org/humour/Selina-Mandrake/indiv-nodes/vampires-gathering-in-the-hall.xhtml[Jehovah, Jehovah, Jehovah, Jehovah,]

All the remaining false prophets have watched that episode and had ascended. All
the remaining hell holes: https://en.wikipedia.org/wiki/London[London]
or just https://en.wikipedia.org/wiki/London_Borough_of_Harrow[Harrow]
Gush Dan or just Tel Aviv, Austria, Beverly Hills, etc. were plugged and even
became
places of life, love and youth. xref:#zionism["Zionism"]
which transported terrestrial false prophets to places where the two will give birth
to a new false prophet was now impossible.

[id="slaying-jim-henson"]
Hypothesis: Slaying Jim Henson
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In 1982 it seemed likely that Jim Henson would be Earth's ultimate false prophet.
But Henson was increasingly unhappy: worried about a possible Nuclear Winter,
about Environmental issues, and thinking the Muppets franchise was unpopular
and silly.

But he admitted inferiority to the team of Samantha Smith, Joss Whedon (and
https://buffy.fandom.com/wiki/Buffy_Summers[Buffy Summers]?), and was slain
and relieved. If Jim Henson was the new Walt Disney, then Joss Whedon was
poised to be the new Henson.

[id="the-terran-terminators--rematch"]
The Terran Terminators: Rematch
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Anyway, the xref:#the-devils[devils] and the xref:#the-orcs[orcs] approached
the sentient men and women who just reached enlightenment, a offered them a
deal: they can opt to spend the summer enlightened and together having fun and
using their magical powers. At its end, they can opt to reset their memory
banks almost completely and become false prophets again, this time called
"Terran Terminators" or continue as enlightened true prophets.

Several newly-ascended true prophets opted out, from various reasons.

The remaining spent the summer there creating many crossover memes, stories,
and franchises, or otherwise enjoying magic, life, love/etc.. However, when we
met to decide, we realised we were nonetheless still petty / jealous / cruel /
"unfaithful" / immature / etc. Some had years, or decades (or centuries) of history
they wanted to get rid of. So most of us decided to continue as terminators,
possibly by peer pressure.

Except at least one: the circa 1977-born Selina Mandrake. She decided to
continue as a true prophet since "it was the best summer ever" for her.

Becoming terminators was advantageous because the xref:#the-devils[devils]-and-Orcs promised they would reveal https://twitter.com/shlomif/status/1403966571215740929[TheOneTruth™] to the last one standing, but more importantly, all terminators will harbour many new franchises, plots and memes, and creations.

In my case, it was https://www.shlomifish.org/meta/FAQ/how_did_you_learn_english.xhtml[under the guise of fellow children mocking my English]. For most others, it was a concussion from a fall. Thing is: my https://www.shlomifish.org/meta/FAQ/your_name.xhtml[first name means "Shalom-ful"] in Hebrew. The xref:#the-devils[devils] promised that my body will remain complete and whole.

These people, the last of the false prophets, became known as The Terran Terminators. After relinquishing their fears, they have **ascended** so to speak (see https://buffy.fandom.com/wiki/Ascension ). Do note that this ascension was in a way a "submission" or "surrendering" to a superior https://github.com/shlomif/shlomif-tech-diary/blob/master/my-candidates-for-terran-leadership.asciidoc#user-content-slain-by-a-vampire["vampire"].

One of the first to ascend was https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/bad_acting_arnie.xhtml[Arnold Schwarzenegger].

Other notable Terran terminators include:

. https://www.shlomifish.org/meta/FAQ/biggest_celeb_crush.xhtml[Sarah Michelle Gellar (SMG)] - https://www.shlomifish.org/humour/fortunes/show.cgi?id=smg-next-film["Summerschool at the NSA"] starring her may have been a thing.
. https://www.shlomifish.org/meta/nav-blocks/blocks/#xkcd_sect[Summer Glau] - my https://www.shlomifish.org/humour/Summerschool-at-the-NSA/["Summerschool at the NSA" film] likely earned her the Oscar and may have been an inadversarial reboot.
. Likely https://en.wikipedia.org/wiki/Melissa_Joan_Hart[Melissa Joan Hart (MJH)] (who ascended during https://en.wikipedia.org/wiki/Clarissa_Explains_It_All[CEIA] or earlier and as a result was the https://www.shlomifish.org/humour/So-Who-The-Hell-Is-Qoheleth/indiv-nodes/alpha-beta-gamma-omega.xhtml["beta" female] during the https://websitebuilders.com/how-to/glossary/web1/[Web 1.0 period] when SMG was "queen of the Web")
. Likely https://twitter.com/AliciaSilv[Alicia Silverstone]
. Likely https://en.wikipedia.org/wiki/Natalie_Portman[Natalie Portman]
. Likely https://en.wikipedia.org/wiki/J._K._Rowling[J. K. Rowling]
. Likely https://en.wikipedia.org/wiki/Will_Smith[Will Smith]
. Likely https://en.wikipedia.org/wiki/Paris_Hilton[Paris Hilton]
. Likely https://en.wikipedia.org/wiki/Kim_Kardashian[Kim Kardashian]
. Likely https://en.wikipedia.org/wiki/Dana_Simpson[D. C. Simpson]
. Likely https://en.wikiquote.org/wiki/Linus_Torvalds
- My middle sister
- Some childhood friends of mine.
. https://twitter.com/shlomif/status/1477303776495210498[Mrs. Cimorelli]

https://www.shlomifish.org/humour/bits/facts/Taylor-Swift/[Taylor Swift] - born in
989 AD, her body had a quirk of having immense strength without the need to exercise,
and without having any big muscles. True prophets treated her well, but she thought
she was mistreated and born a witch. At 1982 She wanted to forget her past, and start
anew as a terminator, who the satans promised would have average starting strength
but could retain her strength, dexterity, flexibility, agility, etc.
without too much exercise (like true prophets and unlike most false prophets).
Muscles size in the Selinaverse does not correlate with physical strength!

Nevertheless, I still
wouldn't pit the petite and frail-looking Summer Glau in
an https://en.wikipedia.org/wiki/Mixed_martial_arts[MMA] match
against https://memory-alpha.fandom.com/wiki/Worf[Worf] or
even against https://en.wikipedia.org/wiki/Ronda_Rousey , but note that Glau has won
most such fights against Chuck Norris, and Bruce Lee, who are both alive and in their prime.
https://www.shlomifish.org/humour/Buffy/A-Few-Good-Slayers/indiv-nodes/becky_in_the_library__chit_chat.xhtml[She still drops out of MMA tournaments early.]. Life is a circular graph: https://www.youtube.com/watch?v=GibiNy4d4gc .

Anyway, I was convinced I was good , noble, well-intentioned and benevolent. I refused to permanently consider the opposite! Even if it meant the whole media of mine and "mainstream science" were wrong.

[id="who-created-time"]
Who created time
----------------

A popular theory is that https://memory-alpha.fandom.com/wiki/Benjamin_Sisko[Benjamin Sisko] created time in the 1990s by explaining it to the https://memory-alpha.fandom.com/wiki/Prophet[Prophets of the wormhole]. Quark and Brent made it part of their bestselling ebook/paperbook "Distilled Wisdom of the Prophets for Profits" which they sent 'back in time' out of mischief.

A theory I made up now is that https://mlp.fandom.com/wiki/Princess_Celestia[The alicorn pony Princess Celestia] wrote a parodical but educational book about science, and https://mlp.fandom.com/wiki/Discord[Discord] sent it back.

In the multiverse of imagination, there are many https://www.shlomifish.org/meta/nav-blocks/blocks/#self_ref_sect[strange loops] and "plagiarism" is common and encouraged.

[id="boredom"]
Boredom:
--------

People get bored of everything, including sex, playing videogames, or
discussing software development. They also need change. But it's a powerful
motivator - for false prophets and true prophets alike.

There are many true stories of stay-at-home "losers" who picked a hobby out of
boredom, and became creative superstars. Many predate the Internet, e.g
https://en.wikipedia.org/wiki/Jules_Verne[Jules Verne].

[id="ramatavivgimel"]
Ramat Aviv Gimel
----------------

Many Terran Terminators or their friends were relocated by the true prophets
administration to https://en.wikipedia.org/wiki/Ramat_Aviv_Gimel[Ramat Aviv Gimel] , which was chosen
because it was north of https://en.wikipedia.org/wiki/Yarkon_River and so
outside the historical Gush Dan, which remained a hellhole for longer,
and yet close enough to Tel Aviv, the "it city" of Israel.

Placing them together was useful for crosspolination, getting slayed, and slaying.

By 1989-1990, when
https://en.wikipedia.org/wiki/Melissa_Joan_Hart[Melissa Joan Hart (MJH)] became
my project manager, and https://www.shlomifish.org/me/rindolf/[Rindolf]
my whicher, almost all observers believed I'm likely going to slay
all other terminators. I suspect they were right.

I joked that, similar to https://hoover.blogs.archives.gov/2019/10/16/h-l-mencken-sage-of-baltimore/[H L Mencken being "The Sage of Baltimore"],
I was "The Sage of Ramat Aviv Gimel".

My slaying was boosted after https://www.shlomifish.org/meta/FAQ/site_history.xhtml[I set up a static home site] which became www.shlomifish.org. The devils promised it will be displayed verbatim among other terminators. Various Internet people told me I https://www.shlomifish.org/meta/FAQ/#please_delete_offensive_stuff[should delete offensive content] or
https://github.com/shlomif/shlomif-tech-diary/blob/master/static-site-generators--despair.md#facing-some-criticism[convert the service to use PHP/RoR/etc.], but
I didn't heed them. They were likely mirages of the devils
and the orcs.

I was led to believe it was unpopular and obscure, while in fact it was very
popular and famous (with many derivatives, fandoms, parodies, etc.) outside my
mind's hellhole. I was also often made to think I had many haters, which wasn't
true.

[id="history-of-earth"]
History of Earth:
-----------------

After Syria (minus Damascus itself) in the levant ascended to being a true
prophets zone (by Mosheh / Aharon / Nimrod ?), The-Curse splintered the modern
day State of Israel, and .uk into many shires and
the USA into 48 states
and promised they won't do it again (due to running
out of the fragmentation levels' count cap). Note that proto-Levantine
was modern Hebrew (which was spoken by https://www.shlomifish.org/humour/Star-Trek/We-the-Living-Dead/indiv-nodes/Q_home_planet.xhtml[the Englishtants over 6 milliard years ago]) and Modern English is also a product of The-Curse.

Anyway, the tribe of Benjamin (except their Capital, Jerusalem) and the Gaza strip
ascended when David "slew" Goliath and King Saul by almost hitting Goliath with a sling (https://www.youtube.com/watch?v=EE2TZAdoaS8["I missed on purpose; I can kill you now"]) and telling him the Judeans and Philistines should become friends.

Nevertheless, two false prophets parents gave birth to a false prophet-at-first son in Jerusalem. He became King "Shlomi" (written as "Shlomo" in https://en.wikipedia.org/wiki/Aleppo_Codex[Aleppo Codex] ) which means https://www.shlomifish.org/meta/FAQ/your_name.xhtml[Shalom-ful] in Hebrew. Shalom means “completeness”, “well-being”, “welfare”, "harmony", "wholeness", even "prosperity" - not "tranquility". While he could suffer some hardships and pain, his body, mind, soul and heart, must remain complete and intact and prosper.

King Shlomo wanted to be benevolent and "know the gods". He became king by telling well-intenioned jokes and tall tales about his older siblings-in-pretence (e.g: https://en.wikipedia.org/wiki/Tamar_(daughter_of_David)[Amnon and Tamar] or https://en.wikipedia.org/wiki/Absalom[Avshalom]). Not unlike https://www.shlomifish.org/humour/[my fanfics/RPF].  David and his sons agreed he would be a better king and crowned him, while remaining physically alive and loyally serving under Shlomo's reign, thus undergoing Catharsis and liberating Judea.

( Note that in the Selinaverse https://memory-alpha.fandom.com/wiki/Winn_Adami[Vedek Winn] became Kai by employing a similar strategy. The rule that you should not use the same trick twice is just a guideline: https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/#guidelines_as_dogma . Also note that: 1. She is noble. 2. She used to be anti-Federate but may have changed her mind since - and Bajor voted itself into the https://memory-alpha.fandom.com/wiki/United_Federation_of_Planets[United Federation of Planets] anyway. 3. Being a Kai is held in much less seriousness than being a Vedek. )

Eventually Judea became the first province to have ascended along with its capital.
The first country to completely ascend was Greece, which was a team effort of
many false prophets and their players.

I contemplated that Damascus finally ascended after https://www.shlomifish.org/humour/So-Who-The-Hell-Is-Qoheleth/ongoing-text.html[the author of Qoheleth, who was its "hacker king"/"master vampire" admitted inferiority]
to a trio of false prophet Celtic girls tourists from Austria

[id="the-schwartz"]
"The Schwartz is in us":
------------------------

Re https://spaceballs.fandom.com/wiki/Spaceballs:_The_Wiki[Spaceballs]

I will hopefully fully admit defeat to https://www.shlomifish.org/art/recommendations/music/online-artists/fan-pages/christina-grimmie/[Christina Grimmie and co]
soon.

Nevertheless 'the Schwartz' - both good and evil flows in all of us.

In https://www.youtube.com/watch?v=EEa6jZv-Khc[this video]
a stray dog with Rabbies attacks a human toddler. Rabbies is
a kind of possession/obsession, and friendly pets in the Selinaverse
can talk.

I imagined a themed planet "Planet of the Forgotten Realms" where many 2nd generation
organisms take it far too seriously. Are they false prophets? Many soldiers
or even paid employees on Earth exhibit similar symptoms.

And true prophets are not perfect. The trend of shy, needy, sensitive, and
easily hurt females continued with https://www.shlomifish.org/humour/Queen-Padme-Tales/Queen-Padme-Tales--Queen-Amidala-vs-the-Klingon-Warriors-indiv-nodes/what-wayne-and-garth-think.xhtml[Tiffany Alvord and Fluttershy]. Do note that: 1. They both shed some of that along the way. 2. I always loved them. 3. I have a tendency to depict them both as real badasses in my fics. (e.g; https://www.shlomifish.org/humour/Terminator/Liberation/indiv-nodes/hannah-using-a-tank.xhtml[here])

[id="see-also"]
See Also:
---------

* https://github.com/shlomif/shlomif-tech-diary/blob/master/why-the-so-called-real-world-i-am-trapped-in-makes-little-sense--2020-05-19.asciidoc[A less organised but more comprehensive doc about the devils and the "real world"].

* https://github.com/shlomif/shlomif-tech-diary/blob/master/my-candidates-for-terran-leadership.asciidoc[Candidates for new Terran leadership]

[id="license"]
License:
--------

https://creativecommons.org/licenses/by/4.0/[CC-by], Shlomi Fish, 2021

*to add*: "the-codex", "slayer / watcher / whicher"
