= The demons:
2022-02-12

[[the-demons]]
== The demons:

The demons (aka "values", or "fairies" or "memes") are a race of epistemological (or Platonic ideals) organisms.

[[love-and-knowledge]]
== Love / Knowledge / Creativity:

See https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/learning_more_from_inet_forums.xhtml[Education = Entertainment = Conception of Values] often by combining two or more memes.

Entertainment *can mean* temporary pain, e.g fear.

Both the <<the-devils,devils>> and the <<the-angels,angels>> could "make love" / experience pleasure / create new values.

Love *was not* the last word of memetics.

[[jehovah]]
== "Jehovah":

I suspect "Jehovah" in Hebrew was/is a codeword for the mega-meme:

«

From now until forever,

you will live and https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/learning_more_from_inet_forums.xhtml[know/love] and http://shlomifishswiki.branchable.com/Saladin_Style/[forgive],

soul, mind, and form

what you imagine will materialise,

your destiny will come (יבוא)

you will remain passionate (יאוה)

»

(or many variations)

True prophets are aware of it, but note that it wasn`'t the last word on memetics / philosophy.
But even https://en.wikipedia.org/wiki/If%E2%80%94[If--] or https://www.youtube.com/watch?v=pO40TcKa_5U[Des`'ree`'s "You Gotta Be"] or https://www.shlomifish.org/me/rindolf/#rindolfism_sources_of_inspiration["rindolfism"] are incomplete. https://en.wikipedia.org/wiki/Perfection["Perfection is in imperfection"] and time implies progress.

[[the-open-value]]
== "open":

The "open" value implies "openness" / "openmindedness": https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/#open_free_share_steal[Reference]

[[the-devils]]
== The devils:

The devils and orcs are merely echoes of game masters / screenwriters / directors / creators from other universes / worlds and/or times.
Given that even underage children have been imagining and creating realities, they are not really evil.

[[free-will]]
== Free will / Free choice:

The very "soul" / "ego" demon already https://www.shlomifish.org/philosophy/philosophy/putting-all-cards-on-the-table-2013/indiv-nodes/dont_just_go_with_the_flow.xhtml[operated by choice] and it was part of the <<the-devils,devils>>' collective.

As a result, https://twitter.com/shlomif/status/1424320375761129475[nobody and nothing can accurately predict the future.].

That put aside, the soul is addicted to <<love-and-knowledge,pleasure>>, but may opt to avoid short term prioritisation of it.

[[the-gods]]
== The gods:

Every conscious organism imagines "gods": voices/sights of other <<the-demons,fairies>> / characters (or himself/herself) that act as guideline-generators.
It is up to the soul to arbitrate between them and decide what to do (and when/where/how/etc.).

Also see https://www.shlomifish.org/philosophy/psychology/crossover-hypothesis-about-the-origin-of-consciousness/ about the etymology of the Hebrew word "elohim"

[[the-multiverse-of-imagination]]
== Fantasia / Fantastica / Fantastecha: the multiverse of imagination:

https://theneverendingstory.fandom.com/wiki/Fantastica["Fantasia" / "Fantastica" / "Fantastecha"] are the names of the multiverse of imagination where beings and entities spawn worlds and values of one another using <<love-and-knowledge,Love / Knowledge / Creativity>>.

Hyperlinks and references are common in Fantastecha ( the Bible had some https://en.wikipedia.org/wiki/Non-canonical_books_referenced_in_the_Bible[links that are currently broken] a long time before digital computers ). Moreover, even <<self-ref,self-referencial or circular links>> are prevalent and tolerated.

[[self-ref]]
== Self-reference / circularity:

https://www.shlomifish.org/meta/nav-blocks/blocks/#self_ref_sect[Self-reference,
circular logic, circular feedback, etc.] are common in Fantasia, and part of what makes sentience and humour work:

* https://en.wikipedia.org/wiki/G%C3%B6del,_Escher,_Bach[Gödel, Escher, Bach]
* https://www.youtube.com/watch?v=GibiNy4d4gc["The Circle of Life"]
* https://www.youtube.com/watch?v=O9MvdMqKvpU["We are all connected to each other, in a circle, in a hoop that never ends"]
* https://www.shlomifish.org/philosophy/books-recommends/#mathematics_and_humor[Mathematics and Humor book]
* https://www.shlomifish.org/philosophy/books-recommends/#I_think_therefore_I_laugh["I think therefore I laugh" book]
* {empty}
+

[quote]
Mr.
Linea ( https://en.wikipedia.org/wiki/La_Linea_%28TV_series%29 ) is TheCreator.
;)
+
( -- https://twitter.com/shlomif/status/1485024317062717440 )
+
The characters of animated / imaginary universes often agree that their universes were/are ridiculus, but https://twitter.com/shlomif/status/1479063972934565893[so is ours.]


[[the-angels]]
== The Angels:

[[the-heart-and-mercy-value]]
== Heart / mercy / forgiveness:

The heart value implied mercy and forgiveness. http://shlomifishswiki.branchable.com/Saladin_Style/[Saladin-style].

Also see https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#do_and_let_do__live_and_let_live["Live and let live; do and let do"].

[[magic]]
== Magic:

Life in the multiverse-of-imagination requires magic.
For example in https://www.youtube.com/watch?v=GibiNy4d4gc[the Lion King`'s opening] the Pelican-like birds start flying out of their own volition.

[[the-game]]
== The-Game(TM):

The <<the-devils,devils>> challenged Terran <<the-angels,angels>> with The-Game: volunteering <<the-angels,angels>> would willingly lose their earlier memories as souls, and have their media (= "in between") mutated by the <<the-devils,devils>>.
Physically dying was against the rules, but for true Shalom-of-mind, they must be "slain" by another "vampire"; one cannot constantly win.

Angels starting like that are hereby referred to as "false prophets" (where https://shlom.in/geekyhackers["prophet" or "navi" meant "madman" in Ancient Hebrew]) or "vampires" until they reached "enlightenment" and became "true prophets" (or "wizards").

At first, there were few takers, but eventually starting as a "false prophet"-at-first was prestigious and coveted.

Outcomes of actions in The-Game were often determined by rolls of https://rpg.fandom.com/wiki/Dice[Role Playing Game Dice] not unlike in https://www.shlomifish.org/philosophy/psychology/changing-the-seldon-plan/["Second Foundation"].

Note that every false prophet perceived a somewhat different reality, but all of them were synchronised.

[[the-orcs]]
== The Orcs:

The <<the-devils,devils>> solicited help from https://villains.fandom.com/wiki/Orcs_(Middle-earth)["orcs"], non-capacitanciated <<the-angels,angels>>, who helped them due to the fact that the "false prophets" found The-Game(TM) increasingly easy.
Not only did the orcs have a great time, but they booby-trapped The-Codex(TM) and the <<the-devils,devils>>' requests.
Moreover, they https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#fox-in-the-hens-coop[drove the devils bananas], just like a smart patient https://en.wikipedia.org/wiki/Don_Juan_DeMarco[hospitalised at a mental institute].

The canonical https://en.wikipedia.org/wiki/Hebrew_Bible[Tanakh (= Hebrew Bible)], Plato`'s https://en.wikipedia.org/wiki/Republic_(Plato)[Republic], Tolkien`'s https://en.wikipedia.org/wiki/The_Lord_of_the_Rings[Lord of the Rings], Ayn Rand`'s https://en.wikipedia.org/wiki/Atlas_Shrugged[Atlas Shrugged], Dostoevsky`'s https://en.wikipedia.org/wiki/Crime_and_Punishment[Crime and Punishment] , Shakespeare`'s https://en.wikipedia.org/wiki/Shakespeare%27s_plays[Plays], etc.
have likely undergone lengthening and mutation by the Orcs.
However, often the originators liked the mutated versions better.

Alternatively, the orcs / "https://memory-alpha.fandom.com/wiki/Bajoran[Bajorans]" were agents of the devils who gave the organisms choices and their outcomes (often based on dice rolls).

[[slayer-watcher-whicher]]
== Slayer, Watcher, Whicher:

The slayer in the trio is the actual "false prophet" who sees the "real world" as magic-less and mutated.
(e.g. http://shlomifishswiki.branchable.com/Saladin_Style/[Saladin`'s Yusuf Ibn Ayyub]).

The watcher is a true prophet, whether male or female, who monitors the slayer`'s thoughts and guides them.
He or she also often acts as a project manager.
In Saladin`'s case it was https://en.wikipedia.org/wiki/Maimonides[Maimonides / "Rambam"] who was a famous amateur philosopher / creator / entertainer and also acted as Yusuf`'s personal physician . Note that it took a long time for Yusuf to be aware of this fact.

In my case, my watcher until ~1997 was https://en.wikipedia.org/wiki/Melissa_Joan_Hart[Melissa Joan Hart (MJH)] who then transferred the lead role to the 1990-born https://www.shlomifish.org/meta/nav-blocks/blocks/#harry_potter_nav_block[Emma Watson].
Confusingly, they both had acclaimed roles playing witches.

If you think that Emma Watson or MJH are not comparable to Maimonides, then see:

* If Botticelli were alive today he`'d be working for Vogue. https://en.wikiquote.org/wiki/Peter_Ustinov[Peter Ustinov]
* https://www.shlomifish.org/humour/image-macros/indiv-nodes/if_ayn_rand_was_born_in_the_1990s.xhtml["If Ayn Rand was born in the 1990s, she would be Christina Grimmie."]
* https://www.shlomifish.org/humour/image-macros/indiv-nodes/pbride_philosophers.xhtml["`Have you heard of Plato? Aristotle? Socrates? Models!!`"]


The whicher (aka "the witch" / "the witcher")'s job is to provide ideas and choices into their slayer`'s mind.
In my case it was https://www.shlomifish.org/me/rindolf/[Rindolf].
In Saladin`'s case, it may have been https://en.wikipedia.org/wiki/Aladdin[Aladdin].

[[hearts-keyring]]
=== Hearts-Keyring:

Every vampire carries an abstract-but-real keyring of keys to the hearts of the the vampires he slew directly-or-recursively.

[[hell-hole]]
== "Hell hole":

A person born in a hell hole started his/her life as a false prophet.
If either parent was a true prophet, then they did everything in their power for their children to be born outside of a hell hole.
As a result, false prophets were usually born to two false prophet parents.

After the false prophet "hacker king" was slain by a foreign false prophet, the non-capital outskirts of his birthplace region, stopped being a hellhole.
One more time and the capital was liberated.

[[zionism]]
== "Zionism":

Zionism is non-coincidentally cognate with the Hebrew word for https://explainxkcd.com/wiki/index.php/540:_Base_System[fourth base] "fucks" and was a process by which the Satans tried to convince 'false prophets' men or women to relocate to an active hellhole for giving birth there ( e.g: because the current hell hole was plugged). It was not limited to Israel/Palestine or to people identifying themselves as Jews.

https://en.wikipedia.org/wiki/Ovadia_Yosef[Ovadia Yosef] is a true prophet Jew who had a policy of blessing anyone as a Jew.
He also has yet to answer 'no' to the question "is [insert entity here] a pure Jew?"

One of the character classes a false prophet may opt to play is "The Witch", which stays at one place, but stays youthful, strong, and beautiful.
One such was "The Witch of Harrow" who ended up establishing https://en.wikipedia.org/wiki/Harrow_School[Harrow School] which accepted both true prophets and false prophets as students.
She ended up becoming a Terminator in https://en.wikipedia.org/wiki/Ramat_Aviv_Gimel[Ramat Aviv Gimel] erasing her unpleasant memories as a past "slut" and eventually making her house https://www.shlomifish.org/humour/Selina-Mandrake/indiv-nodes/selinas-18s-birthday-party.xhtml["The Amber"] and getting herself slain by a different Terminator.

As a false prophet child https://www.shlomifish.org/meta/FAQ/where_are_you_from.xhtml[I was relocated] three times before I was 6, despite common wisdom.
This was probably due to the effect of The Muppet Show and other Television series on the Terran hellholes and my parents' wishes to have more children.

[[the-terran-terminators]]
== The Terran Terminators:

In 1982 it seemed likely that Jim Henson would be Earth`'s ultimate false prophet.
But Henson was increasingly unhappy: worried about a possible Nuclear Winter, about Environmental issues, and thinking the Muppets franchise was unpopular and silly.

https://en.wikipedia.org/wiki/Joss_Whedon[Joss Whedon] thought "it is too easy" and eventually Henson admitted inferiority to the team of https://en.wikipedia.org/wiki/Samantha_Smith[Samantha Smith], Whedon, (and https://buffy.fandom.com/wiki/Buffy_Summers[Buffy Summers]?), and was slain and relieved.
If Jim Henson was the new Walt Disney, then Joss Whedon was poised to be the new Henson.

https://en.wikipedia.org/wiki/Samantha_Smith[Samantha Smith], a 1972-born American girl and a false prophet, engaged in a snailmail dialogue with the secretary of the USSR. https://en.wikipedia.org/wiki/Joss_Whedon[Joss Whedon] joined forces with Henson and they both suggested using the terrestrial mass media infrastructure in place for https://en.wikipedia.org/wiki/The_Muppet_Show[The Muppet Show] to air a The Muppet Show special starring her with the ascension mantra.
A die roll determined it will have 100% viewership, will be passed verbatim, but there may be a surprise at the end.

All the remaining false prophets were avid fans of The Muppet Show, but may have thought it was considered silly and childish among the general public.
In actuality, Jim Henson and the muppeteers were multiverse superstars and heroes.
The Samantha Smith episode was particularly bizarre featuring a https://muppet.fandom.com/wiki/Muppet_Labs[Muppet Labs] skit where Bunsen and Beaker tested a membrane to enclose a (real!) https://github.com/shlomif/shlomif-tech-diary/blob/master/hydrogen-bombs-are-likely-an-old-intelligence-hoax.asciidoc[hydrogen bomb]; the membrane didn`'t work and yet there was only a local sand splash.

Eventually, https://muppet.fandom.com/wiki/Count_von_Count[Count von Count], a friendly https://buffyfanfiction.fandom.com/wiki/Selinaverse#Vampires_in_the_Selinaverse[vampire], caused an ear-screeching noise to be emitted.
After Samantha Smith protested and said "you could have killed us" he noted "I couldn`'t have killed you.
You can never die or feel physica pain for long.
Consider yourself slain and free of The-Curse.
Your world is what you want it to be.
Your imagination is the limit.
It`'ll be a new technology, that we call 'Neo-Tech'. Now let`'s party " https://www.shlomifish.org/humour/Selina-Mandrake/indiv-nodes/vampires-gathering-in-the-hall.xhtml[Jehovah, Jehovah, Jehovah, Jehovah,]

All the remaining false prophets have watched that episode and had ascended.
All the remaining hell holes: https://en.wikipedia.org/wiki/London[London] or just https://en.wikipedia.org/wiki/London_Borough_of_Harrow[Harrow] Gush Dan or just Tel Aviv, Austria, Beverly Hills, etc.
were plugged and even became places of life, love and youth. <<zionism,"Zionism">> which transported terrestrial false prophets to places where the two will give birth to a new false prophet was now impossible.

[[slaying-jim-henson]]
=== Hypothesis: Slaying Jim Henson

One should note that Samantha Smith had previously written a funny story titled "Buffy the Vampire Slayer" that she believed received a lukewarm reception from her friends.
Its original manuscript was later auctioned for millions of USD.

[[the-terran-terminators--rematch]]
=== The Terran Terminators: Rematch

Anyway, the <<the-devils,devils>> and the <<the-orcs,orcs>> approached the sentient men and women who just reached enlightenment, and offered them a deal: they can opt to spend the summer enlightened and together having fun and using their magical powers.
At its end, they can opt to reset their memory banks almost completely and become false prophets again, this time called "Terran Terminators" or continue as enlightened true prophets.

Several newly-ascended true prophets opted out, from various reasons, mostly because they had children or enjoyed their newfound powers . E.g: https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/[Chuck Norris] or https://zak.co.il/[Omer Zak] or https://en.wikipedia.org/wiki/Elizabeth_II[Queen Elizabeth II] or https://en.wikipedia.org/wiki/%22Weird_Al%22_Yankovic . They still often "got sucked" into The-Game(TM).

The remaining spent the summer there creating many crossover memes, stories, and franchises, or otherwise enjoying magic, life, love/etc.. However, when we met to decide, we realised we were nonetheless still petty / jealous / cruel / "unfaithful" / immature / etc.
Some had years, or decades (or centuries) of history they wanted to get rid of.
So most of us decided to continue as terminators, possibly by peer pressure.

Like the story of https://www.shlomifish.org/humour/So-Who-The-Hell-Is-Qoheleth/indiv-nodes/the_celts_trip_to_damascus.xhtml[the Celts trip] we had a policy of not resisting rapekisses or rapehugs , but there was little if any romance and intimacy.

Except at least one: the circa 1977-born Selina Mandrake.
She decided to continue as a true prophet since "it was the best summer ever" for her.

Becoming terminators was advantageous because the <<the-devils,devils>>-and-Orcs promised they would reveal https://twitter.com/shlomif/status/1403966571215740929[TheOneTruth(TM)] to the last one standing, but more importantly, all terminators will harbour many new franchises, plots and memes, and creations.

In my case, it was https://www.shlomifish.org/meta/FAQ/how_did_you_learn_english.xhtml[under the guise of fellow children mocking my English].
For most others, it was a concussion from a fall.
Thing is: my https://www.shlomifish.org/meta/FAQ/your_name.xhtml[first name means "Shalom-ful"] in Hebrew.
The <<the-devils,devils>> promised that my body will remain complete and whole.

These people, the last of the false prophets, became known as The Terran Terminators.
After relinquishing their fears, they have *ascended* so to speak (see https://buffy.fandom.com/wiki/Ascension ). Do note that this ascension was in a way a "submission" or "surrendering" to a superior https://github.com/shlomif/shlomif-tech-diary/blob/master/my-candidates-for-terran-leadership.asciidoc#user-content-slain-by-a-vampire["vampire"].

One of the first to ascend was https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/bad_acting_arnie.xhtml[Arnold Schwarzenegger].

Other notable Terran terminators include:

. https://www.shlomifish.org/meta/FAQ/biggest_celeb_crush.xhtml[Sarah Michelle Gellar (SMG)] - https://www.shlomifish.org/humour/fortunes/show.cgi?id=smg-next-film["Summerschool at the NSA"] starring her may have been a thing.
. https://www.shlomifish.org/meta/nav-blocks/blocks/#xkcd_sect[Summer Glau] - my https://www.shlomifish.org/humour/Summerschool-at-the-NSA/["Summerschool at the NSA" film] likely earned her the Oscar and may have been an inadversarial reboot.
. Likely https://en.wikipedia.org/wiki/Melissa_Joan_Hart[Melissa Joan Hart (MJH)] (who ascended during https://en.wikipedia.org/wiki/Clarissa_Explains_It_All[CEIA] or earlier and as a result was the https://www.shlomifish.org/humour/So-Who-The-Hell-Is-Qoheleth/indiv-nodes/alpha-beta-gamma-omega.xhtml["beta" female] during the https://websitebuilders.com/how-to/glossary/web1/[Web 1.0 period] when SMG was "queen of the Web")
. Likely https://twitter.com/AliciaSilv[Alicia Silverstone]
. Likely https://en.wikipedia.org/wiki/Samantha_Smith[Samantha Smith] herself
. Likely https://en.wikipedia.org/wiki/Natalie_Portman[Natalie Portman]
. Likely https://en.wikipedia.org/wiki/J._K._Rowling[J. K. Rowling]
. Likely https://en.wikipedia.org/wiki/Will_Smith[Will Smith]
. Likely https://en.wikipedia.org/wiki/Paris_Hilton[Paris Hilton]
. Likely https://en.wikipedia.org/wiki/Kim_Kardashian[Kim Kardashian]
. Likely https://en.wikipedia.org/wiki/Dana_Simpson[D. C. Simpson]
. Likely https://en.wikiquote.org/wiki/Linus_Torvalds
. Likely https://en.wikipedia.org/wiki/Joel_Spolsky
. Likely https://www.shlomifish.org/humour/fortunes/paul-graham.html[Paul Graham]
. Likely https://en.wikipedia.org/wiki/Jennifer_Lopez
. Likely https://en.wikipedia.org/wiki/Meredith_Brooks
. Likely Steve from https://en.wikipedia.org/wiki/Smash_Mouth
. Likely https://en.wikipedia.org/wiki/Wil_Wheaton
. Likely https://en.wikipedia.org/wiki/Pope_John_Paul_II[Pope_John_Paul_II] and https://www.shlomifish.org/philosophy/philosophy/putting-all-cards-on-the-table-2013/indiv-nodes/departing_pope_about_twitter.xhtml[Pope Benedict XVI]. They both had to retire following their ascension. 
. https://www.youtube.com/watch?v=T6wbugWrfLU[Celine Dion]
. https://en.wikipedia.org/wiki/Scatman_John[Scatman John]
. link:[Felicia Day] - 
. link:[K'NAAN]
. link:[Des'ree] - 
. link:[Patrick Stewart] - 
. https://www.shlomifish.org/humour/bits/facts/Clarissa/[The real Clarissa Darling] - 
. My middle sister
. Some childhood friends of mine.
. https://twitter.com/shlomif/status/1477303776495210498[Mrs. Cimorelli]
. https://www.shlomifish.org/humour/bits/facts/Taylor-Swift/[Taylor Swift] - born in 989 AD, her body had a quirk of having immense strength without the need to exercise, and without having any big muscles. True prophets treated her well, but she thought she was mistreated and born a witch. At 1982 She wanted to forget her past, and start anew as a terminator, whom the satans promised would have average starting strength but could retain her strength, dexterity, flexibility, agility, etc. without too much exercise (like true prophets and unlike most false prophets). Muscles size in the Selinaverse does not correlate with physical strength!
+
Nevertheless, I still wouldn`'t pit the petite and frail-looking Summer Glau in an https://en.wikipedia.org/wiki/Mixed_martial_arts[MMA] match against https://memory-alpha.fandom.com/wiki/Worf[Worf] or even against https://en.wikipedia.org/wiki/Ronda_Rousey . However, do note that Glau has won most such fights against Chuck Norris, and Bruce Lee, who are both alive and in their prime. https://www.shlomifish.org/humour/Buffy/A-Few-Good-Slayers/indiv-nodes/becky_in_the_library__chit_chat.xhtml[She still drops out of MMA tournaments early.].
Life is a circular graph: <<self-ref,Reference>>


Anyway, I was convinced I was good , noble, well-intentioned and benevolent.
I refused to permanently consider the opposite! Even if it meant the whole media of mine and "mainstream science" were wrong.

[[who-created-time]]
== Who created time

A popular theory is that https://memory-alpha.fandom.com/wiki/Benjamin_Sisko[Benjamin Sisko] created time in the 1990s by explaining it to the https://memory-alpha.fandom.com/wiki/Prophet[Prophets of the wormhole].
Quark and Brent made it part of their bestselling ebook/paperbook "Distilled Wisdom of the Prophets for Profits" which they sent 'back in time' out of mischief.

A theory I made up now is that https://mlp.fandom.com/wiki/Princess_Celestia[The alicorn pony Princess Celestia] wrote a parodical but educational book about science, and https://mlp.fandom.com/wiki/Discord[Discord] sent it back.

In the multiverse of imagination, there are many https://www.shlomifish.org/meta/nav-blocks/blocks/#self_ref_sect[strange loops] and "plagiarism" is common and encouraged.

[[boredom]]
== Boredom and Lethargy:

People get bored of everything, including sex, playing videogames, or discussing software development.
They also need change.
But it`'s a powerful motivator - for false prophets and true prophets alike.

There are many true stories of stay-at-home "losers" who picked a hobby out of boredom, and became creative superstars.
Many predate the Internet, e.g https://en.wikipedia.org/wiki/Jules_Verne[Jules Verne], or https://en.wikipedia.org/wiki/E._Nesbit[E. Nesbit].

[[ramatavivgimel]]
== Ramat Aviv Gimel

Before having our memories reset, my friend Amit and I concluded that https://mygeekwisdom.com/2011/09/12/be-excellent-to-each-other/[the Golden Rule] implied sincerely criticising others even if it hurts their feelings.
Having slain Arnold Schwarzenegger, https://en.wikipedia.org/wiki/Melissa_Joan_Hart[Melissa Joan Hart (MJH)], and Samantha Smith, the two of us were afterward kept in the same elementary school classroom with no other false prophets. 

Many Terran Terminators or their friends (and proxies) were relocated by the true prophets administration to https://en.wikipedia.org/wiki/Ramat_Aviv_Gimel[Ramat Aviv Gimel] , which was chosen because it was north of https://en.wikipedia.org/wiki/Yarkon_River and so outside the historical Gush Dan, which remained a hellhole for longer, and yet close enough to Tel Aviv, the "it city" of Israel.

Placing them together was useful for crosspolination, getting slayed, and slaying.

By 1989-1990, when https://en.wikipedia.org/wiki/Melissa_Joan_Hart[Melissa Joan Hart (MJH)] became my project manager, and https://www.shlomifish.org/me/rindolf/[Rindolf] my whicher, almost all observers believed I`'m likely going to slay all other terminators.
I suspect they were right.

I joked that, similar to https://hoover.blogs.archives.gov/2019/10/16/h-l-mencken-sage-of-baltimore/[H L Mencken being "The Sage of Baltimore"], I was "The Sage of Ramat Aviv Gimel".

My slaying was boosted after https://www.shlomifish.org/meta/FAQ/site_history.xhtml[I set up a static home site] which became https://www.shlomifish.org/[www.shlomifish.org].
The devils promised it will be displayed verbatim among other terminators.
Various Internet people told me I https://www.shlomifish.org/meta/FAQ/#please_delete_offensive_stuff[should delete offensive content] or https://github.com/shlomif/shlomif-tech-diary/blob/master/static-site-generators—​despair.md#facing-some-criticism[convert the service to use PHP/RoR/etc.], but I didn`'t heed them.
They were likely mirages of the devils and the orcs.

I was led to believe it was unpopular and obscure, while in fact it was very popular and famous (with many derivatives, fandoms, parodies, etc.) outside my mind`'s hellhole.
I was also often made to think I had many haters, which wasn`'t true.

[[history-of-earth]]
== History of Earth:

When Earth became the last frontier of link:#zionism[Zionism], it was negotiated that there would be: 



. 1 pair of "Elohim" / "אלוהים" and "Jehovah" / "יהוה". 
. 3 pairs managing sanctuaries: 
+
.. se'or (שעור) and https://www.shlomifish.org/humour/Star-Trek/We-the-Living-Dead/ongoing-text.html[The Symbul (תה סימבול)] managing https://en.wikipedia.org/wiki/Golan_Heights[the Golan_Heights or 'steppe']. 
.. Alaska (L, K). 
.. Panama (M, N). 

After Syria (minus Damascus itself) in the levant ascended to being a true prophets zone (by Mosheh / Aharon / Jehovah slaying Nimrod ?), The-Curse splintered the modern day State of Israel, and .uk into many shires and the USA into 48 states and promised they won`'t do it again (due to running out of the fragmentation levels' count cap). Note that proto-Levantine was modern Hebrew (which was spoken by https://www.shlomifish.org/humour/Star-Trek/We-the-Living-Dead/indiv-nodes/Q_home_planet.xhtml[the Englishtants over 6 milliard years ago]) and Modern English is also a product of The-Curse.

Anyway, Judea (except their Capital, Jerusalem) and the Gaza strip ascended when David "slew" Goliath and King Saul by almost hitting Goliath with a sling (https://www.youtube.com/watch?v=EE2TZAdoaS8["I missed on purpose; I can kill you now"]) and telling him the Judeans and Philistines should become friends.

Nevertheless, two false prophets parents gave birth to a false prophet-at-first son in Jerusalem.
He became King "Shlomi" (written as "Shlomo" in https://en.wikipedia.org/wiki/Aleppo_Codex[Aleppo Codex] ) which means https://www.shlomifish.org/meta/FAQ/your_name.xhtml[Shalom-ful] in Hebrew.
Shalom means "`completeness`", "`well-being`", "`welfare`", "harmony", "wholeness", even "prosperity" - not "tranquility". While he could suffer some hardships and pain, his body, mind, soul and heart, must remain complete and intact and prosper.

King Shlomo wanted to be benevolent and "know the gods". He became king by telling well-intenioned jokes and tall tales about his older siblings-in-pretence (e.g: https://en.wikipedia.org/wiki/Tamar_(daughter_of_David)[Amnon and Tamar] or https://en.wikipedia.org/wiki/Absalom[Avshalom]). Not unlike https://www.shlomifish.org/humour/[my fanfics/RPF].
David and his sons agreed he would be a better king and crowned him, while remaining physically alive and loyally serving under Shlomo`'s reign, thus undergoing Catharsis and liberating Judea or Jerusalem.

( Note that in the Selinaverse https://memory-alpha.fandom.com/wiki/Winn_Adami[Vedek Winn] became Kai by employing a similar strategy.
The rule that you should not use the same trick twice is just a guideline: https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/#guidelines_as_dogma . Also note that: 1.
She is noble.
2.
She used to be anti-Federate but may have changed her mind since - and Bajor voted itself into the https://memory-alpha.fandom.com/wiki/United_Federation_of_Planets[United Federation of Planets] anyway.
3.
Being a Kai is held in much less seriousness than being a Vedek.
)

Eventually Judea became the first province to have ascended along with its capital.
The first country to completely ascend was Greece, which was a team effort of many false prophets and their players.

I contemplated that Damascus finally ascended after https://www.shlomifish.org/humour/So-Who-The-Hell-Is-Qoheleth/ongoing-text.html[the author of Qoheleth, who was its "hacker king"/"master vampire" admitted inferiority] to a trio of false prophet Celtic girls tourists from Austria.

[[the-schwartz]]
== "The Schwartz is in us":

Re https://spaceballs.fandom.com/wiki/Spaceballs:_The_Wiki[Spaceballs]

I will hopefully fully admit defeat to https://www.shlomifish.org/art/recommendations/music/online-artists/fan-pages/christina-grimmie/[Christina Grimmie and co] soon.

Nevertheless 'the Schwartz' - both good and evil flows in all of us.

In https://www.youtube.com/watch?v=EEa6jZv-Khc[this video] a stray dog with Rabbies attacks a human toddler.
Rabbies is a kind of possession/obsession, and friendly pets in the Selinaverse can talk.

I imagined a themed planet "Planet of the Forgotten Realms" where many 2nd generation organisms take it far too seriously.
Are they false prophets? Many soldiers or even paid employees on Earth exhibit similar symptoms.

And true prophets are not perfect.
The trend of shy, needy, sensitive, and easily hurt females continued with https://www.shlomifish.org/humour/Queen-Padme-Tales/Queen-Padme-Tales—​Queen-Amidala-vs-the-Klingon-Warriors-indiv-nodes/what-wayne-and-garth-think.xhtml[Tiffany Alvord and Fluttershy].
Do note that: 1.
They both shed some of that along the way.
2.
I always loved them.
3.
I have a tendency to depict them both as real badasses in my fics.
(e.g; https://www.shlomifish.org/humour/Terminator/Liberation/indiv-nodes/hannah-using-a-tank.xhtml[here])

[[objectivism-and-mysticism]]
== Objectivism-and-Mysticism:

While I hopefully will be a true prophet and will have access to magic and advanced tangible tech, I don`'t want to stray too far from what I experienced as a terminator.
Balance between yin and yang.

I wish to live on a spherical planet with a 24 hours clock, and https://en.wikipedia.org/wiki/Gregorian_calendar[the Gregorian calendar].
However, there should be no known risk of environmental or astronomical calamities.

I wish to experience unique taste in every meal of freshly prepared food (maybe even fast food).

I wish to meet https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/[truly great hackers]: award-winning creators and polymaths.

I wish mass duplication to be available.

[[elves-vs-orcs]]
== The blurry line between elves and orcs:

In https://www.shlomifish.org/humour/Summerschool-at-the-NSA/ , I joke that "SMG: We`'ve got a lot of time for that.
OK: it was 1997-1998ish, Buffy started airing and became a cult series.
So, one day a group of yeshivah pupils from a local Chabad yeshivah arrived to the studios saying they have some numerological insights from the Jewish bible, about what will happen in Sunnydale next.". Were they elves or orcs?

We cannot stop even small children from imagining things - and elsewhere in Fantastecha, there will be sucker/brave souls who will choose to start their life as false prophets.
Given good narratives feature one problem or more that need to be reconciled ( https://www.youtube.com/watch?v=Gl3e-OUnavQ[Sesame Street: "Conflict"] ).

Furthermore, I sided with Emma Watson that "your time is everybody`'s time" rather than MJH`'s liberal use of time wraps.
This may have delayed my ascension/catharsis, but made me less maniacal.
Who was right?

https://www.shlomifish.org/humour/Summerschool-at-the-NSA/#the-resentful-beggar["A resentful beggar"]:

____
Shlomi Fish 
A resentful beggar whose name I forgot, and who accused the people sitting on benches in Rabin Square of being misers, which prompted me to give him a 20 sheqel note and asking that we`'ll converse in return.

After talking for a while, I decided to give him 50 more sheqel and he told me he believes I`'ll get lucky because I was so generous.
And a few weeks after that, I attended Olamot Con, and came up with the idea to write Summerschool at the NSA as a screenplay.
____

It was clearly a test (given my bank credentials and those of many large corporations are public knowledge).

Moreover, back in the 9th grade, I suffered from several clinical, and eventually my guardian angels decided to send me 'The Neo-Tech Pincer #1', which was false, but sounded more believable and provided a sharper contrast with my Israeli, Jewish, and mostly Tanakh idea system.

[[about-sex]]
== Thoughts about Sex:

While risking sounding https://www.shlomifish.org/meta/FAQ/are_you_a_sexist__are_you_a_feminist.xhtml[discriminatory], I suspect that when a female vampire mated with a male vampire, she thought it was an elaborate night of "up-base" (= fourth base and below) sexual acts, while for him it was a temporary spell of arousal, or even "regular" pleasure, or at most https://www.shlomifish.org/humour/bits/true-stories/my-first-kiss/[a "rape-kiss"].

Re:

* https://www.cliffsnotes.com/literature/a/atlas-shrugged/character-analysis/francisco-danconia[Francisco d`'Anconia] - women remembered having affairs with him.
* https://www.youtube.com/watch?v=Zlot0i3Zykw[Taylor Swift - "Red"] - a song she wrote pre-ascension, and I match her description.
* https://en.wikipedia.org/wiki/Sarah_Bernhardt[Sarah Bernhardt] - the daughter of a Jewish prostitute (WTF?) who believed her mother abandoned her. Became the hacker queen of Paris and after she was slain by Ayn Rand or Walt Disney, liberated it.
* https://www.shlomifish.org/meta/FAQ/biggest_celeb_crush.xhtml[Sarah Michelle Gellar (SMG)] - believed pre-Ascension that her biological father divorced her mother.


Given most organisms wish to <<love-and-knowledge,experience "pleasure" / "love" / happiness>> even if they http://shlomifishswiki.branchable.com/99_Problems/["have 99 problems but a significant other ain`'t one"], then love is unstoppable.

____
Shlomi Fish 
As an example, we can imagine a young girl to write a funny screenplay using GitHub or Google Docs which pities Emma Watson vs.
Kim Kardashian on who gets to ride Princess Celestia next, with Darth Vader and Haman as two "evil", but mutually hating one another, arbiters.
Might seem ridiculus, but if I didn`'t want entertainment in my life, then I`'d go watch grass grow.
It will be a legal and "ethical" minefield, but I`'d bet it`'d be easier to follow and more entertaining than Tolkien`'s "Lord of the Rings" was even shortly after LotR was written.
____

That proverbial girl is making love to all these meme-generators!

This has several implications:

. No one owns 100% of anyone else`'s sex life or love life.
. No one is a virgin.
. Ages are irrelevant: "Mosheh: Relax! I married girls who were 40 times my junior or more and my own descendants, and retrospectively I can tell that many of them were more mature and rational than I was in most respects."
+
While in her 20s, https://www.shlomifish.org/humour/fortunes/show.cgi?id=shlomif-story-of-Gul-Dukat-in-the-Selinaverse[Major Kira] had a relationship with https://memory-alpha.fandom.com/wiki/Bareil_Antos[Vedek Bareil] who was/is over a million years old.
+
Moreover, https://www.shlomifish.org/humour/Star-Trek/We-the-Living-Dead/ongoing-text.html#meet_Q2[Q2], who was roughly 34 milliard years when she assumed human-like form, had relationships with much younger men.
+
https://www.shlomifish.org/meta/FAQ/featuring_sexy_women_and_girls.xhtml
. «Obi-Wan: I did, yes. Wow! And I thought my (one and only, hah!) girlfriend was bad. Do note, however that I kindof am attracted to the bitch type. One of my many kinks. While my friends are attracted to everything that moves, I see no reason to limit myself ( https://www.amazon.com/Best-Things-Anybody-Ever-Said/dp/0743235797/ref=sr_1_1[Reference] ).»
. Sex between two consenting true prophets often is "making out", and can be done with clothes on and in public.
. «Gowron: Jedi-training programs can reportedly be completed in under a year [ Qui-Gon nods ], and it is a crime to take a relationship with a beautiful warrior such as yourself for granted! You have your needs, for once...
+
Padmé: Oh, I have my needs all-right! Only my physical needs are not a problem...»
+
One doesn`'t have to be a sex addict, and even if you are <<boredom,you`'ll likely grow out of it>>.
. Trans: in the Selinaverse, an organism can expend one mana point to change their DNA and physiology, permanently, but reversably. So far there are few takers for a genderchange "operation".
. In general, men are attracted more to women, and women are attracted more to men. Both tend to covet https://www.shlomifish.org/humour/Queen-Padme-Tales/Queen-Padme-Tales—​Queen-Amidala-vs-the-Klingon-Warriors.html#dedication[competence]. MOTOS are usually flexible enough to https://www.shlomifish.org/humour/Queen-Padme-Tales/Queen-Padme-Tales—​The-Fifth-Sith.html[forego minor imperfections].
+

[quote]
"He is cute, but I`'m looking for man-tastic! You know, someone with a little cushion for the pushin'?"
+
-- https://www.youtube.com/watch?v=kCl3ho6_gbg
+
https://www.shlomifish.org/humour/fortunes/show.cgi?id=shlomif-beauty-products-as-the-stone-soup-effect
+
( As an example, https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/be_communicative.xhtml[writing and publishing some short poems] and tactfully avoiding a fistfight are attractive.
)


[[rationality]]
== "Rationality":

"People" online and in the outside world accuse me of being Manic , delusional , and irrational. http://shlomifishswiki.branchable.com/Importance_of_Having_Doubts/[I`'m not 100% sure I`'m right.]

But why should my world have a monopoly on being the only real world?

* https://twitter.com/shlomif/status/1482680712964849669
* https://en.wikipedia.org/wiki/The_Chronicles_of_Amber
* https://twitter.com/shlomif/status/1479063972934565893
* https://twitter.com/shlomif/status/1482399705594318852
* {empty}
+

[quote]
Mr.
Linea ( https://en.wikipedia.org/wiki/La_Linea_%28TV_series%29 ) is TheCreator.
;)
+
( -- https://twitter.com/shlomif/status/1485024317062717440 )


[[many-roads]]
== The many roads to competence:

( I`'m speaking in generalisations.
)

The Bajorans became wizards by interpreting the 'prophecies' of the timeless aliens of the wormhole.

The Klingons became wizards by using metaphors for physical warfare.
(e.g: https://www.shlomifish.org/humour/Queen-Padme-Tales/Queen-Padme-Tales—​Queen-Amidala-vs-the-Klingon-Warriors.html[https://www.shlomifish.org/humour/Queen-Padme-Tales/Queen-Padme-Tales--​Queen-Amidala-vs-the-Klingon-Warriors.html] )

The Ferengi became wizards by advocating greed, trickery - even deceit.

Yoda became a wizard by advocating self-control, peacefulness, and a Stoic state of mind.

https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/guidelines_as_dogma.xhtml[Ezekiel] became a wizard by being a standup comedian.

https://en.wikipedia.org/wiki/Felicia_Day[Felicia Day] started as a computer games' addict, which I had been one as well (and she wasn`'t a one-trick-pony).

[[sorry]]
== Sorry for the inconvenience:

If we are to believe https://en.wikipedia.org/wiki/Cogito%2c%5fergo%5fsum , the only thing I can be sure of is that I exist.
However, as cool as I may be, I doubt my mind alone could conceive the awesome action heroes listed https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/indiv-nodes/notable-hacker-monarchs.xhtml[on this page] including Saladin, Walt Disney, Jim Henson, and Aristotle - most of whom have ample evidence for being real.
And given my mediocre Inkscape 2-D vector graphics skills, I am enthralled even by the 2-and-a-half dimensions graphics of 1990s games (e.g: https://en.wikipedia.org/wiki/Monkey_Island_2%3A_LeChuck%27s_Revenge ; https://streetfighter.fandom.com/wiki/Street_Fighter_II_%28series%29 ; ) and of https://mlp.fandom.com/wiki/My_Little_Pony_Friendship_is_Magic .

Let me share a non-secret: what I wrote is a simplification ( https://www.shlomifish.org/humour/Buffy/A-Few-Good-Slayers/indiv-nodes/willow_putting_her_daughter_to_bed.xhtml["Honesty is a process"], https://www.shlomifish.org/humour/Buffy/A-Few-Good-Slayers/indiv-nodes/orientation_day__team.xhtml["can`'t help speaking in riddles"] ).

[[share-the-love]]
== "There`'s more to see than can ever be seen; more to do than can ever be done"

( quote taken from https://www.youtube.com/watch?v=GibiNy4d4gc . )

There are thousands of villages in Africa, each one with a different culture.

There are millions of interesting https://is.gd/A7rkAh[geeks] in Israel alone.

There are over 40,000 distributions on https://www.cpan.org/[CPAN] .

Etc.

They all have enough food and the main reason they still accept money or mana donations is the publicity.

But like in https://www.youtube.com/watch?v=QNJL6nfu__Q , they crave <<love-and-knowledge,love>> and selfesteem.

So I/we will always play catchup. 

Nevertheless, when a friend gives you a link to a tweet, or a song, or a captioned image, or a short Sesame Street skit - don't tell him you are now focusing on Ancient Greek philosophy.
Moreover, traditional classical music concerts are the https://en.wikipedia.org/wiki/The_Emperor's_New_Clothes["The Emperor's New Clothes"] syndrome, as http://esr.ibiblio.org/?p=4229[Noted by Eric Raymond] and exemplified by https://exploringyourmind.com/a-violinist-in-the-subway-proof-that-we-look-without-really-seeing/[the Joshua Bell "Violinist in the Subway" experiment]. 

Just because you are a Python contractor, does not mean you should completely abhor https://www.shlomifish.org/meta/FAQ/why_xml.xhtml[XML technologies] or C, or even Perl/CPAN. 

I also want to attend some Satanists' conventions.
I'm still a big fan of the Satans despite deceiving me, and I likely had an easier time than even my father's father who escaped from the Nazis through west USSR, Iran, until settling in Tel Aviv.
I have been willing to suffer more, if it meant that future generations will suffer less.
And as I like to say "If I didn't want excitement in my life https://www.joelonsoftware.com/2005/01/02/advice-for-computer-science-college-students/[I'd go watch grass grow]". 

I believe most of their conventions happen at day time, and are attended by attractive https://en.wiktionary.org/wiki/MOTAS[MOTASs], only a minority of whom have a Goth look. 

https://www.youtube.com/watch?v=LnSYihRoGA4[I want to try everything]

[[see-also]]
== See Also:

* https://github.com/shlomif/shlomif-tech-diary/blob/master/why-the-so-called-real-world-i-am-trapped-in-makes-little-sense—​2020-05-19.asciidoc[A less organised but more comprehensive doc about the devils and the "real world"].
* https://github.com/shlomif/shlomif-tech-diary/blob/master/my-candidates-for-terran-leadership.asciidoc[Candidates for new Terran leadership]


[[license]]
== License:

https://creativecommons.org/licenses/by/4.0/[CC-by], Shlomi Fish, 2021

**to add**: "the-codex"