[id="intro"]
Introduction
------------

I am planning to take a (hopefully temporary) break from being "The [Invisible] Messiah" to catch up with the Earth outside my "brain clouding" illusions. I will not rest on my laurels, but I need both rest and exercise for my mind and body.

So we could use a new leadership.

This is just a suggested starting point. As usual with https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#hacker-monarchs[Messiahs] there will be https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#strategy-for-winning[friendly and supportive competition] (rather than a "dog eat dog" one).

Also note that delegating and trust are key: http://shlomifishswiki.branchable.com/Saladin_Style

[id="appending"]
Appending:
~~~~~~~~~~

*Update:* I give the option of me not stepping down - just appending the good "people" (more like "entities") to the end of the array. From Moses to Shlomif/Rindolf/@EmmaWatson to Christina Grimmie/Fluttershy/Discord:

* Slayer: Christina Grimmie
* Watcher: https://is.gd/rYa3On[Fluttershy]
* Witch/"whicher": https://www.shlomifish.org/meta/nav-blocks/blocks/#mlp_fim_sect[Discord]

[id="slain-by-a-vampire"]
Satisfying the "being Slain-by-a-vampire" requirement
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

*Update:* In https://www.shlomifish.org/humour/Selina-Mandrake/ongoing-text.html , The Guide (Wil Wheaton) notes that "a vampire can only be slain by another vampire." which was a joke, but may have been a quote from The-Codex™. Luckily, the Codex has a  very fuzzy definition (if any) of "vampire". Fluttershy already had https://mlp.fandom.com/wiki/Bats![the vampire nature], and Discord can use his magic to become a vampire.

As for https://en.wikipedia.org/wiki/Christina_Grimmie[Christina Grimmie], having allegedly died, we can pretend that she was resurrected as a vampirella (e.g a la https://www.youtube.com/watch?v=riemZC4J7GE[this] or https://www.youtube.com/watch?v=lQALLGsn-Fk[that] franchises).

Candidates
----------

https://www.shlomifish.org/humour/bits/facts/Summer-Glau/[Summer Glau] (b 1981),
https://en.wikipedia.org/wiki/Christina_Grimmie[Christina Grimmie] (b 1994),
with https://www.youtube.com/watch?v=ZcCp7488puc&lc=UgzuaKhXA8jh_vD5ojp4AaABAg[Grace VanderWaal] (b 2004) and https://www.youtube.com/channel/UC-BK208At_VuA_YUBnNoNjQ[Gabriela Bee] as proteges.

( + https://www.shlomifish.org/humour/Muppets-Show-TNI/Summer-Glau-and-Chuck-Norris.html[Lucky Luke] )

https://muppet.fandom.com/wiki/The_Moopets[The Moopets] as the "evil, bad, guys". UserFriendly.org's http://ars.userfriendly.org/cartoons/?id=20021202[Cthulhu] is welcome too (he's so cute!).

https://is.gd/rYa3On[Fluttershy, Princess of Princesses, head of the secret cabal leadership of the Mossad, the already top secret intelligence agency of the Zionist conspiracy] and her long time companion, https://www.shlomifish.org/meta/nav-blocks/blocks/#mlp_fim_sect[Discord], as the mysterious "Invisibles".

C's `void *` type and https://www.wired.com/2015/11/null/[Christopher Null] as the "void"/emptiness/the "nothing". In addition https://theneverendingstory.fandom.com/wiki/G%27mork and the rest of the nothingers / voiders will remain there. We still need them and love them, even if they cannot be destroyed or filled with love. https://discworld.fandom.com/wiki/Death[Discworld's Death] is so cute too ( ♥ !).

Alpha males: https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#Chuck_Norris[Chuck Norris] (b 1940) ; https://www.youtube.com/watch?v=kCl3ho6_gbg[Jack Black] (b 1969) ; https://www.youtube.com/watch?v=-qTIGg3I5y8[Cookie Monster] (also see https://www.shlomifish.org/humour/Muppets-Show-TNI/Harry-Potter.html ); https://www.shlomifish.org/humour/Selina-Mandrake/cast.html#the-guide[Wil Wheaton] (b 1972). And the token black guy (hah!) https://www.youtube.com/watch?v=af_J2e4r328[Mr. T] (also see https://www.youtube.com/watch?v=7ZsKqbt3gQ0 ).

Alpha females: https://www.shlomifish.org/humour/Queen-Padme-Tales/[Tiffany Alvord] (b 1992), https://www.youtube.com/watch?v=skbnqqzdooo[Alex G / Alex Blue], https://www.youtube.com/watch?v=TnpTcrtsN3U[Ariel Winter] (b. 1998; also see https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/subverting_franchise_copyright_maximalism.xhtml[this] ).

https://www.shlomifish.org/humour/bits/facts/Taylor-Swift/[Taylor Swift] (b 1989), https://www.youtube.com/watch?v=YV5KAbV34NU[Ed Sheeran] (b 1991).

https://www.imdb.com/name/nm0005485/?ref_=tt_cl_t11[Tiffani Thiessen] played Valerie on "Beverly Hills, 90210" ("value tech"). https://www.shlomifish.org/humour/fortunes/show.cgi?id=sharp-sharp-programming-life-according-to-valentine[Valentine Gellar] too for good measure.

https://en.wikipedia.org/wiki/Marvin_the_Paranoid_Android[Marvin the Paranoid Android] .

Local Israeli
-------------

https://www.pri.org/stories/2012-03-09/israeli-rockers-red-band-more-raunchy-muppets[Red Band], https://nextshark.com/maria-miri-domark-instagram/[Miri Domark]

https://www.youtube.com/watch?v=xZLwtc9x4yA[Sugar Zaza]

Message about Fear of Love
--------------------------

OMG! I've realized that I've not only been a successful author and screenwriter and scholar but the freaking emperor of Fantasia ( https://twitter.com/shlomif/status/1403321840018378753 ). I've preached against fear to live and practised it.

But I did have a fear of romantically loving a woman. So, Tiffany Alvord, a male friend and a female friend - please arrive at my apartment. We'll go to a local restaurant for a double date.
