= Reasons why the outside world, as I perceive it, does not make sense, is contradictory, illogical, or is difficult-to-believe-can-be-real

Shlomi
Fish
 <shlomif@shlomifish.org>
2022-05-04

Date: 2021-08-12

From: https://www.shlomifish.org/me/contact-me/[Shlomi Fish]

Source URL: https://github.com/shlomif/shlomif-tech-diary/blob/master/why-the-so-called-real-world-i-am-trapped-in-makes-little-sense--2020-05-19.docbook5.xml[https://is.gd/5gnFvV]

Here are some reasons why the outside world as I perceive it is contradictory, non-sensible, and even illogical.

( Also see https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/[multiverse cosmology v0.4.x document].
)

== The epistemological demons:

We seem to be dealing with epistemological demons.

I exhibit a Descarteseque https://en.wikipedia.org/wiki/Evil_demon[Evil demon] - like situation.
The demon contorts my perception of the outside world, and may input false emotions and some false thoughts, but I still have my centre-of-consciousness (aka "the soul", or "the ego"), logic, reason, and older memories and acquired knowledge, and skills.

I believed reality is what I was told it must be (by decree of "Science" or "common sense") rather than what I *wanted* it to be ( re link:#selinaverse_vision[The Selinaverse vision] ). As a result, the demon increasingly tried to convince me the world was getting worse, and that I was increasingly ignored, isolated, and unpopular.

But I now know it isn`'t and cannot be so.
I want the world and the multiverse as I want them!

I do not wish to http://shlomifishswiki.branchable.com/Self-Sufficiency/[obey this silly non-reality of yours any more].
I intend to https://www.youtube.com/watch?v=f4Mc-NYPHaQ[break free] and to be in the company of all the people I`'ve known and loved.

Prior art for my situation:

* https://www.shlomifish.org/humour/Selina-Mandrake/#sources_of_inspiration["Selina Mandrake - The Slayer"] - Selina gets sucked into slaying vampires
** https://en.wikipedia.org/wiki/Labyrinth_%281986_film%29[Labyrinth] - Sarah deals with the Goblins.
** https://en.wikipedia.org/wiki/Buffy_the_Vampire_Slayer[Buffy the Vampire Slayer] - Buffy Summers gets sucked into a demonic underworld
** https://en.wikipedia.org/wiki/The_Hobbit[The Hobbit] - Bilbo is drawn out of his comfort zone
* https://en.wikipedia.org/wiki/The_Truman_Show[The Truman Show] - the perceived reality is wrong. 
** https://en.wikipedia.org/wiki/The_Prisoner[The Prisoner]
** https://en.wikipedia.org/wiki/The_Matrix[The Matrix]
* http://www.earthstar.co.uk/deep3.htm[H2G2`'s Planet Earth as a Computer]
+

[quote]
"I speak of none other than the computer that is to come after me," intoned Deep Thought, his voice regaining its accustomed declamatory tones.
"A computer whose merest operational parameters I am not worthy to calculate - and yet I will design it for you.
A computer which can calculate the Question to the Ultimate Answer, a computer of such infinite and subtle complexity that organic life itself shall form part of its operational matrix.
And you yourselves shall take on new forms and go down into the computer to navigate its ten-million-year program! Yes! I shall design this computer for you.
And I shall name it also unto you.
And it shall be called -- The Earth." 
* https://www.shlomifish.org/humour/fortunes/show.cgi?id=god-and-his-angels-as-technicians[God and his angels as implementing humans' perception of the universe] - an allegory
* https://en.wikipedia.org/wiki/Invasion_of_the_Body_Snatchers[Invasion of the Body Snatchers] - my chat friends become inhuman.
* https://www.youtube.com/watch?v=gdbh6GUJ5XY[Pirates of the Caribbean: Ghost story] - food tastes the same (despite proclamation of being freshly made).
* https://en.wikipedia.org/wiki/Rashomon_effect[the Rashomon effect] - different observers observe different realities. 
* https://en.wikipedia.org/wiki/Pascal's_wager[Pascal`'s Wager] - if I stay in the "real-world" hell, then Christine Grimmie, Jim Henson, Avicii, John Lennon, Walt Disney, Saladin, Maimonides, my grandparents, even Moses and Nimrod will have perished, and so will I. 


[[evidence-that-this-hell-isnt-real]]
== Evidence that this hell is not real

[[more-thoughts]]
=== More thoughts:

In this meditation, I am starting from accepting the assumptions that 1) the world, as I perceive it, is real, and - 2) there is no entity capable of employing super-natural "magic" effects that will either make me perceive it in a different way, or actually change it to make it less scientifically acceptable.
I will try to show why accepting them and the media "facts" will result in having to reject them ( https://en.wikipedia.org/wiki/Reductio_ad_absurdum[Reductio ad absurdum] ). 

* https://www.explainxkcd.com/[xkcd] had some RPF (= https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/["Real Person Fiction"], e.g: https://www.explainxkcd.com/wiki/index.php/406:_Venting["`xkcd #406: Venting`"] ), and my https://www.shlomifish.org/humour/Summerschool-at-the-NSA/[Summerschool-at-the-NSA screenplay] was well-received on https://www.reddit.com/r/xkcd/[/r/xkcd] and elsewhere. Nevertheless, later on I was told "RPF? Never do that!" on an xkcd IRC chatroom, and was promptly banned.
* "People" online are afraid of http://shlomifishswiki.branchable.com/Encourage_criticism_and_try_to_get_offended/[critics and contrarians] and yet sadistic enough to ban non-spammers.
* It is not clear whether bigger muscles imply that a person is physically stronger or not.
** https://www.youtube.com/watch?v=CEpkmoCBPkM["`Strength comes in all shapes and sizes and this young lady is proof of that. Watch "`Lovely Joy`" lifting a few times her own weight for your daily dose of gym motivation!`"]
** A typical Gorilla is far stronger than even the strongest humans, while not exercising. 
* https://twitter.com/TheRealGrimmie[Christina Grimmie] was reportedly killed after several years of not doing stuff her way. This is despite advocating confidence and individualism, in her works. 
** Despite her reported assassination, many people online and in the outside world claim they have not heard of her. 
** Grimmie is/was my favourite YouTuber. Cannot be a coincidence. ( https://www.shlomifish.org/art/recommendations/music/online-artists/fan-pages/chris-grimmie/[Reference] ) 
** Others with bad outcomes: https://www.shlomifish.org/humour/bits/facts/Summer-Glau/[Summer Glau], https://www.shlomifish.org/meta/FAQ/biggest_celeb_crush.xhtml[Sarah Michelle Gellar (SMG)], https://en.wikipedia.org/wiki/Jennifer_Aniston[Jennifer Aniston] , https://en.wikipedia.org/wiki/John_Candy[John Candy] , https://en.wikipedia.org/wiki/Beverly_Hills_Ninja[Chris Farley] , https://www.imdb.com/name/nm0504516/[Ron Lester], https://en.wikipedia.org/wiki/Jim_Henson[Jim Henson], https://en.wikipedia.org/wiki/Ayn_Rand[Ayn Rand].
* I am a feeble and frail man (who is otherwise of strong spirit), and who is attracted to strong girls, especially physically strong and/or muscular ones: https://twitter.com/shlomif/status/1394689324554334210[Reference: tweet] .
* I "pirate" (= copy, share, and build upon) copyrighted works all over the place. I`'ve been told https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/fighting_against_the_world.xhtml[it is bad and even "unethical"] or that FOSS / open content / free music / commercial fan-fiction will "never happen".
** https://www.shlomifish.org/meta/FAQ/how_would_you_feel_if_your_own_intellectual_works_were_stolen.xhtml["`Shlomi Fish`'s FAQ - So you support and advocate distributing copyrighted works, and commercial fan-fiction / fan-art? That is theft! How would you feel if your own intellectual property were stolen?`"]. 
* I think that commercial fan fiction not only will be ethical, but is necessary: https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/["`The Case for commercial fan fiction`"]
* "Science" is often a device to enforce external authority and "truisms" and "facts". Just like religions, if not worse: https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/guidelines_as_dogma.xhtml["`Guidelines as dogma`"] .
* People online are often getting hurt over pettier and pettier things, instead of http://shlomifishswiki.branchable.com/Encourage_criticism_and_try_to_get_offended/[encouraging criticism].
* I think "mass production" (more like "mass duplication") has been done using magic and Extra-terrestrial technology (called e.g https://buffyfanfiction.fandom.com/wiki/Q_Continuum_%28Selinaverse%29["`The Q Continuum`"] ) given large factories, farms, and trucks/etc. make everyone who work there miserable (and are often biological hazards). Moreover, they are underpaid.
+
It is also seems incredibly farfetched to believe that there are enough Cocoa Beans to accommodate for the world`'s supply of chocolate and its by-products.
( https://www.tastingtable.com/1333012/how-many-cocoa-beans-one-chocolate-bar/[It takes 90-to-120 cocoa beans to make a 100 gram bar of milk chocolate.] ) 
+
And then there's oil, coal, natural gas, sugar, milk, wheat, rice, copper, iron, gold, silver, https://en.wikipedia.org/wiki/Rare-earth_element[rare-Earth elements], corn, helium, apples, other fruit, almonds ( Reference: https://www.thespruceeats.com/green-almonds-2216444[Green, "`raw`", almonds] ) 
** => The Q Continuum can duplicate or conjure energy, precious minerals, raw materials, inanimate products, foods and drinks, organisms (e.g: https://www.shlomifish.org/humour/fortunes/show.cgi?id=sharp-sharp-programming-life-according-to-valentine[Life According to Valentine] and https://memory-alpha.fandom.com/wiki/Thomas_Riker[Thomas Riker]), or even entire galaxies.
** => The media keeps saying that there`'ll be shortages of certain products, but they do not happen.
** It is unreasonable to assume we can distribute so many food and other products across north America, Europe, Asia, the Middle East, etc. using only trucks and Boeing/etc. aeroplanes. My neighbourhood ( https://en.wikipedia.org/wiki/Ramat_Aviv_Gimel[Ramat Aviv Gimel] ) only has one-and-a-half automobile roads leading into it. 
** There are many byproducts, bybyproducts, derivatives, mashups/mixes: chocolate, chocolate icecream, cakes, kitkats / mars / snickers. 
* I think there has been a conspiracy of the demons inside me to try to convince me that the world outside me was getting worse, and that I was more and more isolated, friendless and unpopular. Well, game over - I won - you will lose!
* There are thousands' years old hackers and below-20 ones who are huge fans of one another: https://www.shlomifish.org/humour/Star-Trek/We-the-Living-Dead/indiv-nodes/kai-blanche.xhtml["Meet Kai Blanché"] .
* It is possible yada` (= "to know" in Hebrew) meant "to educate / to entertain" and involves pleasure, but sometimes pain too, and was mutual, and always spawns ( possibly invisible ) baby angels. If it makes you bored or indifferent, it likely is not effective. https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/[Reference: "`The case for commercial fan fiction`"]
* I had a very short haircut for many years now and given many girls have many "bad hair days" (re https://www.shlomifish.org/humour/Muppets-Show-TNI/Harry-Potter-indiv-nodes/the_beautiful_assistant.xhtml["`The beautiful assistant`"] and https://www.youtube.com/watch?v=8N2k-gv6xNE ) think they may wish to follow suit: https://www.refinery29.com/en-us/2021/03/10365754/emma-watson-bob-haircut-2021["`Emma Watson Has New Short Bob Hair Cut In LA For Spring`"]. That page was published a day after I wrote https://www.shlomifish.org/humour/fortunes/show.cgi?id=shlomif-beauty-products-as-the-stone-soup-effect["`Beauty Products as the Stone Soup/Placebo Effect`"]
* Per https://twitter.com/shlomif/status/1173621519274127361 "I love the film Labyrinth. it was so funky and nice and David Bowie was great and Jennifer Connelly was so touching and maybe could have taken the Oscar if there was no prejudice against her youth and the fact it was a fantasy/children film back then.". Jennifer Connelly likely was nominated and won (and it may not have been an age record).
** => Emma Watson may have won the Oscar for some of the Harry Potter films: https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/bad_acting_emma_watson.xhtml["`'`Bad`' Acting: Emma Watson`"]
** => Arnold Schwarzenegger likely won it as well: https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/bad_acting_ftw.xhtml["`'`Bad`' Acting for the win`"]
* Terran science was an epistemological facade (Faster-than-light travel, duplication of galaxies, the https://en.wikipedia.org/wiki/Akashic_records[Akashic_records] are all possible). However it turned out to be a blessing in disguise, because many Terran scientists and engineers and developers were highly concerned about efficiency and reliability and other kinds of https://github.com/shlomif/shlomi-fish-homepage/blob/master/lib/notes/quality-software--followup-2018.md[quality]. See e.g. http://www.h-online.com/open/features/Is-Microsoft-running-out-of-steam-1102654.html[the variations on the James Watt`'s steam engine].
** => Extraterrestrial technology, although advanced (but naturally not https://www.shlomifish.org/philosophy/philosophy/putting-all-cards-on-the-table-2013/#we_all_have_a_master[omnipotent]) was incredibly wasteful. As a result, Earth became a hub for technology - both tangible and intellectual and lately digital as well.
* As a child, I wanted to be good-hearted (= noble, honest, benevolent) and later on aspired to be world savior / messiah / "the greatest person in history". I guess "nice guys finish last".
* It is not clear why we have to suffer from https://en.wikipedia.org/wiki/Consumerism[Consumerism] of large electrical appliances (e.g: washing machines, dishwashers, and refrigerators) when they *can* be made more reliable (like those that had been in the past).
* I have a very low number of Twitter followers (below 650 - https://twitter.com/shlomif ) and my reddit posts are usually not upvoted a lot ( https://www.reddit.com/user/shlomif ) . This is despite some of my older posts being a staple on Slashdot and other sites (e.g: https://www.shlomifish.org/humour/bits/Mastering-Cat/["Mastering cat" Interview].)
* People cite contemporary copyright law as a justification for censorship:
** https://www.reddit.com/r/Jennamarbles/comments/mjfmsj/advice_to_jenna_1_youre_awesome_i_love_you_2/["`Advice to Jenna: 1. You're awesome. I love you. 2. "Racist" humour is OK. 3. You don't have to absolutely do what you think you must. : r/Jennamarbles`"]
** https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/["`The Case for commercial fan fiction`"]
** https://www.shlomifish.org/philosophy/case-for-file-swapping/["`The Case for File Swapping`"]
* I lost contact with many online friends due to discontinues of IM services and me not receiving their email/etc replies. The devils are clouding my perception of the world using https://twitter.com/shlomif/status/1395025361138761729[my media].
* Most people I see on the streets in my neighbourhood, are clearly zombies. 
** Many people I try to talk to in English claim they do not know it. This is despite the fact that https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/#ramatavivgimel[Ramat Aviv Gimel] is an afluent area, and there are many foreign workers (filipinos, Thais, Indian, Sri-Lankan, etc.) there who do not speak Hebrew well. 
+
On E-mail, http://linuxmafia.com/%7Erick/[Rick Moen] told me Israelis`' knowledge of English is only exceeded by the Dutch ("Netherlands"). 
* We went from killing women to raping them to sexual harrassment. Some say one cannot even compliment a woman for her looks.
* The other day I was talking with a friend about https://en.wikipedia.org/wiki/J._K._Rowling[JK Rowling] as a role model and the following day she said JKR was evil since she opposed https://en.wikipedia.org/wiki/Transgender[Transgender] people (which I do too).
** => The same thing happened with https://en.wikipedia.org/wiki/Joss_Whedon[Joss Whedon]'s alleged "`sexual harassment`" claims. ( also see https://en.wikipedia.org/w/index.php?title=Buffy_studies&oldid=1022301852[Buffy studies] for his remarkable advancement of feminism ).
* People are opposed to the fact that sexual attractiveness strongly correlates with competence:
** https://www.shlomifish.org/humour/image-macros/indiv-nodes/say_no_to_an_alpha_female.xhtml[Shlomif`'s Memes - One does not simply say "`no`" to an Alpha Female]
** https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#meaning-of-able-competent["`Putting Cards on the Table (2019-*) - What do "able" and "competent" imply?`"]
** https://www.shlomifish.org/me/resumes/Shlomi-Fish-Resume-as-Writer-Entertainer.html[Shlomi Fish Resume as Writer Entertainer]
* People become non-responsive on social media:
** https://slashdot.org/submission/13002768/queen-padm-amidala-tales-star-trekstar-warsreal-world-crossover[Slashdot sumbission: queen padmé amidala tales star trek star wars real world crossover]
* People https://github.com/shlomif/shlomif-tech-diary/blob/master/about-censorship.asciidoc[censor me] saying https://www.youtube.com/watch?v=UF4_WnXhHFM["I Would Not Say Such Things If I Were You"] rather than http://shlomifishswiki.branchable.com/Encourage_criticism_and_try_to_get_offended/["why, thank you"]
* There are many one song guest performances in longer live shows. E.g:
.. https://www.youtube.com/watch?v=edV1Px8NHk4[Rolling Stones - with Lady Gaga　"Gimme Shelter"　@ Newark, N.J. 15/12/12 - YouTube]
.. https://www.youtube.com/watch?v=eZgc8-ry3rc[Taylor Swift Ft. Sara Bareilles - Brave (DVD The RED Tour) Bônus - YouTube]
.. https://www.youtube.com/watch?v=YMD_L8IDZnc[Ozzie Osbourne at 4m59s]
.. https://www.youtube.com/watch?v=FFm1kxvSus8["Jessie J and Tom Bleasby singing Flashlight - YouTube"] - on the Ellen Generes show. 

+
Would they travel by plane/automobile for 10 minutes? 
+
Moreover, "Stutz" ["סטוץ"], an Israeli dating gameshow used to match teenagers from distant towns. 
* => I adore https://www.shlomifish.org/meta/FAQ/biggest_celeb_crush.xhtml[Sarah Michelle Gellar (SMG)], but learned of https://www.reddit.com/r/IAmA/comments/1z4nu6/i_am_sarah_michelle_gellar_also_known_as_the_girl/[her reddit IAmA] only when it was too late.
* https://twitter.com/shlomif/status/1418433188091793412["If you`'re the smartest person in the world - you are in the wrong world."]
* "People" online are afraid of hearing contrasting views, yet are often cruel enough to block/ban/devoice contrarians. http://shlomifishswiki.branchable.com/Encourage_criticism_and_try_to_get_offended/[Encourage criticism].
* A correspondent told me that "[a flat] 100% of the https://en.wikipedia.org/wiki/Aleppo_Codex[Aleppo Codex (the Hebrew Bible)] is crap." Then I gave https://biblehub.com/parallel/1_kings/20-11.htm as a counterexample, and there was no commentary for it in a site of atheist objections.
* https://twitter.com/shlomif/status/1407204486985175043
* The latest obsession of 'geeks' with Japanese culture is a mirage of the fuckers done to make me feel unpopular: https://youtube.com/watch?v=xZLwtc9x4yA ; https://shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/["`The Case for commercial Fan-fiction.`"]
* Likewise with the 'Asperger syndrome': https://shlomifish.org/meta/FAQ/asperger_syndrome.xhtml ; obesity ; environmental issues ; etc.
* arduino is a mirage of the devils just like Angular / react.js and bitcoin and discord.gg .
* Why did https://twitter.com/shlomif/status/1357258591498100736[Monty Python and Python-Lang cross streams] only on 2021? Has @EricIdle been living under a rock?
* "People" are afraid to live: told me there is risk when https://github.com/shlomif/MeToo-me-too[invoking the #MeToo tag]; told me I should not approach people on the street.
* Electrical / Internet / water / gas / etc. wiring happens by magic.
* Many classics are needlessly long and repetitive, e.g: https://en.wikipedia.org/wiki/Aleppo_Codex[Aleppo Codex]
+
The canonical https://en.wikipedia.org/wiki/Hebrew_Bible[Tanakh
(+++=+++ Hebrew Bible)], Plato`'s https://en.wikipedia.org/wiki/Republic_(Plato)[Republic], Tolkien`'s https://en.wikipedia.org/wiki/The_Lord_of_the_Rings[Lord of the
Rings], Ayn Rand`'s https://en.wikipedia.org/wiki/Atlas_Shrugged[Atlas Shrugged], Dostoevsky`'s https://en.wikipedia.org/wiki/Crime_and_Punishment[Crime and
Punishment] , Shakespeare`'s https://en.wikipedia.org/wiki/Shakespeare%27s_plays[Plays], etc.
have likely undergone lengthening and mutation by the Orcs.
However, often the originators liked the mutated versions better. 
* {empty}
+

____
"`Oh, it was definitely an instructive service.
However, there was one thing which bothered both me and my late comrades: they kept lecturing to us how bad the Enemy was, and why we must fight it.
I think half of our training time was wasted on such lectures.
We knew the Enemy was bad, and that was the reason why we joined the Organisation in the first place!

In my opinion, it was completely unnecessary.
Perhaps they thought that without those brainwashes we would have reached the conclusion that there is no rationale behind the activity against the Enemy.
Most of us reached that conclusion a few months, if not less, after we joined the Organisation and we still kept fighting.
So they didn`'t have a reason to go to this length and just bother us.`"
____
+
-- https://www.shlomifish.org/humour/TheEnemy/The-Enemy-English-v7.html
* Microbiology is a pseudoscience - most of its processes are unexplained.
* The terrestrial food supply cannot/could-not scale so well. 
+
we cannot reasonably distribute so many food products all over USA, Europe, Asia, Israel, etc.
without magic. 
* I have fanfics featuring Emma Watson - https://www.shlomifish.org/meta/nav-blocks/blocks/#harry_potter_sect[Emma Watson fan-fiction]. She can film them, or similar fanstories and screenplays written by other writers. But she allegedly hasn't made a film in years. Moreover, despite all that, everyone are talking about her
* Tiffany Alvord`'s manager told me she wants to record original songs, but she hasn`'t uploaded either them or covers.
* Occam`'s Razor tells me there`'s a conspiracy-- https://www.shlomifish.org/art/recommendations/music/online-artists/fan-pages/chris-grimmie/[https://is.gd/kSLGdP]
* Someone on freenode told me my site is a "waste of space" even though:
.. https://mirrors.edge.kernel.org/pub/linux/kernel/ is far more "`wasteful`"
.. https://en.wikipedia.org/wiki/Nazi_book_burnings[Nazi book burnings]
.. https://www.goodreads.com/quotes/17802-where-they-have-burned-books-they-will-end-in-burning[Where they have burned books they will end in burning human beings]
.. https://www.chabad.org/library/bible_cdo/aid/16186[Yonah / Jonah: "how come you have shown mercy for the kikayon plant, and I won't show mercy for a Ninveh, the large city?"]
* https://www.youtube.com/watch?v=kYX8sjIzjGw[Christina Grimmie`'s song "Feelin' Good"] views' count has been stuck below 4 million.
* I also suspect that Christina Grimmie, many other fellow entertainers / creators, and the universal defence community cooperated reluctantly ( "`OK, OK. Tell you what? I`'ll play along.`" ). Nevertheless, the introes and outroes of Grimmie`'s videos, and also those of other artists I liked (e.g.: https://www.tiffanyalvord.com/[Tiffany Alvord] ) contain many cuts, likely because they were lying to me.
* My 9th grade literature teacher told us that https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/learning_more_from_inet_forums.xhtml[philosophy / philosophising] was bad! 
* I saw badly photoshopped people on the streets while I was walking outside. 
* Some technologies are too complicated for a human to understand, much less to implement: e.g: C++, CSS 3.x, ghc, Common Lisp https://twitter.com/shlomif/status/1428991948803776512[Reference]. 
* https://www.shlomifish.org/Files/files/images/hostgator-no-python3.png[HostGator removing python v3 and requiring v2.7.5 (!)]
* The local synagogue and the https://en.wikipedia.org/wiki/Ramat_Aviv_Mall[Ramat Aviv Mall] look bigger on the inside. 
* https://en.wikipedia.org/wiki/Emma_Watson[Emma Charlotte Duerre Watson] (also see https://www.shlomifish.org/meta/nav-blocks/blocks/#harry_potter_nav_block[my fanfics of her] ) was born a day after https://www.shlomifish.org/meta/FAQ/biggest_celeb_crush.xhtml[Sarah Michelle Gellar (SMG)]'s 13th birthday. "Emma" means "complete" in proto-Germanic, not unlike https://www.shlomifish.org/meta/FAQ/your_name.xhtml["Shlomi" [+++=+++ "shalom-ful"]]. "Eymah" means 'terror' in Hebrew, while "Em" means "mother". "Sarah" means "a [female] minister" or "a ruler". "Charlotte" is cognate with both "Sarah" and "Shlomi" and also means "a ruler". 
+
So it is likely that she was conceived as a bridge between SMG and me. footnote:[There may have been hopes to get SMG to terminate me before me hitting
puberty on 5 May 1990 [= my 13th birthday].]
** Emma Watson`'s https://en.wikipedia.org/w/index.php?title=Emma_Watson&oldid=1223309727[terrestrial wikipedia page] implies she is a workaholic, who still had time-to-pose for many "nudes" (despite having been a self-proclaimed "feminist"). She also did not star in a film role since 2019, despite the fact I (and others) wrote screenplays featuring her. 
* There are many battery-powered speedy self-moving vehicles [e.g: electrical "קורקינטים"] whereas it takes a very large terrestrial battery to have as many joules as a tablespoon of peanut butter. 
* https://www.today.com/pets/hundreds-golden-retrievers-met-scotland-150th-anniversary-breed-t133915["Hundreds of golden retrievers met in Scotland for 150th anniversary of breed"] - no way can you fly so many (over 300) in Boeing/etc. planes, or even drive them by automobiles. Moreover, many Scotland roads have a single lane, with pass-by road-widening extensions. 
* I have a supposedly younger cousin called "Shlomi" despite our Jewries' unwillingness to name newborns after living relatives. 
* As a false prophet child, https://www.shlomifish.org/meta/FAQ/where_are_you_from.xhtml[my template was relocated] three times before he was 6, despite common wisdom that one should not relocate young children. This was probably due to the effect of The Muppet Show and other television series on the Terran hellholes and my parents' wishes to have more children. 
* The freenode / 'libera.chat' split is hard-to-believe. 
* Apple M1 is hard-to-believe: 
.. ARM is underperformant while having low gates' count and power consumption. 
.. yet, Apple added an x86-64 emulation, which wastes gates and power! 
* Boeing 747/etc. aeroplanes are so heavy that they can only fly **by magic**. 
** Same for https://en.wikipedia.org/wiki/Honey_bee[honey bees]. 
* At one point close to 2020, I drank so little for many days, that I should have died of water deprivation. 
* I survived biting an Oak acorn (as a child) despite https://en.wikipedia.org/wiki/Guns,_Germs,_and_Steel[Guns, Germs, and Steel]'s claim that acorns contain poison. 
* The third-reich nazis could not have remained motivated to kill so many people. 
** Likewise for the https://www.shlomifish.org/humour/bits/facts/NSA/[NSA], many terrorist/activist organisations, militaries, low-paying jobs. 
** The Gazan Hamas is at war with Israel, to free the Hamas-men imprisoned in Israel, which causes Israel to bomb the Gaza strip and kill many more people. 
** {empty}
+

____
Pacifists may be disappointed, but after (and if) the rest-of-days, there`'ll still be wars.
Civilian wizards can optoutof Earth`'s warzone layer, and it's safe. 

One does not need good excuses for taking parts in wars, just like one doess need them to play Chess/Checkers/Street-Fighter/etc. 
____
+
Such games are often fun and educational.
Love and Knowledge. 
* There is a high-performance chess engine, written in C under GPL/AGPL. One developer maintains an enhanced fork of it, of which he privately gives binaries, only after lengthy background checks (a grand waste of time/energy/love). 
* Android could not have been developed so quickly without using GNU and/or iPhone's source code. 
* In this hell, I have received very few PayPal/etc. donations, and few people have published critiques of my sites' pages online. This is despite many voicing them on online chats. 
* "`People`" keep reporting https://www.shlomifish.org/meta/FAQ/#broken_links[broken links on the webpages of my websites], while the owners of the websites to which they point are not responsive to my requests to restore them. https://www.shlomifish.org/humour/fortunes/show.cgi?id=sharp-perlcafe-misplacing-a-website["How the hell does one misplace an entire website?"]
** There are many youtube-blocks, youtube takedowns, reddit blocks, broken links in static/etc. websites, placing resources behind a login wall or a pay wall. They likely affect only me. https://www.shlomifish.org/humour/fortunes/paul-graham.html#paul-graham-democracy-and-wikipedia[Paul Graham about free WWW resources:]
+

[quote]
The second big element of Web 2.0 is democracy.
We now have several examples to prove that amateurs can surpass professionals, when they have the right kind of system to channel their efforts.
Wikipedia may be the most famous.
Experts have given Wikipedia middling reviews, but they miss the critical point: it`'s good enough.
And it`'s free, which means people actually read it.
On the web, articles you have to pay for might as well not exist.
Even if you were willing to pay to read them yourself, you can`'t link to them.
They`'re not part of the conversation. 
* https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/starved_of_employees.xhtml[RIAA's youtube-dl takedown request] exhibited both technical and legal competency, and complete naivity about the power of git-scm, the Internet, etc. 
* The amount of hatred / prejudice / ad-hominemry "people" have against the techs listed on https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/guidelines_as_dogma_intro.xhtml["`guidelines as dogma`" intro] and https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/geeks_and_hackers_are_cool.xhtml[geeks and hackers are cool.xhtml] and https://www.shlomifish.org/meta/FAQ/[Shlomi Fish`'s FAQ] are immense. 
* https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/hollywood_screenplay_format.xhtml[Hollywood`'s mandated screenplay format] - finicky and boring. Would never have been tolerated by screenwriters, who were/are geeky and hackery.
* "People" with whom I chat online find poor excuses not to peruse my recommendations: 
** "I'm now focusing on Ancient Greek philosophy" 
** "There's still a lot I don't know about Ruby-on-Rails" [as if one can learn it all!] 
* I suspect the reason that Christina Grimmie`'s introes/outroes had so many videos' interruptions is that they were lying to me: https://www.shlomifish.org/art/recommendations/music/online-artists/fan-pages/chris-grimmie/[Reference: [my] Christina Grimmie fan page] . Occam's Razor tells me there *is* a conspiracy. 
* E-mail / blogs / etc. spam should have been stopped by karma (= "what goes around, comes around"). https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/#all_people_are_good[Case for Commercial fan-fiction: all people are good]
* In the Russia-Ukraine war, the Russians are stupid enough to keep using tanks. 
* https://en.wikipedia.org/wiki/Alexandre_Dumas[Alexandre Dumas pere] had 40 affairs. 
* https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/bad_acting_arnie.xhtml[Arnold Schwarzenegger] reportedly started his acting career when in his 40s. Ageism aside, the real reason was his template`'s secret history as one of https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/#history-lesson-about-the-muppeteers[The Three [Head] Muppeteers]. 
* https://www.youtube.com/watch?v=Zlot0i3Zykw[Taylor Swift - "Red"] - I match her description, and as of 2023-11-13 my sex-life has amounted to https://www.shlomifish.org/humour/bits/true-stories/my-first-kiss/[one, brief, kiss] . 
* It is likely that https://en.wikipedia.org/wiki/Egyptian_pyramids[the Egyptian pyramids] and the https://en.wikipedia.org/wiki/Mesoamerican_pyramids[Mesoamerican pyramids] were constructed using magic. 
* Many people to whom I wrote, have not replied to my messages, or requests. 
+
This is despite https://www.shlomifish.org/humour/fortunes/show.cgi?id=smg-about-giving-back-money-and-time[Sarah Michelle Gellar`'s quotation about giving back money and time]
* Videos are removed, blocked, or otherwise censored from my YouTube based on apparent whim. ( https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#YouTube[Reference] . ) 
* I suspect https://bigbangtheory.fandom.com/wiki/Sheldon_Cooper[Sheldon Cooper], whose first name is cognate with mine (= "`Shlomi`"), was in part an exaggerated parody of me at the time. Like him, I tried to reconcile my contemporary ideology with link:#terrestrial[terrestrial] science and "consumerist" culture. That was evident from my contemporary writings, e.g.: 
** https://www.shlomifish.org/philosophy/the-eternal-jew/[The Eternal Jew]
** https://www.shlomifish.org/humour/human-hacking/[The Human Hacking Field Guide]
** https://www.shlomifish.org/humour/Star-Trek/We-the-Living-Dead/[Star Trek: "`We, the Living Dead`"]

+
Having read https://en.wikipedia.org/wiki/Sheldon_Cooper[Sheldon`'s wikipedia page] , it seems he resembles me in many ways.
Seems like he was conceived as a parody of me. 
* Many friends and classmates shared a private name with others and a family name with others too. They were likely conceived as bridges or proxies. 
** It is hard-to-believe there were so many peasants in previous centuries of history, who begot so many present celebrities. 
* Often, when I wrote about an insight online, people seem to know about my previous whereabouts (even if tangential) and "`stalked`" me. 
* I have no coherent memories since before the 1st grade ("Kitah Aleph", `"כיתה אלף"`) in Ramat Aviv Gimel school in Israel, when I was 6-7 years old. This is while two younger sisters had been born then, (and was told I reacted to their presence) and I was moved from Dallas, Texas to Rockville Maryland, to Ramat Aviv Gimel. 
+
https://www.shlomifish.org/meta/FAQ/#how_did_you_learn_english[Shlomif's FAQ: How did you learn English? ]
+
I also seemed to possess some significant inherent knowledge of Modern Hebrew and Modern English. 
* It seems farfetched to believe that https://www.shlomifish.org/philosophy/psychology/why-openly-bipolar-people-should-not-be-medicated/[psychiatric drugs will help in preventing depressions, hypo-manias, manias, etc.] yet many people support the media position. 
** Theses drugs have to be bitter, because otherwise they won't be considered medicine, right?! 
* https://en.wikipedia.org/wiki/William_Jennens[The Jennens vs. Jennens] court-case supposedly took-over-a-century and wasted a lot of money. In actuality, the two sides split the money 50-50. The case began as a relic in hells of some vampires. But they received enough additional money-to-keep the show afloat. It was a parody court-case that exercised the functionality-of-the-real-legal-system. 
** https://en.wikipedia.org/w/index.php?title=Smartphone_patent_wars&oldid=1224319910[the Smartphone patents`' wars] are a facade for smartphone vendors pointing out flaws, features, and misfeatures in each other`'s products. There is little money at stake, and no bans. 
* Lately, blogging and chatting online has become an obstacle race of censored resources, resources that require registration or payment, broken links, links that are deemed non-free by FLOSS zealots, etc. https://www.shlomifish.org/humour/fortunes/paul-graham.html[Paul Graham had written about that years ago:]
+

[quote]
The second big element of Web 2.0 is democracy.
We now have several examples to prove that amateurs can surpass professionals, when they have the right kind of system to channel their efforts.
Wikipedia may be the most famous.
Experts have given Wikipedia middling reviews, but they miss the critical point: it`'s good enough.
And it`'s free, which means people actually read it.
On the web, articles you have to pay for might as well not exist.
Even if you were willing to pay to read them yourself, you can`'t link to them.
They`'re not part of the conversation. 
* Many open-source-software projects,  or websites/blogs/etc. have seemingly been abandoned by their originators and maintainers. "`You divorce wives, not children -- https://en.wikipedia.org/wiki/Clueless[Clueless].`"
** https://en.wikipedia.org/wiki/Npm[npmjs]
**
+
[source]
----

$ cargo install-update -a

    Polling registry 'https://index.crates.io/'......

Package       Installed  Latest   Needs update
bat           v0.24.0    v0.24.0  No
cargo-update  v13.4.0    v13.4.0  No
cbindgen      v0.26.0    v0.26.0  No
fd-find       v10.1.0    v10.1.0  No
hexyl         v0.14.0    v0.14.0  No
ripgrep       v14.1.0    v14.1.0  No

No packages need updating.
Overall updated 0 packages.
----
+
Rust-lang is supposedly a very trendy language currently! 
* Why are there so many copyright takedown requests? As far as the copyright holders or the lawyers acting on their behalf are concerned, they are a waste of time, love, and often -- money. 
* Seems like I am not the only man who, as a general rule, dislike seeing women naked, and rather see them in bikini/lingerie ("`scantily-clad`") https://www.reddit.com/r/unpopularopinion/comments/1deuq21/women_look_way_better_in_a_bikinilingerie_than/["`women look way better in a bikini/lingerie than completely naked. : r/unpopularopinion`"] . However, one allegedly needs to be naked to "4th-base" (or is it "home-run"). Moreover, people pee from penises and vaginas! 
* In https://www.shlomifish.org/humour/fortunes/show.cgi?id=when-closed-source-bites[this IRC convo] someone keep defending the fact that Firefox, is in some aspects, superior to Opera because it is open-source, changing his arguments and evading mine. 
+
( Possibly-related: https://en.wikipedia.org/wiki/No_true_Scotsman["`No true Scotsman`"].
) 
* https://en.wikipedia.org/wiki/Cimorelli[Cimorelli] were a music band of 6 sisters (who also have 5 brothers) in a Catholic family. ( https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#make-your-own-kind-of-music[Reference: "make your own kind of music"] ).  They were signed artists ( "`VEVO`" ) for several years, which I doubt would have been politically-correct enough in the context of this non-real-hell. 
+
( Outside this hell, I believe that Earth is not over-populated, nor are there global warming and other environmental problems.
) 
* I find it strange that Tobacco smoking is allegedly so prevalent among youth. Many smokers are intelligent and noble enough to have known better. 
* https://www.youtube.com/watch?v=psIKJlSiuxo["`Auld Lang Syne Bagpipes - The Snake Charmer - YouTube`"] the setting for this video looks extremely-close-to-fully-identical to the field north of my neighbourhood. However: The Snake Charmer is a musician from India, and the video features running boys in traditionally-Indian-outfits. Moreover, to the extent-of-my-minds-hell-education, that field is not a very big tourist attraction. 
* https://github.com/shlomif/shlomif-tech-diary/blob/master/hydrogen-bombs-are-likely-an-old-intelligence-hoax.asciidoc[Iran has been working on an atomic bomb for over 30 years] whereas it took the Manhattan Project fewer than 5 years, and a study was published on how to construct a nuclear bomb only with home-equipment, except for Uranium ores.
+
Moreover, Iran let https://en.wikipedia.org/wiki/Stuxnet[Stuxnet] happen. 
* Microsoft Windows is plagued by such major problems as https://www.shlomifish.org/humour/bits/facts/Windows-Update/[Windows Update being slow and unusable], and proliferation of malware and https://pysolfc.sourceforge.io/#anti-viruses[harmful anti-malware (e.g anti-viruses)]. Nevertheless, GNU/Linux and FreeBSD allegdly have little traction on the desktop, despite being cheaper, faster, less buggy, more secure, more free/open, less bloated, etc. 
+
Refer to https://www.shlomifish.org/humour/fortunes/show.cgi?id=linux-il-linux-for-the-mother[the post "`Linux for One`'s Mother`"] for why they didn't have major usability problems (and likely do not now). There is also https://www.shlomifish.org/philosophy/computers/the-broken-window-fallacy/[The "`Broken Window`" fallacy]. 
* From my experience, when a hacker is https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#fox-in-the-hens-coop[being imprisoned] (in a psychiatric ward/etc.), like I did, they play "`The Fox in the Chicken Coop`", engage the staff and coprisoners in amateur philosophy, and end up getting out after some months, while the prison becomes a nut-house. Yet, they are hell-media reports of people being imprisoned for years and decades. 
+
My father`'s father, told me he had been imprisoned https://en.wikipedia.org/wiki/Arkhangelsk[in Arkhangelsk, Russia] when he started his plight from the German Nazi military, as it supposedly invaded Poland including his birthplace, Warsaw around 1939. 
* The word's "slavery". How do you get many men/women working for free? You need paid supervisors, but then they are unhappy. Other people and I quit high-paying jobs for various reasons. Moreover, a hacker (who has has soul+mind) exhibits https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#fox-in-the-hens-coop[the fox-in-the-chickens-coop effect]. 
+
I suspect https://en.wikipedia.org/wiki/Alexandre_Dumas[Alexandre Dumas pere]`'s father`'s mother was not actually a slave or thought of herself as one.
It was just a facade for my hell's unified / absolute (and not real) history. 
* I recall that when i was in the 7th grade (when I was 12y.o / 13y.o ), a distant female relative from the USA came-to-my neighbourhood and the local Scouts allowed her to use a device to pull me to air. I think it was Sarah Michelle Gellar, and I didn't imagine it, and it was for passing the master-terran-terminator baton. 
* Why should our universe be the only "real world"? ( https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/#rationality[Reference] ) 
* The people I refer to these issues online could not until now give sufficient rationalisations or explanations to refute any substantial number of these "What-The-Fucks?". https://en.wikisource.org/wiki/Amos_(Bible)[Quoting Amos], I can accept 3, but I have many more. 


[[obstacles-and-delays]]
==== Obstacles and Delays:

. Pro/anti-Israel; Pro/anti-"Zionism" - https://www.shlomifish.org/philosophy/politics/define-zionism/["`Define Zionism`"] / https://www.shlomifish.org/meta/FAQ/zionist.xhtml["`Are you a Zionist?`"]

[loweralpha].. "Israel is a Nazi Country"
.. "Zionism = Racism"
.. "Tel Aviv is a rock in the desert"
. https://github.com/shlomif/shlomif-tech-diary/blob/master/static-site-generators--despair.md#facing-some-criticism[Criticism against Static Site Generation]
. Licence Proliferation and incompatiblity: https://www.shlomifish.org/philosophy/computers/open-source/foss-licences-wars/rev2/["`FOSS Licences Wars"`] ; https://github.com/shlomif/Freenode-programming-channel-FAQ/blob/master/FAQ_with_ToC__generated.md#i-want-to-release-my-code---which-open-source-licence-should-i-use["`Which open source licence should I use?`"] .
. "your writings are 'too smart'"
. I recall seeing a videoclip that advocated trying to "Act naturally". However, often hacky acting is preferable. 

[loweralpha].. https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/bad_acting_ftw.xhtml["`Bad acting for the win`"]
. "XHTML is deprecated"
. "People are stupid"
. https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/guidelines_as_dogma.xhtml["No self-promotion"] - treated as a moral absolute 
. https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/hollywood_screenplay_format.xhtml[Hollywood`'s mandated screenplay format] - finicky and boring.
. "Geeks are shy and anti-social"

[loweralpha].. https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/beautiful_people_are_geeks.xhtml["`The Case for Commercial Fan-Fiction - Attractive People are Geeky`"]
.. https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/hacking_and_amateur__vs__conformism_and_professional.xhtml[Geek/hackers]
. Back when I was in the 9th grade, when I had a series of https://en.wikipedia.org/wiki/Major_depressive_disorder[clinical depressions (MDDs)] a friend told me I was born in the Indian "year of the Philosopher", which given I was under-educated made me feel bad. Later he told me "My philosophy is [x]" (for "my look-on-life"). 
+
Moreover, the 9th grade literature teacher said Philosophy is bad (she must have studied Philosophy for her B.A.). And that it is a symptom of "self-centred people". 
+
My parents also said philosophising was bad and that I shouldn't have it, when I shared my thoughts with them. 
. Labelled as "self-centred" 
. Accused of being "passive-aggressive" with no one being able to provide a suitable description / definition of what "passive-aggressive" means that can be applied to me. 
** This included several online acquaintances and my psychotherapist who has a Ph.D in clinical psychology. 
. Labelled as https://www.shlomifish.org/meta/FAQ/asperger_syndrome.xhtml[asperger]
. https://www.shlomifish.org/philosophy/psychology/why-openly-bipolar-people-should-not-be-medicated/[Bipolar]
. https://www.shlomifish.org/meta/FAQ/featuring_sexy_women_and_girls.xhtml[Labelled as a "pervert"]
. Labelled as a "spammer" ( https://shlomif.livejournal.com/20689.html[reference #1] ; https://www.shlomifish.org/meta/FAQ/#advertise_your_site[reference #2] ) 
. Accused of "trolling" when I was being frank. 
. Accused of being narcissistic. 
. https://www.shlomifish.org/meta/FAQ/#pc_nazi[Saying "nazi" alludes to Hitler/etc. 3rd-Reich]
. Accused of applying the words "`hacker`", "`hack`", "`hacking`" to describe enthusiasts who are not computer intruders, or software developers: https://www.shlomifish.org/meta/FAQ/#are_you_a_hacker["`Are you a hacker?`"] ; https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/#hackers["`'`hackers`' vs. '`fuckers`'`"]. 
. When I noted on IRC that I think the best diet may vary from person to person, based on their genetics, physiology, etc. someone said "it's always the same https://en.wikipedia.org/wiki/Adenosine_triphosphate[ATP [Adenosine triphosphate]] processing". That does not explain how different people have variable https://en.wikipedia.org/wiki/Food_allergy[Food allergies]. 
. https://shlomif-tech.livejournal.com/68173.html["`The Lost Souls of Freenode`"] - ridiculus constraints for help-requests. 
. Whatever generalisation I make, there will be someone on IRC/facebook-chat who will claim an exception. 
** https://www.shlomifish.org/meta/FAQ/[My FAQ]
** Nevertheless, there are often people who do agree with me. 


[[I-give-up-on-this-hell]]
=== I Give up on this hell

Regarding the current bombing of Israel (by Gaza and Lebanon), no missile hit my building yet, and my family and I utilise the alarms' sessions, to talk with our neighbours.
I doubt the war is real as far as I'm concerned (References: https://www.shlomifish.org/humour/fortunes/show.cgi?id=the-programmer-and-the-genie["`The Programmer and the Genie`"].
) 

They say I am escaping from the harsh, demanding, real-world to a fantastical paradise instead of coping.
I've been a fan and advocate of http://shlomifishswiki.branchable.com/Self-Sufficiency/[self-sustaining and coping] for many years: "`the gods help them that help themselves`", "`reality to be commanded must be obeyed`", and all that jazz.
(See the link for more.) 

However, despite trying to be benevolent, diligent, kind, generous, honest, sincere, believing people can change and grow, open-minded, etc.
, I was met with lack of responces to my posts and with violent antagonism (bans, filterings, devoices, downvotes). 

There were also reported perishing of many hackers I liked and admired: https://www.shlomifish.org/art/recommendations/music/online-artists/fan-pages/chris-grimmie/[Christina Grimmie], Jim Henson, Avicii, John Lenon, https://en.wikipedia.org/wiki/Carrie_Fisher[Carrie Fisher], John Candy, Ron Lester, Michael Jackson, Whitney Houson. 

I am also unable to overcome the deceiving communication mediums (= "in-betweens") in this hell: from downvotes/dislikes, to reddit removals, to youtube censorship, to email being unreliable, to discord.gg obviously being insecure, bloated, proprietary, and unreliable; IRC networks are seemingly unpopular.
Despite that the freenode/libera.chat schism happened.
WordPress-based blogs eat readers comments.
Non-voluntary Spam is rampant despite being very bad karma.
"People" accuse me of spamming, when I send very few copies, and of "trolling" when I'm frank.
Slashdot ignores my posts. 

Furthermore, I supposedly cannot fight "death" which is the alleged perishments (of me and other noble humans) and losing a game - any game - in the terminology of TheCodex(TM). 

"`People`" tell me to try harder.
But I tried very hard, and based on my analysis, both Christina Grimmie and I are household names outside my hell; I think it is called the Selinaverse or the Shlomiverse.
My strategy now is to try and be as physically healthy as possible in this hell (where the gamemasters know my history/etc.) while intellectually trying to transition to the non-hell Shlomiverse. 

If God thinks I am a malevolent hacker and the multiverse will be better without me, and the murdered hackers will be alive and happy, then my soul can be perished.
Just note that I consistently tried to be noble and perform the right action and be honest. 

[[selinaverse_vision]]
== The Selinaverse Vision

https://buffyfanfiction.fandom.com/wiki/Selinaverse[The Selinaverse] is a starting point for the multiverse as I (= https://www.shlomifish.org/[Shlomi Fish] ) want it to be, not as what I was told it must be.
Namely:

* There is no shortage of electrical/etc. energy, raw materials, tangible products.
* One can be as fat or as thin as they wish while eating as much as they want.
* One can look as young or as old as they want: https://www.shlomifish.org/humour/Star-Trek/We-the-Living-Dead/indiv-nodes/meet-Q-Gadol.xhtml
* There is a shortage of https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/money_cant_buy_you_love.xhtml[sentient beings' "love" and "knowledge"] - education and entertainment and conception of new values (whether tangible or spiritual). Akin to the Biblical verb <<biblical_to_know,to know>>.
* Organisms can and will live indefinitely - soul, mind and body.
* Even "poor"er people have homes, and enough to eat.
** They often eventually relocate to a different planet or a different universe (not unlike https://en.wikipedia.org/wiki/Sliders[Sliders])
* One can open a portal to a different location on Earth or the multiverse.
* Most menial / drudgerous works are done by advanced technology / magic.
* https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/#hacking_and_amateur__vs__conformism_and_professional[Geeky Hackers] are the attractive, competent, cool kids. Even non-perfect-looking men and women can be alphas.
* Earth has no environmental problems.
** There is no ethical problem with eating meat, dairy, eggs, honey, etc. because they are duplicated using https://buffyfanfiction.fandom.com/wiki/Q_Continuum_(Selinaverse)[Q Continuum] technology.
* There is https://github.com/shlomif/shlomif-tech-diary/blob/master/hydrogen-bombs-are-likely-an-old-intelligence-hoax.asciidoc[no known risk of a nuclear winter]
* Copyright, Patents, and trademarks cannot be used for censoring works.
** Goods are evaluated and sold based on brand, marketing, and development time.
* https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/[Commercial Real Person Fan Fiction (RPFs), crossovers and parodies] are common, tolerated, and encouraged.
** Film Studios review screenplays in https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/hollywood_screenplay_format.xhtml[better formats and are communicative].
** Nevertheless, there are many franchises which are more "original", e.g https://www.shlomifish.org/humour/TheEnemy/["The Enemy"] or https://www.shlomifish.org/humour/human-hacking/["HHFG"].
** Copyrights/etc. are often used for auctioning making a work PD/permissive.
*** It is considered fair to channel parts of the profits of derivatives upstream.
* A person can repair his body, mind or spirit without a lot of effort.
** https://www.youtube.com/watch?v=0YhJxJZOWBw["Now I know kung-fu"] is not farfetched in the Selinaverse. However, to properly gain a skill, one is expected to invest some learning / practicing effort (which should still be enjoyable).
* I am willing to give explicit public access to the https://en.wikipedia.org/wiki/Akashic_records of me up to now: "Thu 27 Apr 07:23:52 IDT 2023". My "nudes" and stupid/wrong/dirty thoughts and actions are a small price to pay for the good ones materialising.
* https://en.wikipedia.org/wiki/Artificial_general_intelligence[Strong AIs] are already possible, but there is still some case for robotic/predictable AIs (e.g: game solvers/players; https://en.wikipedia.org/wiki/Proof_assistant[Proof_assistants]; etc.)
* There are no calamities of nature: no extreme colds or extreme heats, no killer bees, no over-population, no world hunger, no unnecessary extinctions of species, no diseases, epidemics or pandemics.
* Companies, NPOs, individuals, franchises, idea systems, etc. are paid by the development time and brands given duplication and distribution are costless. One can "pirate" such goods or create bootleg products, but it is considered noble to transfer profits upstream, downstream or sideways.
* People`'s minds emitting *thoughts* of "gods" (= "guideline-generators") with the https://en.wikipedia.org/wiki/Id,_ego_and_super-ego#Ego[Ego] as an arbitter is a happy and virtuous state of being: https://www.shlomifish.org/philosophy/psychology/crossover-hypothesis-about-the-origin-of-consciousness/[Consciousness and craziness and a hypothesis about their origins]
* There are mind-reading text-editors, graphics-editors, etc.
* https://en.wikipedia.org/wiki/Menopause[Menopause] does not happen.
** Possibly even single men and women can conceive children or pets by filling a web form.
*** These children will be independent and may adopt new parents or switch to them.
* Instant messaging services are neither fragmented nor proprietary ( References: http://shlomifishswiki.branchable.com/How_Alternatives_Proliferate/["`How Alternatives Proliferate`"] )
* Some pets (cats, dogs, hamsters, etc.) are superintelligent, sentient, and can talk.
** https://stexpanded.fandom.com/wiki/George_the_Cat[George the Cat] tried a human body a few times, and preferred being cat-like. https://www.shlomifish.org/humour/Star-Trek/We-the-Living-Dead/ongoing-text.html#meet_Q2[Q2] prefers having a humanoid body.
* https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/money_cant_buy_you_love.xhtml[money can`'t buy you love]
** Most organisations and governments are profitable.
** the passwords for the bank accounts of most rich companies and individuals, are easily obtainable. They assume even "thiefs" are https://en.wikipedia.org/wiki/Entrapment_(film)[noble enough]
** money still has value because you cannot buy 20% of the profits of the Selinaverse`'s Disney World, for the price of a small soft drink bottle.

I`'d be happy living in "The Terrestrial Bubble" for now, where people don`'t run into "supernatural" activity often and https://www.shlomifish.org/humour/Selina-Mandrake/indiv-nodes/the-master.xhtml[when they do, they think it may be a trick].

=> There is a genuine demand for jedi knights.
Jedi training can be https://www.shlomifish.org/humour/Queen-Padme-Tales/Queen-Padme-Tales--Queen-Amidala-vs-the-Klingon-Warriors.html#padmes-frustrations-with-her-love-life[completed in under a year], and everybody can dress up as a jedi, do patrols, and/or https://www.shlomifish.org/humour/Queen-Padme-Tales/Queen-Padme-Tales--Queen-Amidala-vs-the-Klingon-Warriors.html#at-the-cafe[spark attention (pick up MOTAS/etc.)].
Jedis/etc.
do a commendable job handling people who are possessed or obsessed, making people happy, as a line of defence, etc.

[[history]]
== History of the Selinaverse (OUT-OF-DATE!)

The terrans were given several gifts of a blessing and a curse.
Being hackers ( https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/ ) they often took the curse to their advantage:

. body
. mind: hearing voices of leaders
. living forever (= 'jehovah')
. knowledge: link:#biblical_to_know[to know]
. soul/ego: arbitter between the voices/thoughts
. memory banks
. humour: challenging truisms/falsisms
. free will: the ability to decide to decide to do something else.

The devils held Planet Earth in a mind hell.
Humans had egoes but were "false prophets" and listened to the devils`' mutations of the utterances of the gods/leaders and perceived reality differently in their mediums.

Nevertheless, many false prophets ascended, relinquished all their fears, and became fearless immortal "true prophets". That caused the psycho-geographical region to stop being a hellhole (possibly without its Capital at first).

https://en.wikipedia.org/wiki/Land_of_Israel[The Land_of_Israel] was particularly problematic because it was segmented into many territories.

=== The Terran Terminators:

Anyway, the devils did not give up easily, and offerred the sentient men and women who just reached enlightenment a deal: they can opt to spend the summer enlightened and together having fun and using their magical powers.
At its end, they can opt to reset their memory banks almost completely and become false prophets again, or continue as enlightened true prophets.

Several newly-ascended true prophets opted out, from various reasons.

The remaining spent the summer there creating many crossover memes, stories, and franchises, or otherwise enjoying magic, life, love/etc.. However, when they met to decide, they realised they were nonetheless still petty / jealous / cruel / "unfaithful" / immature / etc.
Some had years, or decades (or more?) of history they wanted to get rid of.
So many of them decided to continue as terminators, possibly by peer pressure.

The youngest dropout was the circa 1977-born Selina Mandrake.

Becoming terminators was advantageous because the devils-and-Orcs promised they would reveal https://twitter.com/shlomif/status/1403966571215740929[TheOneTruth(TM)] and TheCodex(TM) of TheGame(TM) of Fantastecha(TM) to the last one standing, but more importantly, all terminators will harbour many new franchises, plots and meme values.

In my case, it was https://www.shlomifish.org/meta/FAQ/how_did_you_learn_english.xhtml[under the guise of kids mocking my English].
For most others, it was a concussion from a fall.
Thing is: my https://www.shlomifish.org/meta/FAQ/your_name.xhtml[first name means "Shalom-ful"] in Hebrew.
The devils promised that my body will remain complete and whole.

These people, the last of the false prophets, became known as The Terran Terminators.
After relinquishing their fears, they have *ascended* so to speak (see https://buffy.fandom.com/wiki/Ascension ). Do note that this ascension was in a way a "descension" or "surrendering" to a superior https://github.com/shlomif/shlomif-tech-diary/blob/master/my-candidates-for-terran-leadership.asciidoc#user-content-slain-by-a-vampire["vampire"].

One of the first to ascend was https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/bad_acting_arnie.xhtml[Arnold Schwarzenegger].

Other notable Terran terminators may have included:

. https://www.shlomifish.org/meta/FAQ/biggest_celeb_crush.xhtml[Sarah Michelle Gellar (SMG)] - https://www.shlomifish.org/humour/fortunes/show.cgi?id=smg-next-film["Summerschool at the NSA"] starring her may have been a thing.
. https://www.shlomifish.org/meta/nav-blocks/blocks/#xkcd_sect[Summer Glau] - my https://www.shlomifish.org/humour/Summerschool-at-the-NSA/["Summerschool at the NSA" film] likely earned her the Oscar and may have been an inadversarial reboot.
. Likely https://en.wikipedia.org/wiki/Melissa_Joan_Hart[Melissa Joan Hart (MJH)] (who ascended before https://en.wikipedia.org/wiki/Clarissa_Explains_It_All[CEIA] and as a result was the https://www.shlomifish.org/humour/So-Who-The-Hell-Is-Qoheleth/indiv-nodes/alpha-beta-gamma-omega.xhtml["beta" female] during the https://websitebuilders.com/how-to/glossary/web1/[Web 1.0 period] when SMG was "queen of the Web")
. Likely https://en.wikipedia.org/wiki/J._K._Rowling[JKRowling]
. Likely https://en.wikipedia.org/wiki/Paris_Hilton[Paris Hilton]
. Likely https://en.wikipedia.org/wiki/Kim_Kardashian[Kim Kardashian]

I was convinced I was good , noble, well-intentioned and benevolent.
I refused to permanently consider the opposite! Even if it meant the whole media of mine and "mainstream science" were wrong.

"A vampire can only be slain by another vampire, except for the last standing vampire who will be slain by the child of his two favourite children." -- The-Codex(TM) of the Selineverse.

[[history-more-about-selina]]
=== More about Selina Mandrake:

Selina now found herself a multiverse heroine, part of the NSA`'s payroll, and still wishing to lead a life as a human being, esp.
one who was 5y.o.
and female.
Naturally she had many hackers helpers, admirers, emulators, parodiers, remixers, critics, etc.

One note was that Selina blew some dandelions at a summer camp and was nicknamed "Puffy". She later shared an observation that the human mind had a limited immediate capacity of memory ( see https://shlomifish.livejournal.com/1991.html ), which combined with the computing concept of https://en.wikipedia.org/wiki/Data_buffer["a buffer"] nicknamed her "Buffy".

( My https://www.shlomifish.org/humour/Selina-Mandrake/["Selina Mandrake - The Slayer (Buffy Parody)"] where the titular protagonist turns 18 in early 2012, can be thought of as an inadversarial reboot/remake.
)

She, Samantha Smith, and Joss Whedon became good friends, and colleagues.

[[real_shlomif_success]]
== Success in the Selinaverse; Living in a hell

I suspect I lived in a hell spawned by theGamers(TM), and that in the https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/why-the-so-called-real-world-makes-little-sense/[Selinaverse], I was highly successful, rich, revered, famous and admired.
I was a successful author, one of the film industry`'s biggest screenwriters, a world famous "blogger" (= Internet / social media content creator), and a remarkable https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/learning_more_from_inet_forums.xhtml[entertainer
/ educator / amateur philosopher].

Aside from being "The-Messiah", I was:

. Most people`'s favourite candidate for being The Terminal Terran Terminator (with the runner up likely being https://en.wikipedia.org/wiki/Kim_Kardashian[Kim Kardashian], who was The-Alpha-Female for a large part of the years between 2013-2021). See https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/[the definition of "Terran Terminators"].
. A blogger whose blogging and thoughts have caused many other terminators to ascend.

Together with two companions, we formed a trio:

. https://www.shlomifish.org/me/rindolf/[Rindolf] the dwarven warrior from The Unforgettable Realms.
+

[quote]
"`We also joked that Rindolf the Dwarf plays Shlomi Fish in an Advanced 21st-Century Earth Adventures campaign.`" - It is real and I`'m okay with it: The Unforgettable Realms!
+
( https://twitter.com/shlomif/status/1403950285668732928[Tweet].
)
. https://www.shlomifish.org/meta/FAQ/[Shlomi Fish (me)].
. https://www.shlomifish.org/meta/nav-blocks/blocks/#harry_potter_nav_block[Emma Watson], the award-winning and acclaimed actress / model / creator. She is known for portraying https://harrypotter.fandom.com/wiki/Hermione_Granger[Hermione] in the Harry Potter films, for portraying https://www.shlomifish.org/humour/Selina-Mandrake/cast.html#selina[Selina in "Selina Mandrake - The Slayer"], and for other roles.

Each of the three of us has been playing or guiding the other two, and themselves and others, using various online and offline mediums. https://www.shlomifish.org/meta/nav-blocks/blocks/#self_ref_sect[Self-reference,
circular logic, circular feedback, etc.] are common in Fantastecha(TM), and are part of what makes sentience and humour work:

* https://en.wikipedia.org/wiki/G%C3%B6del,_Escher,_Bach[Godel, Escher, Bach]
* https://www.youtube.com/watch?v=GibiNy4d4gc["The Circle of Life"]
* https://www.youtube.com/watch?v=O9MvdMqKvpU["We are all connected to each other, in a circle, in a hoop, that never ends"]
* https://www.shlomifish.org/philosophy/books-recommends/#mathematics_and_humor[Mathematics and Humor book]
* https://www.shlomifish.org/philosophy/books-recommends/#I_think_therefore_I_laugh["I think therefore I laugh" book]

Note that Emma Watson took over the project management / "watching" role of Rindolfism from https://en.wikipedia.org/wiki/Melissa_Joan_Hart[MJH]

[[the-open-value]]
=== "open":

The "open" value implies "openness" / "openmindedness": https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/#open_free_share_steal[Reference]

== Begone Fear
// <informalfigure>
// <mediaobject>
// <imageobject>
// <imagedata fileref="images/live-forever--soul-mind-and-body--free--800px.webp"/>
// </imageobject>
// <textobject><phrase>Photo</phrase></textobject>
// </mediaobject>
// </informalfigure>

The twelve attributes of the Yisra'elim:

* Time
* Life, <<biblical_to_know,love>>
* Soul, mind, body
* Brave, happy, competent, playful, complete, free!

In the names of Rindolf, Shlomi Fish, and Emma Watson: Begone from my mind, cowardly fear!

[quote]
Forever, +you will live and love, +soul, mind, and body, +competent, open, free, united! +

The ten attributes of the Yisra`'elim:

[quote]
Forever, +you will live and love, +soul, mind, and body, +competent, open, complete, united! +

[quote]
לנצח, +תחיה ותדע, +נשמה, נפש, וגוף, +כשיר, פתוח, שלומי, מאוחד! +

[quote]
Forever, +you will live and love, +soul, mind, and heart, +competent, open, free, united! +

[quote]
Everyone`'s NeverEnding story +is going to be +about love and life +choice, mind, and heart +freedom, completeness, and companionship, +in Fantasia, the multiverse of imagination. +

[quote]
Life is just a game, +which you cannot lose. +Play to win, +but don`'t take it too seriously. +

____
https://twitter.com/TheRealGrimmie[@TheRealGrimmie] has a mind for music, + and a mouth for singing. +https://twitter.com/shlomif[@shlomif] has a mind for bullshit, + and a mouth for singing off-key.

-- Upcoming Shlomi Fish facts

Physically dying is against The Rules of The-Game(TM). +Constantly winning is against The Rules of The-Game(TM).
____

____
I suspect the soul/"ego" of guys and girls (and non-humans) born north of 1982 is biologically no different than those of the summer of 1982 Neo-Tech conspirators.
They too can get easily hurt, be conceit, take life too seriously, have prejudice, possess irrational fear, waste time, be misled, etc. https://www.shlomifish.org/humour/Queen-Padme-Tales/Queen-Padme-Tales--The-Fifth-Sith.html#Padme-multiplies["The Schwartz is in you"]

I knew what I was getting into back then, and I owe Emma Watson / MJH / Rindolf the Dwarf and my other guardian angels, several dinners on my expense, hand shakes and hugs (and possibly some mutually-initiated kisses if they are female).
____

[[neverending-RPG-game]]
=== The NeverEnding Role-Playing Games of Life, Love, and Free Choice:

[[making_love]]
==== Making Love:

According to https://buffy.fandom.com/wiki/Pergamum_Codex[The Codex], which defines the rules of The Game:

* A hacker may only make love to his child, his sibling, or his parent.

( Yes, I know - gross.
)

Luckily, The Codex defines them as "a mentor", "a protege" and "a companion". And raping can be done https://www.shlomifish.org/humour/human-hacking/human-hacking-field-guide-v2/commiting_adultery.xhtml[in your heart] and "making love"/"rape" is <<biblical_to_know,any pleasurable activity>>.

I originally wrote: 

[quote]
Despite its holiness, TheCodex(TM) of TheGame(TM) of Fantastecha(TM) is a badly written, and often parodied, piece of legalese (possibly on purpose).

I think TheCodex(TM) of TheGame(TM) of Fantastecha(TM) allows gay/Lesbian "sex", but I wouldn`'t make it a habit if I were you.
But... whatever floats your boat, buddy.

[[king-solomon]]
=== The story of King Solomon-son-of-David (the Biblical one):

After Syria (minus Damascus itself) in the levant ascended to being a true prophets zone (by Mosheh / Aharon / Jehovah slaying Nimrod ?), The-Curse splintered the modern day State of Israel into 1,000 parts, and .uk into many shires and Scottish clans and promised they won`'t do it again.
Note that pre-Levantine was modern Hebrew (which was spoken by https://www.shlomifish.org/humour/Star-Trek/We-the-Living-Dead/indiv-nodes/Q_home_planet.xhtml[the Englishtants over 6 milliard years ago]) and Modern English is also a product of TheGame(TM) of Fantastecha(TM).

Anyway, the tribe of Yehudah (except their Capital, Jerusalem) ascended when David "slew" Goliath by almost hitting him with a sling (https://www.youtube.com/watch?v=EE2TZAdoaS8["I missed on purpose; I can kill you now"]) and telling him the Judeans and Philistines should become friends.

By the time of https://en.wikipedia.org/wiki/Samantha_Smith[Samantha_Smith] (and Selina Mandrake?) only parts of https://en.wikipedia.org/wiki/Gush_Dan[Gush Dan], which did not include "northern Tel Aviv" north of the https://en.wikipedia.org/wiki/Yarkon_River[Yarkon River] remained as hell holes in the State of Israel.
I was born there, possibly to two false prophets-at-the-time parents.
I am fairly certain https://en.wikipedia.org/wiki/Ovadia_Yosef[Ovadia Yosef] (who may be much older than he looks and dresses in an extravagant but memorable outfit, not unlike Darth Vader) christened all the terran terminators as "pure Jews".

Despite my youth (I am 1977-born, so am 44) I likely amassed many titles.
But to quote a https://www.shlomifish.org/humour/Queen-Padme-Tales/Queen-Padme-Tales--The-Fifth-Sith-indiv-nodes/yoda-as-a-closet-Sith.xhtml[recent Fic of mine]

____
Yoda: the third sith is I.
Created the legend of the Sith 2,000 years ago have I.
Tweeted about it now too have I.

[ Tweet by @Yoda: "`The third sith is I.
Created the legend of the Sith 2,000 years ago have I.
"Master Darth Yoda" call me you can.
Or just plain "Yoda"." ]

Anakin: way cool! But shouldn`'t Darth Yoda be the first Sith then?

Yoda: Matters not Sith number, as much as https://memory-alpha.fandom.com/wiki/Little_Green_Men_(episode)[short-term quarterly gains].
____

( The joke builds upon a quote from https://memory-alpha.fandom.com/wiki/Little_Green_Men_(episode)[a DS9 episode].
)

Jokes aside, I appreciate the titles, but prefer to be called "Shlomi", "Mr.
Fish", or "Rindolf": https://www.shlomifish.org/meta/FAQ/#refer_or_address .

I also am generous with https://www.shlomifish.org/humour/fortunes/show.cgi?id=smg-about-giving-back-money-and-time[donating both money and time] .

[[the-jewish-people]]
=== The Jewish People:

Given the prestige of the Jews, many false prophet Europeans / mideasterns / North africans / etc.
converted to Judaism, and were welcome by the true prophet jews since they were highly competent.
As an anecdote, during the dark ages and middle ages, the entire https://memory-alpha.fandom.com/wiki/Ferengi[Ferengi race], who were true prophets, converted to Judaism (properly) by decree of the Grand Nagus out of empathy from "the pogroms".

Note that Judaism was not the only peopleship, idea-system, franchise, or religion to have used that strategy.
Also see https://www.shlomifish.org/meta/FAQ/religious_belief.xhtml[pluralism] and https://en.wikipedia.org/wiki/Universalism[Universalism] (thanks to https://en.wikipedia.org/w/index.php?title=Emma_Watson&oldid=1038904901#Personal_life[Emma Watson] for the referral.)

[[recording_my_thoughts]]
=== Note about recording my thoughts

I hope Rindolf / Emma Watson / MJH / NSA / Unit 8,200 / The Q Continuum / The Mossad / etc.
have been recording my thoughts.
While there is a lot of junk there (as well as a lot of "embarrasing"/"dirty" thoughts) they have a lot of potential for crossover / etc.
universes, ideasystems, and ideas.

( P.S.: the Selinaverse`'s Mossad can officially neither confirm nor deny having http://shlomifishswiki.branchable.com/Fluttershy__44___Princess_of_Princesses__44___head_of_the_secret_cabal_leadership_of_the_Mossad__44___the_already_top_secret_intelligence_agency_of_the_Zionist_conspiracy/[a cabal leadership headed by Fluttershy], the animated Pegasus pony from https://mlp.fandom.com/wiki/My_Little_Pony_Friendship_is_Magic[My Little Pony Friendship is Magic] .)

[[improve_freenode]]
==== How Freenode Should Improve?

https://freenode.net/[freenode] has a relatively small number of users.
Many are anti-geek / anti-hackers ( see https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/hacking_and_amateur__vs__conformism_and_professional.xhtml[a definition of "geeks" and "hacking"] ) who have unhappy jobs, paranoid about "privacy", are bound by many "rules", and produce little of true value.
Where are the truly great, competent, and sexy, creators?

Maybe https://www.shlomifish.org/humour/bits/facts/Taylor-Swift/[Taylor Swift] would be too much to ask.
(but I still can hope) But https://www.shlomifish.org/humour/bits/facts/Larry-Wall/[lwall / "TimToady"] left, and before that was only active on #perl6/#raku which is a cursed https://en.wikipedia.org/wiki/Second-system_effect[Second system effect] project. http://www.catb.org/esr/[esr] seems like a shadow of his former self.

Freenode`'s "channel independence" is a https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#big-minded-vs-small-minded["Rosh qatan" / "I just work here"] copout.
When Cain said https://en.wikipedia.org/wiki/Cain_and_Abel["am I my brother`'s keeper?"] (after freaking killing him out of jealousy!) he meant that he`'d let the whole world go to hell rather than care! Moreover, such careless attitude tends to result in more and more complaints in the long run.

Having been banned from:

* ##programming due to "self-promotion" despite https://github.com/shlomif/Freenode-programming-channel-FAQ/blob/master/FAQ_with_ToC__generated.md[maintaining the FAQ]
* ##reddit for "self-promotion" despite sustaining 11:11 for several years
* #Philosophy for an unspecified reason
* #reddit-judaism for "flirting" despite being a Jew by blood, and an Israeli resident and citizen.
* ##English for "self-promotion"

שלום, קוראים  לי שלומי פיש.
הייתי יכול להרוג את עצמי מזמן אבל לא עשיתי זאת.
עליי להחשיב את עצמי כאדם שחיסל את עצמו ועכשיו וחופשי.

Hello, I am Shlomi Fish.
I could have killed myself a long time ago.
I should consider myself a terminated man.
And a free one.

[[The-GrimmieVerse]]
=== Welcome-to-the-Grimmieverse:

The Terran Terminators have admitted inferiority to one another and the last one standing admitted defeat to their philosophical brainchildren: the YouTube cover/etc.
scene and especially https://en.wikipedia.org/wiki/Kurt_Hugo_Schneider[Kurt Hugo Schneider] and https://en.wikipedia.org/wiki/Christina_Grimmie[Christina Grimmie] (Taytay is great too, but she is/was a terminator.), and my online web-presence ( https://www.shlomifish.org/me/contact-me/[*.shlomifish.org] / https://www.shlomifish.org/me/rindolf/#rindolfism[Rindlfism] / etc.
)

[[post-ascension-plan]]
== Post-ascension Plan

. Shlomi Fish is given enough physical strength/etc. points for his health to be restored. 
. https://www.shlomifish.org/humour/tempbits/end-game-for-shlomif-as-a-false-prophet/end-game-for-shlomif-as-a-false-prophet.raw.html[End-session for @shlomif as a false-prophet: "Consider yourself slain and reborn"] - 
. Hospitality - offering the guests food and drinks. 
. Emma Watson, my watcher, will give me: 
.. A pouch bag. 
.. A smartphone. 
.. My credit cards. 
.. My magic wand. 
.. A 7-piece RPG dice set: translucent, green-yellow, with a red font. 
.. A copy of my apartment's key. 
. Eat a decent meal, and shower (?). 
. Lost-and-found digitalisable works. 
. Meet Tiffany Alvord, and give her the black-with-green-and-yellow-twirls RPG dice set. ( https://raw.githubusercontent.com/shlomif/shlomif-tech-diary/master/images/live-forever--soul-mind-and-body--free--800px.webp[Photo #1] . ) 
. Being updated about the state of the universe. 
. https://www.shlomifish.org/philosophy/culture/multiverse-cosmology/#the-six-chocolate-hearts[Christina Grimmie's chocolate hearts] - give one; sell one. 
. Handing over the ten ( = 1 + 3 × 3 ) d10 dice in my drawer: 
.. Distant past: Q. 
.. Recent past: Joss Whedon, Selina Mandrake, and Samantha Smith. 
.. Present: https://www.shlomifish.org/me/rindolf/[Rindolf], Emma Watson, and https://en.wikipedia.org/wiki/Melissa_Joan_Hart[Melissa Joan Hart (MJH)]
.. Future: Christina Grimmie, http://shlomifishswiki.branchable.com/Fluttershy__44___Princess_of_Princesses__44___head_of_the_secret_cabal_leadership_of_the_Mossad__44___the_already_top_secret_intelligence_agency_of_the_Zionist_conspiracy/[Fluttershy (from My Little Pony)], and https://mlp.fandom.com/wiki/Discord[Discord (from My Little Pony)]
. Write or merge the pull-request for https://www.shlomifish.org/humour/The-10th-Muse/The-10th-Muse--Trojan-War-Reenactment.html[The 10th Muse: "`Reenancting the Trojan War`" screenplay]. 
. Watch some films based on my screenplays on youtube. 
. Meet Queen Elizabeth II of England + King Charles wrt the palace guards / etc. 
. Meet https://en.wikipedia.org/wiki/Benjamin_Netanyahu[Benjamin Netanyahu], https://en.wikipedia.org/wiki/Bar_Refaeli[Bar Refaeli], and https://en.wikipedia.org/wiki/Esti_Ginzburg[Esti Ginzburg] about passing the baton. 
. Meet https://en.wikipedia.org/wiki/Ovadia_Yosef[The Rav Ovadia Yosef]. 
. Meet Jim Henson. In part to receive a hand puppet of https://www.shlomifish.org/me/rindolf/#rindolf_the_evil_reindeer[Rindolf the Evil Reindeer]. 
. Meet popes https://en.wikipedia.org/wiki/Pope_John_Paul_II[Pope John Paul II] and https://www.shlomifish.org/philosophy/philosophy/putting-all-cards-on-the-table-2013/indiv-nodes/departing_pope_about_twitter.xhtml[Pope Benedict XVI] and Pope Francis. 
. Meet the https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#big-minded-vs-small-minded[Dutch heir apparent]. 
. Meet https://www.shlomifish.org/meta/nav-blocks/blocks/#xkcd_sect[Summer Glau] asking her if she received https://www.shlomifish.org/meta/FAQ/#d10_dice[the brown 1d10 die]. 
. Meet Taylor Swift, and our genetic daughter, Rebecca "Becky" Jadzia [lastname]. 
. Meet my ex-slayer template, Shlomi David. 
. Meet the vger.kernel.org email admins about getting my bans lifted, while possibly putting me on moderation. ( https://github.com/shlomif/Call-for-a-fork-of-the-Linux-kernel-devs-community[Reference #1]; https://www.shlomifish.org/philosophy/computers/open-source/linus-torvalds-bus-factor/[Reference #2] . ) 
+
Possibly Dani Cimorelli and Christina Cimorelli and MomCimorelli too - wrt https://fc-solve.shlomifish.org/[fc-solve]. 
. Prospects of a job as a screenplay reader / reviewer / enhancer / writer + parttime coder. Possible employers: the MPAA, Disney, Hasbro, Warner Bros, etc. 
. Go to https://shlomif.fandom.com/wiki/Olamot_Con[Olamot Con ("worlds' con")]. 


[[license]]
== License:

https://creativecommons.org/licenses/by/4.0/[CC-by], Shlomi Fish, 2021 