Date: 2021-05-19

From: https://www.shlomifish.org/me/contact-me/[Shlomi Fish]

URL: https://is.gd/1vNvze

Here are some reasons the outside world as I perceive it makes little sense:

The epistemological demons:
---------------------------

We seem to be dealing with epistemological demons.

I exhibit a Descarteseque https://en.wikipedia.org/wiki/Evil_demon[Evil demon] - like situation. The demon contorts my perception of the outside world, and may input false emotions and the occasional false thought, but I still have my centre-of-consciousness (aka "the soul", or "the ego"), logic, reason, and older memories.

Prior art for my situation:

* https://www.shlomifish.org/humour/Selina-Mandrake/#sources_of_inspiration - Selina
** https://en.wikipedia.org/wiki/Labyrinth_%281986_film%29[Labyrinth] - Sarah
** https://en.wikipedia.org/wiki/Buffy_the_Vampire_Slayer - Buffy gets sucked into a demnic underworld
** https://en.wikipedia.org/wiki/The_Hobbit[The Hobbit] - Bilbo is drawn out of his comfrt zone
* https://en.wikipedia.org/wiki/The_Truman_Show
** https://en.wikipedia.org/wiki/The_Prisoner
** https://en.wikipedia.org/wiki/The_Matrix
* http://www.earthstar.co.uk/deep3.htm[H2G2's Planet Earth as a Computer] - «"I speak of none other than the computer that is to come after me," intoned Deep Thought, his voice regaining its accustomed declamatory tones. "A computer whose merest operational parameters I am not worthy to calculate - and yet I will design it for you. A computer which can calculate the Question to the Ultimate Answer, a computer of such infinite and subtle complexity that organic life itself shall form part of its operational matrix. And you yourselves shall take on new forms and go down into the computer to navigate its ten-million-year program! Yes! I shall design this computer for you. And I shall name it also unto you. And it shall be called ... The Earth."»
* https://www.shlomifish.org/humour/fortunes/show.cgi?id=god-and-his-angels-as-technicians : «God and his angels as implementing humans' perception of the universe»

More thoughts:
--------------

https://www.explainxkcd.com/[xkcd] had some RPF (= https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/["Real Person Fiction"], e.g: https://www.explainxkcd.com/wiki/index.php/406:_Venting ), and my https://www.shlomifish.org/humour/Summerschool-at-the-NSA/ was well-received on https://www.reddit.com/r/xkcd/[/r/xkcd] and elsewhere. Nevertheless, later on I was told "RPF? Never do that!" on an xkcd IRC chatroom, and was promptly banned.

It is not clear whether bigger muscles imply that a person is physically stronger or not.

https://twitter.com/TheRealGrimmie[Christina Grimmie] was reportedly killed after several years of not doing stuff her way.

I am a feeble and frail man who is otherwise of strong spirit, and who is attracted to strong girls, especially physically strong and/or muscular ones: https://twitter.com/shlomif/status/1394689324554334210 .

I "pirate" (= copy, share, and build upon) copyrighted works all over the place ("ARRRRRRRR!!!").

I think that commercial fan fiction not only will be ethical, but is necessary: https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/

"Science" is often a device to enforce external authority and "truisms" and "facts". Just like religions, if not worse: https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/guidelines_as_dogma.xhtml .

I think "mass production" (more like "mass duplication") has been done using Extraterrestial technology (called e.g https://buffyfanfiction.fandom.com/wiki/Q_Continuum_%28Selinaverse%29[The Q Continuum] ) given large factories, farms, and trucks/etc. make everyone who work there miserable.

⇒ The Q Continuum can duplicate or conjure energy, precious minerals, raw materials, inanimate products, foods and drinks, organisms (e.g: https://www.shlomifish.org/humour/fortunes/show.cgi?id=sharp-sharp-programming-life-according-to-valentine[Life According to Valentine] and https://memory-alpha.fandom.com/wiki/Thomas_Riker[Thomas Riker]), or even entire galaxies.

→ The media keeps saying that there'll be shortages of certain products, but it doesn't happen.

I think there has been a conspiracy of the demons inside me to try to convince me that the world outside me was getting worse, and that I was more and more isolated, friendless and unpopular. Well, game over - I won - you shall lose!

There are thousands' years old hackers (aka "vampires") and below-20 ones who are huge fans of one another: https://www.shlomifish.org/humour/Star-Trek/We-the-Living-Dead/indiv-nodes/kai-blanche.xhtml .

[id="biblical_to_know"]
It is possible yada` (= "to know" in Hebrew) meant "to educate / to entertain" and involves pleasure, but sometimes pain too, and was mutual, and always spawns ( possibly invisible ) baby angels. If it makes you bored or indifferent, it likely is not effective. https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/

I had a very short haircut for many years now and given girls have many "bad hair days" (re https://www.shlomifish.org/humour/Muppets-Show-TNI/Harry-Potter-indiv-nodes/the_beautiful_assistant.xhtml and https://www.youtube.com/watch?v=8N2k-gv6xNE ) think they may wish to follow suit: https://www.refinery29.com/en-us/2021/03/10365754/emma-watson-bob-haircut-2021

Per https://twitter.com/shlomif/status/1173621519274127361 "I love the film Labyrinth. it was so funky and nice and David Bowie was great and Jennifer Connelly was so touching and maybe could have taken the Oscar if there was no prejudice against her youth and the fact it was a fantasy/children film back then.": Jennifer Connelly likely was nominated and won (and it may not have been an age record).

⇒ Emma Watson may have won the Oscar for some of the Harry Potters: https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/bad_acting_emma_watson.xhtml

⇒ Arnold Schwarzenegger likely won it as well: https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/bad_acting_ftw.xhtml

Terran science was an epistemological facade (Faster-than-light travel, duplication of galaxies, the https://en.wikipedia.org/wiki/Akashic_records are all possible). However it turned out to be a blessing in disguise, because many Terran scientists and engineers and developers were highly concerned about efficiency and reliability. See e.g. http://www.h-online.com/open/features/Is-Microsoft-running-out-of-steam-1102654.html[the variations on the James Watt's steam engine].

As a child, I wanted to be good-hearted (= noble, honest, benevolent) and later on aspired to be world savior / messiah / "the greatest person in history". I guess "nice guys finish last".

It is not clear why we have to suffer from https://en.wikipedia.org/wiki/Consumerism[Consumerism] of large electrical appliances (e.g: washing machines and refrigerators) when they **can** be made more reliable.

I have a very low number of Twitter followers (below 650 - https://twitter.com/shlomif ) and my reddit posts are usually not upvoted a lot ( https://www.reddit.com/user/shlomif ) . This is despite some of my older posts being a staple on Slashdot and other sites (e.g: https://www.shlomifish.org/humour/bits/Mastering-Cat/["Mastering cat" Interview].)

People cite contemporary copyright law as an justification for censorship:

* https://www.reddit.com/r/Jennamarbles/comments/mjfmsj/advice_to_jenna_1_youre_awesome_i_love_you_2/
* https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/
* https://www.shlomifish.org/philosophy/case-for-file-swapping/

I lost contact with many online friends due to discontinues of IM services and me not receiving their email/etc replies. The devils are clouding my perception of the world using https://twitter.com/shlomif/status/1395025361138761729[my media].

https://freenode.net/[freenode] has a relatively small number of users. Many are anti-geek / anti-hackers ( see https://is.gd/A7rkAh[a definition of "geeks" and "hacking"] ) who have unhappy jobs, paranoid about "privacy", are bound by many "rules", and produce little of true value. Where are the truly great, competent, and sexy, creators?

The Selinaverse Vision
----------------------

https://buffyfanfiction.fandom.com/wiki/Selinaverse[The Selinaverse] is a starting point for the multiverse as I (= https://www.shlomifish.org/[Shlomi Fish] ) want it to be, not as what I was told it must be. Namely:

* There is no shortage of electrical/etc. energy, raw materials, tangible products.
* One can be as fat or as thin as they wish while eating as much as they want.
* One can look as young or as old as they want: https://www.shlomifish.org/humour/Star-Trek/We-the-Living-Dead/indiv-nodes/meet-Q-Gadol.xhtml
* There is a shortage of https://www.shlomifish.org/philosophy/culture/case-for-commercial-fan-fiction/indiv-nodes/money_cant_buy_you_love.xhtml[sentient beings' "love"] - education and entertainment and conception of new values (whether tangible or spiritual). Akin to the Biblical verb xref:#biblical_to_know[to know].
* Organisms can live indefinitely
* Even "poor"er people have homes, and enough to eat.
* One can open a portal to a different location on Earth or the multiverse.
* Menial / drudgerous works are done by robots.
* https://is.gd/A7rkAh[Geeky Hackers] are the attractive, competent, cool kids. Even non-perfect-looking men and women can be alphas.
* Earth has no environmental problems.
** There is no problem eating meat, dairy, eggs, honey, etc. because they are duplicated using https://buffyfanfiction.fandom.com/wiki/Q_Continuum_(Selinaverse)[Q Continuum] tehnology.
* Copyright cannot be used for censoring works.
* There is https://github.com/shlomif/shlomif-tech-diary/blob/master/hydrogen-bombs-are-likely-an-old-intelligence-hoax.asciidoc[no risk of a nuclear winter]

I'd be happy living in "The Terrestrial Bubble" for now, where people don't run into "supernatural" activity often and https://www.shlomifish.org/humour/Selina-Mandrake/indiv-nodes/the-master.xhtml[when they do, they think it may be a trick].
